### ISSUE TITLE
Cannot print when a conversation is opened in a new Thunderbird tab

### ISSUE THREAD

**Issue by davenz** [protz/thunderbird-conversations#1000]
Hi, 

When viewing a conversation in Thunderbird's standard message pane, one can either right-click on the conversation and select "Print..." via the contextual menu, or, go to "File -> Print..." to sucessfully print the email. 

When the same conversation is opened in a Thunderbird tab, the contextual menu is no longer available (including any option to print). In addition, although "File -> Print..." is available, trying to print in this way fails. The print dialogue simply never appears, and there is no feedback or error prompt otherwise.

I've tested this on Ubuntu 14.04 with Thunderbird v38.2.0 + Conversations 2.10, and the same combination on Windows 8.1. 

Cheers, 
Dave

**Comment by protz** [comment]
Yeah I once fixed this in Thunderbird but users were angry because it conflicted with another behavior that they were used to, so in the meanwhile, the only thing I have to offer is the "print this conversation" link at the bottom.

**Comment by davenz** [comment]
Hi Jonathan,

Thanks for the clarification. Would it be possible then to also have the "print this conversation" link at the bottom of the email specifically when the conversation is opened in a new tab? At present the net effect is that one cannot print at all when a new conversation is opened in a tab.

Cheers, 
Dave

**Comment by protz** [comment]
The link should be there. Screenshot of the bottom of the conversation?

~ jonathan

**Comment by davenz** [comment]
Ahh thanks, it totally is (right at the bottom), and I now see where I'm getting confused. When viewing a conversation in Thunderbird's main message pane, one can right-click to print a particular message within that conversation. What I was looking for (and missing because it's not there) was a "Print this conversation" link at the bottom of each message when the conversation is opened in a tab, enabling the same per-message printing available in the former scenario (which would otherwise be performed by a right-click).

I'll open a separate issue for this as an improvement request.

Cheers, 
Dave
