### ISSUE TITLE
PGP Inline Signatures look bad

### ISSUE THREAD

**Issue by yoshimo** [protz/thunderbird-conversations#1001]
If people use pgp-inline instead of pgp/mime for their signatures , there are remains of that signature which look bad.

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1
Hi
-----BEGIN PGP SIGNATURE-----
QIc.....
-----END PGP SIGNATURE-----
```

I think this should look like Kmail on Kubuntu, where the signed part of the mail gets a colored frame so you see which part is signed.
I also do not want to see the big garbage block with the signature.
The interesting part is, does the signature match the text or not.

**Comment by protz** [comment]
Is this specific to Conversations or does this also happen when you hit "more > view using the classic reader"?

**Comment by elioqoshi** [comment]
@yoshimo I have the same question as @protz (would be good to know before continuing with the redesign)

**Comment by yoshimo** [comment]
I must say it happens with classic view too.

**Comment by Standard8** [comment]
Assuming this happens with the classic view as well, then it was either an enigmail issue or a thunderbird issue.

If it still exists, it should ideally be followed up with them first.
