### ISSUE TITLE
Body of PGP/MIME email vanished

### ISSUE THREAD

**Issue by meteficha** [protz/thunderbird-conversations#1003]
Hey!

This is a strange issue.  I've received a PGP/MIME e-mail.  Thunderbird Conversations 2.10 didn't have trouble using Enigmail 1.8.2 to decrypt and display it.  

However, I wanted to see the message on Classic View.  To my surprise, Classic View showed an empty message body!  When going back to the Conversations View, the body vanished as well!

Looking at the source of the message shows the PGP/MIME "attachments".  Pressing the link on Conversations to forward the conversation works (!).  Asking to edit the message as a new one also works (!).  

I have no idea what's going on :(.  Let me know what I should do to try to debug this issue.

**Comment by protz** [comment]
Very strange. Does switching conversations help?

**Comment by meteficha** [comment]
At some point the body came back, as I went to this e-mail now and it was there.  I guess I'll close the issue as I can't reproduce it anymore :|.
