### ISSUE TITLE
Conversation not recognized by Conversations, despite being grouped by Thunderbird

### ISSUE THREAD

**Issue by RalfJung** [protz/thunderbird-conversations#1007]
There seem to be cases where Thunderbird does recognize that a bunch of mails belong to a single thread, but conversations still doesn't display them together. For example, I have here two mails (in the same folder of my local archive) with the following headers:

```
Message-ID: <55420CEB.6010006@mpi-sws.org>
```

```
In-Reply-To: <55420CEB.6010006@mpi-sws.org>
References: <55420CEB.6010006@mpi-sws.org>
Message-ID: <OFC0E843BF.67381D84-ONC1257E37.003D9983-C1257E37.003E4991@notes.mpi-sb.mpg.de>
```

After enabling threaded grouping, Thunderbird shows the two as one thread. Still, when I click one of them, Conversations does not show the other in the message view.

**Comment by protz** [comment]
It has to be an indexing problem. Did you fiddle with the global indexing settings (right-click on a folder, hit properties, and in one of the tabs, see if "include this folder in global search results" is unchecked -- it *should be checked*)? Alternatively, go to the FAQ and follow the instructions to reset global-messages-db.sqlite

**Comment by RalfJung** [comment]
That seems to have done it - I deleted that database file, and now all the threads I tried are shown correctly. I just wonder how long I have to wait until TB is done re-indexing...

**Comment by RalfJung** [comment]
I now have this issue again with a thread that only started today: I got several mails, and sent one myself, and archived all of that (into the October folder). Thunderbird shows them all as a single thread. But the plugin splits them into three conversations of the first mail, the second mail, and the mail I sent + the last reply.
After restarting Thunderbird, the split changed to the first mail, and the other three.

**Comment by protz** [comment]
Yeah, so there's basically nothing I can do about it. It's the underlying indexing system that gets confused -- called "gloda", the **glo**bal **da**tabase. There's a series of bugs about it, the original author is no longer maintaining it, I used to be a module owner, but I no longer have time to take on that task either :-/.

The workaround is to work with your threads collapsed at all times in the thread pane. That way, you well get *at least* the selected messages in the conversation...

**Comment by RalfJung** [comment]
I see - that's a bummer. With Thunderbird expanding threads by itself when I change folders, that means I find myself frequently manually collapsing threads. I understand you can't do much about that, either.

**Comment by RalfJung** [comment]
Btw, I find it confusing that bugs like this are closed. I mean, you acknowledged there is a bug here, just that you can't do much about it. By closing this bug, the next person who comes along and searches for bugs before reporting a new one will probably not even see this bug, and report a duplicate.

**Comment by protz** [comment]
Yeah, good question about these. I usually close them because 1) there's 
nothing I can do about them and 2) the bugs are not about Conversations 
but they about Thunderbird, therefore, they belong in the Thunderbird 
bugtracker.

That being said, feel free to re-open this issue if you feel that's 
useful -- I've applied the appropriate label.

(For the expansion of threads, I use the \ keyboard shortcut (collapse 
all threads)).
