### ISSUE TITLE
Doesn't integrate well with Dark themes

### ISSUE THREAD

**Issue by vishesh** [protz/thunderbird-conversations#1008]
The color scheme when using dark GTK theme such as Arc, screws up the skin. I've attached a screenshot.

![image](https://cloud.githubusercontent.com/assets/310099/9867636/03ffac66-5b3e-11e5-8893-2583b0cd07db.png)

**Comment by Redart98** [comment]
Conversation View uses window color for message background. As far as i can see, 
https://github.com/horst3180/Arc-theme
http://linuxcentro.com.br/linux/arc-theme-um-belissimo-tema-flat-para-o-linux/
Arc uses white color here. It seems that everything is working as intended, isn't it? What color is the background in default TB message view?

**Comment by vishesh** [comment]
So yes, I tried another theme and you are right, its probably the GTK theme issue not Conversation View's. I really like that GTK theme, so I tried to get the text box white to black. I can't find the appropriate CSS class however. Any clues?

**Comment by protz** [comment]
I think you can customize that within thunderbird using the options...?

**Comment by vishesh** [comment]
I don't know if such option exists.

**Comment by protz** [comment]
Edit > Preferences > Display > Formatting > Colors

**Comment by protz** [comment]
Probably need to restart Thunderbird after that.
