### ISSUE TITLE
slow script warning with handlebars

### ISSUE THREAD

**Issue by MLopez-Ibanez** [protz/thunderbird-conversations#1009]
On an IMAP account, with a folder with 1536 emails, switching from/to a thread with less than 100 messages is quite slow, in the order of tens of seconds. Sometimes, it even triggers:

A script on this page may be busy, or it may have stopped responding. You can stop the script now, or you can continue to see if the script will complete.

Script: chrome://conversations/content/js/handlebars-v3.0.0.js:2492
Script: chrome://conversations/content/js/handlebars-v3.0.0.js:1248

Thunderbird 38.2.0
Thunderbird Conversations 2.10

**Comment by supervirginia** [comment]
Same happens to me, with maybe 20 E-Mails, I always have to choose to stop the script in order to continue reading my emails. The line number changes everytime though.
![conversations_ss](https://cloud.githubusercontent.com/assets/16543028/12093893/d2aee81e-b305-11e5-8b7f-15668d2cd868.png)

**Comment by MLopez-Ibanez** [comment]
Still happens with TB 45.4.0 and Conversations  	2.11.4

The script/line numbers varies (I guess it reports the point at which TB stopped the script). I wished one could obtain a backtrace instead.

Script: chrome://conversations/content/js/jquery-1.6.4.min.js:2

This is what TB prints to the console from the moment I click on the problematic thread until the moment the "unresponsive script" dialog pops:

2016-10-31 15:41:09     Conversations.MonkeyPatch       DEBUG   Intercepted message load,  18  message(s) selected
2016-10-31 15:41:09     Conversations.MonkeyPatch       DEBUG   Hockey-hack
JavaScript strict warning: chrome://conversations/content/js/jquery-1.6.4.min.js, line 2: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: chrome://conversations/content/js/jquery-1.6.4.min.js, line 2: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: chrome://conversations/content/js/jquery-1.6.4.min.js, line 2: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: chrome://conversations/content/js/jquery-1.6.4.min.js, line 2: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: chrome://conversations/content/js/jquery-1.6.4.min.js, line 2: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: chrome://conversations/content/js/jquery-1.6.4.min.js, line 3: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: chrome://conversations/content/js/jquery-1.6.4.min.js, line 3: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: chrome://conversations/content/js/jquery-1.6.4.min.js, line 3: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: chrome://conversations/content/js/jquery-1.6.4.min.js, line 3: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: chrome://conversations/content/js/jquery-1.6.4.min.js, line 3: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: chrome://conversations/content/js/jquery-1.6.4.min.js, line 4: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: chrome://conversations/content/js/jquery-1.6.4.min.js, line 4: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: chrome://conversations/content/js/jquery-1.6.4.min.js, line 4: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: chrome://conversations/content/js/jquery-1.6.4.min.js, line 4: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: chrome://conversations/content/js/jquery-1.6.4.min.js, line 2: ReferenceError: reference to undefined property f.valHooks[this]
JavaScript warning: chrome://conversations/content/js/jquery.tokeninput.js, line 470: unreachable code after return statement
2016-10-31 15:41:10     Conversations.Stub.Completion   DEBUG   You don't have Contacts installed. Gloda will provide autocomplete.
2016-10-31 15:41:10     Conversations.SimpleStorage     DEBUG   Simple Storage loaded.
2016-10-31 15:41:10     Conversations.MonkeyPatch       DEBUG   First conversation
JavaScript strict warning: chrome://conversations/content/js/jquery-1.6.4.min.js, line 2: ReferenceError: reference to undefined property a[0]
JavaScript strict warning: chrome://conversations/content/js/jquery-1.6.4.min.js, line 2: ReferenceError: reference to undefined property f.cache[a[f.expando]]
JavaScript strict warning: resource://conversations/modules/conversation.js, line 86: ReferenceError: reference to undefined property this._toRun
2016-10-31 15:41:13     Conversations.Conversation      DEBUG   Outputting GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF 
2016-10-31 15:41:13     Conversations.Conversation      DEBUG   20 messages in the conversation now
JavaScript strict warning: resource://conversations/modules/contact.js, line 97: ReferenceError: reference to undefined property this._colorCache[email]
JavaScript strict warning: chrome://conversations/content/js/handlebars-v3.0.0.js, line 1932: ReferenceError: reference to undefined property options.srcName
JavaScript strict warning: chrome://conversations/content/js/handlebars-v3.0.0.js, line 2207: ReferenceError: reference to undefined property path.falsy
JavaScript strict warning: chrome://conversations/content/js/handlebars-v3.0.0.js, line 2779: ReferenceError: reference to undefined property this.options.srcName
JavaScript strict warning: chrome://conversations/content/js/handlebars-v3.0.0.js, line 599: ReferenceError: reference to undefined property options.helpers
JavaScript strict warning: chrome://conversations/content/js/handlebars-v3.0.0.js, line 593: ReferenceError: reference to undefined property container.partials
JavaScript strict warning: chrome://conversations/content/js/handlebars-v3.0.0.js, line 629: ReferenceError: reference to undefined property container.partials

Then the dialog refers to:
Script: chrome://conversations/content/js/handlebars-v3.0.0.js:2471

If I click continue, it shows the thread immediately.

**Comment by sebma** [comment]
Hi,
I have the same error on my Ubuntu with thunderbird 52.4.0 and conversations 2.13.3

![warning unresponsive script_011](https://user-images.githubusercontent.com/4569306/31515319-0c959216-af95-11e7-91d4-7d78b4ffbba0.png)

Can you have a look ?

**Comment by helen-fornazier** [comment]
Hi,

I have this same error on Debian unstable (near to Debian buster),  this happens all the time and is quite annoying.

Thunderbird Version: 60.8.0
Conversation version: 2.14.7

Is there any other info I can get to help with this?

![image](https://user-images.githubusercontent.com/11065451/63446100-f8d87680-c40f-11e9-9a10-e58262f5cbcf.png)

**Comment by Standard8** [comment]
The master we've just merged has a rewritten UI using React rather than jQuery/handlebars. Hopefully that has resolve the issues here and we won't see these performance issues again.

If they do reoccur, please file a new issue and provide the details.

**Comment by sebma** [comment]
@Standard8 It seems [2.15.x releases](https://addons.thunderbird.net/en-US/thunderbird/addon/54035/versions/) are build for Thunderbird 68. Can you please back-port all (2.15.x releases) or at least the last release for Thunderbird 60 ?

**Comment by Standard8** [comment]
> @Standard8 It seems [all 2.15.x releases](https://addons.thunderbird.net/en-US/thunderbird/addon/54035/versions/) are build for Thunderbird 68. Can you please back-port all (2.15.x releases) or at least the last release for Thunderbird 60.6 ?

Sorry, that is not possible. Too much has changed in between 60 and 68 to make this viable. Thunderbird 68 is already released, I suspect automatic updates will be released within a month or so (though that's a guess based on what I've seen on the Thunderbird planning list).

**Comment by sebma** [comment]
@Standard8 Yes, Thunderbird 68 was released almost 2 months ago but the problem [it's not even available to the Debian Testing](https://packages.debian.org/testing/thunderbird), let alone all other Debian based distributions :(.

Thanks anyway.

Cheers :)
