### ISSUE TITLE
Column widths reset in unified inbox

### ISSUE THREAD

**Issue by jeremyleib** [protz/thunderbird-conversations#1010]
Using Thunderbird 38.2.0 and Conversations 2.10 on Windows 10 (though this issue has been annoying me in several previous versions of Thunderbird, Conversations, and Windows). I adjust the column widths in the unified inbox. Next time I start Thunderbird, though, the columns are reset to the default widths. Note: the columns actually chosen are not affected. The columns I hid and displayed don't change when starting Thunderbird the next time. When I disable Conversations, the column widths 'stick' when I next restart Thunderbird. With it enabled, though, the widths reset.

Thanks for any help! I love this addon!
Jeremy

**Comment by protz** [comment]
This will be resolved along with #932

**Comment by protz** [comment]
Please try http://jonathan.xulforum.org/files/gcv-nightlies/201510172139-master.xpi and tell me if that fixes it (if it does, please close the issue).

Thanks!

**Comment by protz** [comment]
(the fix is removing the "between" column in favor of the upcoming "correspondents" column which is a Thunderbird-implemented column and shouldn't cause this bug)
