### ISSUE TITLE
When replying to a PGP-encrypted message using the reply box, the reply is not sent encrypted

### ISSUE THREAD

**Issue by frh** [protz/thunderbird-conversations#1011]
It seems that when I use the reply box to send a reply to a PGP-encrypted email, the email is not sent encrypted.

**Comment by msprotz** [comment]
Yeah it just picks your default composition preferences for that account.

There's another bug opened to handle better openpgp UI... can you close this one?

Thanks,

Jonathan

**Comment by protz** [comment]
#791

**Comment by frh** [comment]
@protz Thank you, #791 matches exactly the symptom I am experiencing (reply always sent unencrypted regardless of Enigmail composition preferences.
