### ISSUE TITLE
Issues with long email addresses in contact tooltip

### ISSUE THREAD

**Issue by keeperofdakeys** [protz/thunderbird-conversations#1012]
On the contact popup in a conversion, sometimes an especially long email address will push the copy button under the avatar. I would expect it to wrap onto the next line. I've also noticed some z-index issues on the contact dropdown. (A sample is attached). 
![contact](https://cloud.githubusercontent.com/assets/141626/10209669/149cafec-681d-11e5-8490-08094b728c48.png)
I'm using thunderbird 38 under linux.

Having a quick look at the source code, could this float: left be an issue? https://github.com/protz/thunderbird-conversations/blob/06c5896aa28bb7a2632c8e305128ebb16b42f85a/skin/conversation.css#L351-L359. I haven't had any time to setup a dev environment to test this though.

**Comment by protz** [comment]
Something to fix along with #967 ?

**Comment by elioqoshi** [comment]
Will keep that in mind!

**Comment by elioqoshi** [comment]
@can't we expand the width of the box depending on the maximum width of the elements in there (in this case the email address). Will add a mockup in a bit

**Comment by xi** [comment]
I think this has been fixed somewhere in #1097 or #1134.

**Comment by protz** [comment]
Thanks. Closing.
