### ISSUE TITLE
Wrong conversation is shown when switching quickly between threads

### ISSUE THREAD

**Issue by RalfJung** [protz/thunderbird-conversations#1013]
Sometimes, it happens that the conversation shown at the bottom of the main window does not match to message(s) selected at the top.

I can reproduce this by
- Clicking on some (collapsed) thread (A) with lots of messages, so that loading it takes some time
- While it is still loading, quickly clicking another message/thread (B)
- Now the first, large thread finishes loading and is shown at the bottom
- I have to click some other message (!= B), and then click B again, to make it actually show B

This frequently happens to me in normal daily usage.

**Comment by protz** [comment]
Ok, this one is a bug, but it'll most likely be fixed when I implement the speed optimizations I mentioned in #1014.

I think I've replied to all your issues. Apologies for the delay, things are a little bit busy on my end. Will you be at OOPSLA? We could chat about your issues and/or possible contributions (if you're interested, of course!) while I buy you a beer.

**Comment by RalfJung** [comment]
> I think I've replied to all your issues. Apologies for the delay, things are a little bit busy on my end.

Don't worry, compared to many other projects, we are definitely fast.

> Will you be at OOPSLA? We could chat about your issues and/or possible contributions (if you're interested, of course!) while I buy you a beer.

No, I will probably not be on another conference anymore this year - and I don't really file like taking another one of these long flights anyway ;-) .
Also, as far as I remember, I still owe you a beer :D

**Comment by Standard8** [comment]
I believe I've just fixed this in 3.1.2 which has just been released - specifically in a634d01. Although the performance still isn't brilliant for large threads, we'll cancel display of the previous one and display the correct one.
