### ISSUE TITLE
CSS customization

### ISSUE THREAD

**Issue by vojtechkral** [protz/thunderbird-conversations#1017]
Hi,
  it would be awesome if I could customize the converstaions CSS through the preferences screen. Such as add custom rules, etc.

I have no idea how hard this is to implement though...

Anyway, thanks for a great add-on!

**Comment by protz** [comment]
I think there's instructions on how to do that in the wiki. Like, 
there's sample CSS rules to hide the quick reply.
https://github.com/protz/thunderbird-conversations/wiki/Tips-and-tricks:-Disabling-the-%22Quick-Reply%22-feature
If that helps, please close this issue. Thanks!

Jonathan

**Comment by vojtechkral** [comment]
@protz Hm, interesting, but doesn't really help... I'm trying to increase font size, because I have an HDPI display. HTML messages seem to obey thunderbird font settings, but plain text message have 12px font size no matter what. I can't seem to be able to modify that even with stylish.

BTW. those stylish script examples are missing a URL block, as in

    @-moz-document url(chrome://conversations/content/stub.xhtml)

or similar

**Comment by vojtechkral** [comment]
Uhh, never mind.

Turns out it's Tunderbird configuration problem. Apparently the font settings need to be set for each font/language family separately. Completely unintuitive if you ask me. But anyway, this is not a Conversations issue. Sorry.

**Comment by Quantizen** [comment]
@vojtechkral Could you explain your last comment further? I also want to increase the font size of the plain text view.
