### ISSUE TITLE
Not able to change setup

### ISSUE THREAD

**Issue by mkielg11** [protz/thunderbird-conversations#1018]
After installation, I open the "Start the setup assistant" through the preferences in the add-on menu, however, when I uncheck e.g. the "Unified Inbox" option and press "Apply changes", nothing is changed and when opening the assistant again, I find the option re-checked. 

Very annoying, as especially as I find both the Unified and Global Inbox very annoying.

**Comment by protz** [comment]
I think the setup assistant is meant to be a one-time customization 
thing, not an accurate reflection of the state your Thunderbird is in 
(it writes changes, but does not allow you to customize the existing setup).

Use View > Folders to disable the unified view.

(Please close this if my answer helps. Thanks!)

Jonathan

**Comment by mkielg11** [comment]
I haven't been able to find your solution in the menus, but by disabling the add-on and then re-enabling it with the desired configuration will do the trick, I have found.
