### ISSUE TITLE
"Reply-To" is not shown

### ISSUE THREAD

**Issue by RalfJung** [protz/thunderbird-conversations#1019]
I have here a mail which has a `Reply-To` header. Conversations does not show that even when I enable "show details", unlike plain Thunderbird which does show this together with Cc, and so on.

**Comment by protz** [comment]
I'd integrate a pull request for that. I think it's just a minor change 
in the source code at 
https://github.com/protz/thunderbird-conversations/blob/master/modules/message.js#L1222

**Comment by RalfJung** [comment]
Hehe, I see what you are doing here ;-)

I'm putting it on my list, and hopefully can give it a try. But please, nobody hold their breath...
