### ISSUE TITLE
Blank PGP-encrypted messages in conversation view

### ISSUE THREAD

**Issue by Manko10** [protz/thunderbird-conversations#1020]
When I receive PGP-encrypted messages, I can read them without issues when I open them for the first time. But then when I select a different conversation and switch back to that conversation, all those messages are blank. Except for those that I wrote myself.

This is what it looks like:
![conversations-empty](https://cloud.githubusercontent.com/assets/911270/10563846/64ffdd3e-759b-11e5-865f-9d941a6795e9.png)

As you can see, the empty messages aren't even detected as being encrypted. In fact, when I turn on debugging and look into the log file, it says that it found three PGP messages, although there should be more (no errors are reported):

> 2015-10-18 13:13:13     Conversations.Modules.Enigmail  DEBUG   Found inline PGP
> 2015-10-18 13:13:13     Conversations.Modules.Enigmail  DEBUG   Found inline PGP
> 2015-10-18 13:13:13     Conversations.Modules.Enigmail  DEBUG   Found inline PGP

When I click "view using the classic reader", the message pane is still empty. Only when I right-click and say "Open Message in New Window" the contents are shown.

The only differences that I could find in the messages are that the ones that are shown correctly are all inline PGP whereas the others are multi-part MIME mails.
However, I tried sending myself multi-part messages, too and couldn't reproduce. So I examined the message sources and they look slightly different.

Enigmail creates multipart messages like this:

```
MIME-Version: 1.0
Content-Type: multipart/encrypted;
 protocol="application/pgp-encrypted";
 boundary="RIuCQL75xEBjjxeqDJ6WwlhdHq8fH4N4c"

This is an OpenPGP/MIME encrypted message (RFC 4880 and 3156)
--RIuCQL75xEBjjxeqDJ6WwlhdHq8fH4N4c
Content-Type: application/pgp-encrypted
Content-Description: PGP/MIME version identification

Version: 1

--RIuCQL75xEBjjxeqDJ6WwlhdHq8fH4N4c
Content-Type: application/octet-stream; name="encrypted.asc"
Content-Description: OpenPGP encrypted message
Content-Disposition: inline; filename="encrypted.asc"

-----BEGIN PGP MESSAGE-----
Version: GnuPG v2

...
-----END PGP MESSAGE-----

--RIuCQL75xEBjjxeqDJ6WwlhdHq8fH4N4c--
```

These are shown correctly.
The other messages I received which are only shown the first time I open them look like this:

```
MIME-Version: 1.0
Content-Type: multipart/encrypted;
 boundary="----------=_1445147238-4871-42";
 protocol="application/pgp-encrypted"

This is a multi-part message in MIME format...

------------=_1445147238-4871-42
Content-Type: application/pgp-encrypted
Content-Disposition: inline
Content-Transfer-Encoding: 7bit

Version: 1
------------=_1445147238-4871-42
Content-Type: application/octet-stream
Content-Disposition: inline
Content-Transfer-Encoding: 7bit

-----BEGIN PGP MESSAGE-----
Version: GnuPG v2.0.14 (GNU/Linux)

...
-----END PGP MESSAGE-----

------------=_1445147238-4871-42--
```

Using Thunderbird 38.3.0 on Linux x68_x64 with Conversations 2.10.

I searched the bug tracker and thought this might be related to issue #978, but I'm still using Enigmail 1.8.2. not 1.9.

It might be the same as issue #901, but since that's very old and there hasn't been any helpful activity, I just created a new issue.

**Comment by Manko10** [comment]
Looks like I found a workaround. The "I love attachments" option in the settings forces those "empty" messages to be rendered correctly.

**Comment by protz** [comment]
Can you try the most recent version from http://jonathan.xulforum.org/files/gcv-nightlies/ along with Thunderbird "Daily" and make sure that it fixes your issue?

Thanks!

**Comment by SimJoSt** [comment]
I have a similar problem. S/MIME signed mails sometimes appear to be empty.
I tried the newest version and have not run into this error again. I'll keep you up to date.
