### ISSUE TITLE
Cannot remove blank line before quote at start of message

### ISSUE THREAD

**Issue by azrdev** [protz/thunderbird-conversations#1023]
Thunderbird 38.3, Conversations 2.10

Reply to a message. The original message is quoted, preceded by a line "$sender wrote on $date:". If I delete that line and at least one line at the start of the quote, there is an empty non-quoted line at the top of the message, before the quote. I cannot get rid of that line without un-quoting the (now) first line of the quote.

**Comment by protz** [comment]
I would say that's an error in the core Gecko contentEditable element. Try filing at https://bugzilla.mozilla.org

Thanks,

Jonathan

**Comment by azrdev** [comment]
@protz I'm not familiar with your or TBs code, is this <https://bugzilla.mozilla.org/show_bug.cgi?id=779067> or <https://bugzilla.mozilla.org/show_bug.cgi?id=685445> ?
