### ISSUE TITLE
Severe font smoothng issues on non English windows

### ISSUE THREAD

**Issue by Wintereise** [protz/thunderbird-conversations#1024]
Hi,

There appears to be severe font smoothing problems on UI elements generated by this plugin. However, actual mail content is styled fine.

Here's a screenshot showing what I'm talking about -- http://voile.tomoyo.eu/pool/BF

The system in question is Windows, and is running Thunderbird 38.3.0. Its locale is set to Japanese (for both UTF and non UTF system components)

I tried searching with is:open and is:issue + font, but got no hits. Any assistance will be highly appreciated.

Thank you!

**Comment by protz** [comment]
Hi there,

Thanks for the bug report. The Conversations addon doesn't control the rendering (this is a core Thunderbird component) so I suggest you try to file a bug at https://bugzilla.mozilla.org

Thanks,

Jonathan
