### ISSUE TITLE
strange watch tag

### ISSUE THREAD

**Issue by Goddard** [protz/thunderbird-conversations#1026]
I am seeing a "watch" tag in Thunderbird all of a sudden when using this add-on.  Why is this happening?

**Comment by bramblevine** [comment]
It might be similar to something I saw when I upgraded recently. I was seeing an 'Important' tag being set on incoming email with high priority. In my tags list 'Important' is the first one and I'm wondering if there is a naive implementation behind the auto tag feature.

The main problem I had with it was the tag could not be removed. To disable the feature go into the preferences, Thunderbird Extras (last tab) and then uncheck "Automatically tag high priority mail as Important".

**Comment by protz** [comment]
I don't think it's related to this addon.

**Comment by Goddard** [comment]
it wont let me delete the tags

**Comment by Goddard** [comment]
also dont have "Thunderbird Extras"

**Comment by protz** [comment]
I think you're just seeing the standard thunderbird feature called tags

http://kb.mozillazine.org/Tags

**Comment by Goddard** [comment]
I understand that, but it just appeared.  I haven't done anything and I use this awesome add-on all the time.

**Comment by protz** [comment]
Maybe you hit the 3 key on your keyboard

**Comment by Goddard** [comment]
The 3 key displays a "personal" tag, but a "Watch" tag is always present on all emails.

**Comment by protz** [comment]
Screenshot?
