### ISSUE TITLE
Delete conversation only deletes inbox messages

### ISSUE THREAD

**Issue by Garoe** [protz/thunderbird-conversations#1027]
When I select a conversation and I press Delete or the "Delete this conversation" button, the messages in the sent folder are not deleted.

**Comment by protz** [comment]
I think there's an option for that in the addon's options.... ?

~ jonathan

**Comment by Garoe** [comment]
I see, that does indeed work, thanks for your help. Have you consider enabling the option by default?

**Comment by protz** [comment]
Yes, and then I had big drama because too many messages were deleted...

**Comment by torkelsson** [comment]
Please don't enable it by default. Just because you delete the incoming
conversation, it doesn't mean that you want to delete the mails you sent.

2015-11-11 16:26 GMT+01:00 Garoe Dorta <notifications@github.com>:

**Comment by Garoe** [comment]
As a last suggestion, would it be to difficult to add to a button to enable/disable the option in the start up assistant? I had missed it because I thought it would be there
