### ISSUE TITLE
feature request: move from inbox to the thread folder 

### ISSUE THREAD

**Issue by leosteinfeld** [protz/thunderbird-conversations#1041]
Hi,

First of all thanks for your very useful ad-on.

I organize my e-mails in folders, so that, besides the basic conversation view, the feature that I found really nice is been able to see the folder where the rest of the mails of the same thread are located. It would be very very useful to quick move from the inbox to the folder where the rest of the mails resides.

Thanks again.

**Comment by MLopez-Ibanez** [comment]
This works for me in the latest version. If an email within a conversion is on a different folder, it is shown at top of that particular email, I can click to jump to the other folder.

If you mean, move the email from the inbox to the other folder, you may wish to check the "Nostalgy" add-on. It does something similar and much more: https://github.com/alainfrisch/nostalgy

**Comment by Standard8** [comment]
As per previous comment this has worked for a while.
