### ISSUE TITLE
All Conversations Expanded

### ISSUE THREAD

**Issue by lprattacular** [protz/thunderbird-conversations#1042]
One day I opened Thunderbird and all of my inbox conversations were expanded. I collapsed quite a few of them, but when I went to another folder and clicked back into my inbox, they were all expanded again. I've restarted Thunderbird and my computer several times since then. I'm using Thunderbird 38.4.0. 

Help?

**Comment by protz** [comment]
You have View > Threads > Collapse All Threads (in the menus) or the `\\` keyboard shortcut.

That's a Thunderbird feature, I have no control over that.
