### ISSUE TITLE
1. why is the update of the "Thunderbird Conversations 10.1-let-fixed" is impossible.／2. "thread view" is, to combine the other different Message.

### ISSUE THREAD

**Issue by hideki-nomura** [protz/thunderbird-conversations#1043]
I am using the "Thunderbird 38.4.0".
I am one's favorite this add-on from one year ago.
However, why is the update of the "Thunderbird Conversations 2.10.1-let-fixed" is impossible.

Moreover, recently, to be in trouble, "thread view" is, to combine the other different Message.
This symptom occurs at Reply to the Message.
Minute that arrived immediately after the Message is, It binds to reply, it can not be separated.
If not the Reply is it looks fine.

In order to not be normal Reply, we disable this addon.
After disable, it is normal.

Please give me your support.
Or more

**Comment by protz** [comment]
Can you be more specific about the update being impossible?

For the threading issue, I suspect it's the first bug mentioned at 
https://github.com/protz/thunderbird-conversations/wiki/What-is-threading

~ jonathan

**Comment by hideki-nomura** [comment]
about the update being impossible

1. In addon-Manager, when run the update download is interrupted. but also tried, Restart, such as Restart the PC, the same symptoms are repeated.
Update of other add-ons, can without any problem.

2. as the next best thing, I uninstalled this addon, Then the latest I tried to install, but display compatible failure out, it was not feasible.

3. Next time, I installed the old version. Although successful, and execute the update, it could not.

4. for this, now, is uninstall state.
Or more

**Comment by michielbrinkers** [comment]
I'm having the same issue of different messages being combined, and I'm pretty sure it's not the 'reply' issue because it's happening across the board and I'm seeing 4 year old mail threads being included. I also get the root of a conversation getting a message tacked on at the front, and then when I get into that thread, a whole different conversation being added at the front. This has been happening since a week or more.

**Comment by michielbrinkers** [comment]
I tried 38.1, 38.3 and 42.0b2, and non of them made a difference.

**Comment by chester03** [comment]
I too am having same issue with updating the add-on..... message comes back "There was an error downloading T/Bird Conversations - Try Again". No detail about what sort of error is involved - restarting T/Bird and PC makes no difference.

**Comment by clst** [comment]
I am having the same issue (error, try again in Add-ons Manager). There is nothing in the Error Console. A https connection is made: addons.cdn.mozilla.net, It responds with a few bytes then the error is displayed.

**Comment by NicoHaase** [comment]
I have the same issue, the following message is shown in the error console:

1449855294887	addons.xpi	WARN	Download of https://addons.cdn.mozilla.net/user-media/addons/54035/thunderbird_conversations-2.10-tb.xpi?filehash=sha256%3Ac7e49f6cbf7b5e4b38c8700df957417b58c4bd42415ce3f70c9ba888a86757e7 failed: Downloaded file hash (800da5cf0f845b5fa8f9d49569c948904b16e30cf6df9cfe82078ed9058392cd) did not match provided hash (c7e49f6cbf7b5e4b38c8700df957417b58c4bd42415ce3f70c9ba888a86757e7)

**Comment by protz** [comment]
I've reported it on bugzilla.mozilla.org; no one seems to be doing 
anything about it.

addons.mozilla.org "fixed" the addon for me, resulting in everything 
being broken, and everyone having that error message.

**Comment by chester03** [comment]
Update V2.10.2 today has fixed the problem for me - thanks!

**Comment by protz** [comment]
Perfect. It's a dummy version which is, really, the same as 2.10; I just pushed it to fix the update problem. Thanks for the feedback!
