### ISSUE TITLE
Enigmail preference "Override with" inactive when this plugin is enabled

### ISSUE THREAD

**Issue by Rudd-O** [protz/thunderbird-conversations#1047]
When this addon is enabled, the Override with preference in Enigmail does not work for some reason, and ends up being reverted (in practice, not in the prefs) to /usr/bin/gpg2.

Please fix.  To reproduce:
- disable conversations
- enable enigmail
- set override in enigmail to some nonsense command that will cause errors (/bin/false)
- RESTART thunderbird
- check that it fails when composing a mail
- enable conversations
- RESTART thunderbird
- compose, and check that the failures are gone

Confirm with strace -ff -eexecve -s2048.

**Comment by protz** [comment]
I'm inclined to believe you even though I'm not an Enigmail user myself. Can you try a "Daily" build of Thunderbird and the latest build of Conversations at http://jonathan.xulforum.org/files/gcv-nightlies/ to see if the problem persists?

Thanks,

Jonathan

**Comment by Rudd-O** [comment]
I'll try, but no promises, these days I'm hella busy.

**Comment by Standard8** [comment]
Is this still an issue? I'm guessing a lot has changed in the last few years, so I'll close this out, if it is a problem, feel free to re-open or file a new issue.
