### ISSUE TITLE
Full view of clicked links.

### ISSUE THREAD

**Issue by slowrobert** [protz/thunderbird-conversations#1048]
Currently when clicking on a link to view it in thunderbird, the view page which opens is cut in 1/2 with the original message shown on the bottom and the link page on top.

Without the extension the entire window shows the link page, which is what I would prefer instead of the 50% view. 

I don't see any 'handles' to stretch one or the other window, nor do I see how to make the bottom view which shows the currently selected email, disappear all-together.

**Comment by slowrobert** [comment]
Nevermind; found View:Conversation....

**Comment by slowrobert** [comment]
View:Conversation can be turned off,....But then, that sort of defeats the extension...

It would be nice to be able to resize the viewing panels, especially when popping open linked pages.

**Comment by protz** [comment]
Can you post a screenshot of your issue?

**Comment by slowrobert** [comment]
2 screen shots; one with conversation view on, the other with it off.
![screen shot cut in half](https://cloud.githubusercontent.com/assets/10386765/12010029/40dcb000-ac49-11e5-8ac3-7f43843cfcc6.png)
![conversation view off](https://cloud.githubusercontent.com/assets/10386765/12010030/44220210-ac49-11e5-8950-ea90782a41b0.png)

**Comment by protz** [comment]
I assume you're using another addon to get a mini-browser inside of 
Thunderbird?

**Comment by slowrobert** [comment]
Yes, I am using Thunderbrowse 3.82.

It seems to me that the conversation view should only be in the main/first tab and that any other tabs opened to view email pages should not have the conversation view applied.  

I guess I had forgotten that the browser functionality was not default for Thunderbird, but it is convenient.

**Comment by protz** [comment]
I'm closing this on the basis that I cannot make Conversations compatible with every single extension out there. If the Thunderbrowse author wants to submit a patch to make Conversations compatible, then I'd happily take it, otherwise, we'll just leave it "as is".

Thanks,

Jonathan
