### ISSUE TITLE
Multiple conversations "merged to one"

### ISSUE THREAD

**Issue by oyvindmikkelsen** [protz/thunderbird-conversations#1049]
Hi  :-)

I'm having an issue with six conversations that shows up as one. Do you know what's causing this? Is there anything I can do to fix it? 

![screen shot 2016-01-08 at 12 58 33](https://cloud.githubusercontent.com/assets/16609384/12197686/64d8f2d8-b609-11e5-82e3-0a260f2d4bd0.png)

**Comment by protz** [comment]
Can you read https://github.com/protz/thunderbird-conversations/wiki/What-is-threading and investigate?

Thanks,

Jonathan

**Comment by aleksandrs-ledovskis** [comment]
There are no commits related to this bug, so one can assume that it has been closed as stale? 

Very unfortunate, as I have experienced this same problem where completely different emails would be displayed as part of single conversation.

**Comment by protz** [comment]
It's just that it's an underlying issue in Thunderbird over which I have no control, unfortunately.
