### ISSUE TITLE
Too many mail in conversation crash

### ISSUE THREAD

**Issue by londumas** [protz/thunderbird-conversations#1050]
When there are too many emails / too big joined files in a conversation Thunderbird crashes.

Ubuntu 15.10
Thunderbird  38.5.1
Thunderbird Conversations 2.10.2

Thanks for the work.

Crash message:

<me>@<me>:~$ thunderbird 

(process:5725): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
[calBackendLoader] Using libical backend at /home/<me>/.thunderbird/8exxbtzc.default/extensions/{e2fda1a4-762b-4020-b5ad-a41df1933103}/components/libical-manifest
Vector smash protection is enabled.

(thunderbird:5725): Gtk-CRITICAL **: IA__gtk_clipboard_set_with_data: assertion 'targets != NULL' failed
Processus arrêté
<me>@<me>:~$ [NPAPI 5798] ###!!! ABORT: Aborting on channel error.: file /build/thunderbird-046_07/thunderbird-38.5.1+build2/mozilla/ipc/glue/MessageChannel.cpp, line 1584
[NPAPI 5798] ###!!! ABORT: Aborting on channel error.: file /build/thunderbird-046_07/thunderbird-38.5.1+build2/mozilla/ipc/glue/MessageChannel.cpp, line 1584

**Comment by protz** [comment]
Sounds like a bug in Gecko. Extensions should not be allowed to crash 
Thunderbird.

Can you file a bug at http://bugzilla.mozilla.org and close this one?

Thanks,

Jonathan

**Comment by londumas** [comment]
Hi @protz ,

Not sure to be able to fill the bug report on 'Gecko', because I don't know what it does.
Should I put the same bug report ?

Thanks,
Hélion.

**Comment by protz** [comment]
Yes, just put it in the Core component and in the General subcategory 
with the same information. Please also put the value ":protz" in the CC 
field.

Thanks,

Jonathan

**Comment by londumas** [comment]
How can I know what version of "core" I have ?

**Comment by londumas** [comment]
I have put:
Component: "General"

**Comment by protz** [comment]
Yes, that's very good. The version you have is the version of 
Thunderbird you're running. Thanks again!

**Comment by londumas** [comment]
I just finished the bug report, tell me if you received it and if it is ok, then I close the git report.

Thanks,
Hélion.

**Comment by protz** [comment]
Yes, it's good. Thanks.

**Comment by londumas** [comment]
Issue reported on https://bugzilla.mozilla.org/show_bug.cgi?id=1239623
