### ISSUE TITLE
Middle-clicking folder opens conversation, prevents all folder navigation

### ISSUE THREAD

**Issue by jimbo1qaz** [protz/thunderbird-conversations#1052]
Thunderbird 38.5.1, release Conversations, OS = Windows 7 x64.

When I middle-click a folder in the left pane, it opens Conversation Reader instead of a folder tab. Afterwards, left-clicking folders does nothing, breaking folder navigation.

**Comment by protz** [comment]
Good catch, although I haven't had the "breaking folder navigation" symptom.
