### ISSUE TITLE
It doesn't work with Thunderbird 44 Beta 1

### ISSUE THREAD

**Issue by Dimas-sc** [protz/thunderbird-conversations#1053]
With the new Beta and this addon enabled, Thunderbird doesn't load the mails.

**Comment by protz** [comment]
I think you need the newer version from 
http://jonathan.xulforum.org/files/gcv-nightlies/ ; please try it out 
and close the issue if it fixes the problem for you.

Thanks,

Jonathan

**Comment by Dimas-sc** [comment]
Yes, it works, thx
