### ISSUE TITLE
settings don't work

### ISSUE THREAD

**Issue by pnikas** [protz/thunderbird-conversations#1054]
The conversations settings buttons don't work on mac.Tried different versions also but still when pressing the save button nothing happens

**Comment by protz** [comment]
I'm not sure what you're talking about. Can you post a screenshot?

**Comment by luizfss** [comment]
I believe to be having the same problem.

Change any settings, click on apply changes and nothing happens. Turn Conversations settings are all checked options.

Not gathering the messages sent.

I'm using the latest version of Thunderbird (38.5.1) and the 2.10.2 version of Conversations.

**Comment by protz** [comment]
Use the latest version at https://jonathan.protzenko.fr/thunderbird-conversations/

**Comment by luizfss** [comment]
Not worked! :(

2016-03-01 13:51 GMT-03:00 Jonathan Protzenko <notifications@github.com>:

**Comment by protz** [comment]
What is your thunderbird version and your conversations version?

**Comment by protz** [comment]
Also: anything in Tools > Error Console when that happens?
