### ISSUE TITLE
No message body after update to TB 44 B1

### ISSUE THREAD

**Issue by antiphasis** [protz/thunderbird-conversations#1055]
After updating TB to 44B1 (automatically announced and installed), no message text is shown, neither single message nor threaded messages. 
Simply deactivating the addon - all message bodies are shown.

**Comment by protz** [comment]
Please try the latest version at 
http://jonathan.xulforum.org/files/gcv-nightlies/ and close this issue 
if that fixes it. Thanks!

**Comment by antiphasis** [comment]
Done, it's working again. Thanks!
