### ISSUE TITLE
Drag & Drop of attachments to Finder (Mac OS X) does not work

### ISSUE THREAD

**Issue by philpav** [protz/thunderbird-conversations#1057]
I am using Thunderbird 38.5.1 and the addon version 2.10.2 on Mac OS X El Capitan. 
I am not able to drag & drop attachments from a mail to a Finder window. I have to manually save the attachments. 

Is this an issue or did I maybe oversee a setting?

**Comment by protz** [comment]
I think this is an underlying Thunderbird issue; does 
https://bugzilla.mozilla.org/show_bug.cgi?id=377621 match your description?

Please close this issue if that solves the problem. Thanks!

Jonathan
