### ISSUE TITLE
Thunderbird stops updating the message preview pane when navigating a mailbox

### ISSUE THREAD

**Issue by callahad** [protz/thunderbird-conversations#1062]
I haven't pinned down specific STR yet, but I've been able to trigger the following error a few times:

> Timestamp: 2/25/16, 02:05:00
> Error: TypeError: messages is null
> Source File: [chrome://conversations/content/stub.xhtml](https://github.com/protz/thunderbird-conversations/blob/4181ab0b119125919fab46cd5713674f9eb29de5/content/stub.xhtml)
> Line: [717](https://github.com/protz/thunderbird-conversations/blob/4181ab0b119125919fab46cd5713674f9eb29de5/content/stub.xhtml#L717)

Once triggered, clicking a new message in the mailbox does not change the message displayed in the preview pane. Switching mailboxes fixes it.

This is using master as of 2016-02-24 with SHA 4181ab0b119125919fab46cd5713674f9eb29de5 on Earlybird (46.0a2, 2016-02-23).

**Comment by Dexterp37** [comment]
Mh, interesting. I'll try to have a look over the weekend, thanks for reporting! If you happen to figure out the STR, that would be great :-D

**Comment by protz** [comment]
The workaround is to select several threads at the same time then click 
back on the original thread.

~ jonathan

**Comment by Dexterp37** [comment]
Sorry, I can't seem to reproduce :(

**Comment by protz** [comment]
Hmm... this is weird -- it only happened occasionally previously, but now the frequency of this issue seems to be higher. Will most likely require some deeper investigation

**Comment by protz** [comment]
@Dexterp37 yeah it is indeed happening more frequently than before. Probably worth trying to fix this if possible...

One way to debug this would be to turn messages into a getter / setter and print a stack trace when setting it to the empty array.

I won't have time to do a deep-dive into this until next week-end, so if you have some free time, feel free to take a stab at it and collect a few stack traces with your daily usage...

**Comment by Dexterp37** [comment]
I won't have a lot of time until the next week-end as well unfortunately :( I'll be collecting the stacks with the my daily usage though.

> 2016-03-01 19:25:29     Conversations.Conversation      DEBUG   Recycling conversation! We are eco-responsible. 0 new messages
> 2016-03-01 19:25:29     Conversations.Conversation      ERROR   Error: set messages() sets null
> 2016-03-01 19:25:29     Conversations   DEBUG
> Conversation.prototype.messages@resource://conversations/modules/conversation.js:397:17
> _Conversation_outputMessages@resource://conversations/modules/conversation.js:965:9
> _Conversation_getReady/<@resource://conversations/modules/conversation.js:660:7
> _Conversation_signal@resource://conversations/modules/conversation.js:107:7
> _Conversation_onQueryCompleted_bug547088@resource://conversations/modules/conversation.js:646:9
> setTimeout handler*_Conversation_onQueryCompleted@resource://conversations/modules/conversation.js:582:5
> gloda_coll_onQueryCompleted@resource:///modules/gloda/collection.js:631:7
> QueryFromQueryResolver.onQueryCompleted@resource:///modules/gloda/datastore.js:147:7
> gloda_ds_qfq_handleCompletion@resource:///modules/gloda/datastore.js:385:11
> 
> JavaScript error: chrome://messenger/content/mailWidgets.xml, line 1096: TypeError: contentElement is null
> 2016-03-01 19:25:29     Conversations.Message   DEBUG   A message is selected: imap-message://aplacitelli%40mozilla.com@imap.gmail.com/INBOX#13432
> 2016-03-01 19:25:29     Conversations.Conversation      ERROR   Error: get messages() returns null
> 2016-03-01 19:25:29     Conversations   DEBUG
> Conversation.prototype.messages@resource://conversations/modules/conversation.js:388:17
> MonkeyPatch.prototype.apply/_summarizeThread_patched/</<@resource://conversations/modules/monkeypatch.js:450:1
> _Conversation_outputInto/this._onComplete@resource://conversations/modules/conversation.js:1151:30
> _Conversation_expandAndScroll/<@resource://conversations/modules/conversation.js:1109:7
> _Conversation_signal@resource://conversations/modules/conversation.js:107:7
> _Message_signal@resource://conversations/modules/message.js:1336:5
> f_temp1@resource://conversations/modules/message.js:1534:15
> EventListener.handleEvent*f_temp2@resource://conversations/modules/message.js:1451:9
> EventListener.handleEvent*Message.prototype.streamMessage@resource://conversations/modules/message.js:1421:5
> Message.prototype.expand/<@resource://conversations/modules/message.js:1347:11
> _Message_buildAttachmentViewIfNeeded@resource://conversations/modules/message.js:1148:7
> Message.prototype.expand@resource://conversations/modules/message.js:1344:9
> _Conversation_expandAndScroll/<@resource://conversations/modules/conversation.js:1130:13
> _Conversation_expandAndScroll@resource://conversations/modules/conversation.js:1122:5
> _Conversation_appendMessages@resource://conversations/modules/conversation.js:819:7
> _Conversation_outputMessages@resource://conversations/modules/conversation.js:963:9
> _Conversation_getReady/<@resource://conversations/modules/conversation.js:660:7
> _Conversation_signal@resource://conversations/modules/conversation.js:107:7
> _Conversation_onQueryCompleted_bug547088@resource://conversations/modules/conversation.js:646:9
> setTimeout handler*_Conversation_onQueryCompleted@resource://conversations/modules/conversation.js:582:5
> gloda_coll_onQueryCompleted@resource:///modules/gloda/collection.js:631:7
> QueryFromQueryResolver.onQueryCompleted@resource:///modules/gloda/datastore.js:147:7
> gloda_ds_qfq_handleCompletion@resource:///modules/gloda/datastore.js:385:11
> 
> 2016-03-01 19:25:29     Conversations.Message   ERROR   TypeError: aConversation.messages is null
> 2016-03-01 19:25:29     Conversations   DEBUG
> MonkeyPatch.prototype.apply/_summarizeThread_patched/</<@resource://conversations/modules/monkeypatch.js:450:1
> _Conversation_outputInto/this._onComplete@resource://conversations/modules/conversation.js:1151:30
> _Conversation_expandAndScroll/<@resource://conversations/modules/conversation.js:1109:7
> _Conversation_signal@resource://conversations/modules/conversation.js:107:7
> _Message_signal@resource://conversations/modules/message.js:1336:5
> f_temp1@resource://conversations/modules/message.js:1534:15
> EventListener.handleEvent*f_temp2@resource://conversations/modules/message.js:1451:9
> EventListener.handleEvent*Message.prototype.streamMessage@resource://conversations/modules/message.js:1421:5
> Message.prototype.expand/<@resource://conversations/modules/message.js:1347:11
> _Message_buildAttachmentViewIfNeeded@resource://conversations/modules/message.js:1148:7
> Message.prototype.expand@resource://conversations/modules/message.js:1344:9
> _Conversation_expandAndScroll/<@resource://conversations/modules/conversation.js:1130:13
> _Conversation_expandAndScroll@resource://conversations/modules/conversation.js:1122:5
> _Conversation_appendMessages@resource://conversations/modules/conversation.js:819:7
> _Conversation_outputMessages@resource://conversations/modules/conversation.js:963:9
> _Conversation_getReady/<@resource://conversations/modules/conversation.js:660:7
> _Conversation_signal@resource://conversations/modules/conversation.js:107:7
> _Conversation_onQueryCompleted_bug547088@resource://conversations/modules/conversation.js:646:9
> setTimeout handler*_Conversation_onQueryCompleted@resource://conversations/modules/conversation.js:582:5
> gloda_coll_onQueryCompleted@resource:///modules/gloda/collection.js:631:7
> QueryFromQueryResolver.onQueryCompleted@resource:///modules/gloda/datastore.js:147:7
> gloda_ds_qfq_handleCompletion@resource:///modules/gloda/datastore.js:385:11
> 
> 2016-03-01 19:25:29     Conversations.Message   WARN    Running signal once more to make sure we move on with our life... (warning, this WILL cause bugs)

This looks like a reasonable starting point.

**Comment by protz** [comment]
Hmm the line number don't match my local copy of the file. How much should I subtract?

**Comment by Dexterp37** [comment]
19 lines in conversation.js. The culprit seems to be the only |this.messages = null| in conversation.js, setting the messages to null.

**Comment by Orhideous** [comment]
I'm also faced with this problem.
Thunderbird 45.0, Thunderbird-conversations 2.12pre from master (b989e21b7b0e8340286d8bde81e9a3d3cb508798)

**Comment by lkraav** [comment]
Same problem here.

**Comment by protz** [comment]
I'd love to hear about your Thunderbird & Conversations version, and I'd 
love to hear whether there's anything of interest in Tools > Error 
Console :)

**Comment by hwti** [comment]
I think it started with Thunderbird 45.0, but I can't try Conversations older than 2.11 (nothing is displayed in the message pane if I try 2.10.2).

It seems to happen at least when receiving a new message in the currently displayed conversation : the new message is shown, then the error traces happen.

I see these traces :
> Erreur : TypeError: this.messages is null
> Fichier source : resource://conversations/modules/conversation.js
> Ligne : 1137

> Erreur : TypeError: messages is null
> Fichier source : chrome://conversations/content/stub.xhtml
> Ligne : 717

I sometimes see other traces before : 
> gloda.collection	ERROR	caught exception from listener in onItemsModified: resource://conversations/modules/conversation.js:1061: TypeError: this._domNode.ownerDocument.getElementById(...) is null

> gloda.collection	ERROR	caught exception from listener in onItemsModified: resource://conversations/modules/conversation.js:511: TypeError: this.messages is null

**Comment by Dexterp37** [comment]
I'm running a custom compiled extension which simply sets |this.messages = []| instead of |this.messages = null| in conversation.js. Everything seems to work much better, but I'm not entirely sure that's ok or if it has any other consequence. @protz is this an feasible solution?

I'm not entirely sure why this is being set to null in the first place, but I don't know much more about Thunderbird internals  :(

**Comment by protz** [comment]
Yeah I tried to review that code and I also failed to understand why it 
was set to null instead of [].

If that works for you I'm up for a pull request.

~ jonathan

**Comment by Standard8** [comment]
I've not seen this for a while, so I'm going to assume that this is gone. Please re-open or file a new issue if it is still present in the latest versions.
