### ISSUE TITLE
enigmail OpenPGP/MIME encrypted messages are not displayed

### ISSUE THREAD

**Issue by Faldrian** [protz/thunderbird-conversations#1065]
When used in combination with enigmail, inline PGP works okay (you get the prompt and the message is displayed inside the conversations view after decryption).

When there is a message of type multipart/encrypted with "This is an OpenPGP/MIME encrypted message (RFC 4880 and 3156)" content, conversations shows an empty box for that mail and no prompt is shown.

It would be nice to have the same behaviour as with inline PGP messages.

**Comment by lcseguin** [comment]
Same issue here. Some older sent emails are displayed as encrypted.

**Comment by Darigaaz** [comment]
+1
Even just signed messages does not display.

**Comment by lcseguin** [comment]
@Darigaaz Your update did not work for me :-(

**Comment by protz** [comment]
https://addons.mozilla.org/en-US/thunderbird/addon/gmail-conversation-view/versions/ has a pointer to 2.11.2 which fixes this. Sorry about the issue! Please shout out if this build doesn't fix your issue.
