### ISSUE TITLE
enigmail signed messages say they have been decrypted

### ISSUE THREAD

**Issue by hardbyte** [protz/thunderbird-conversations#1066]
There is a misleading "decrypted" icon with the hover text "This message has been decrypted before display" for messages that are signed but not encrypted.

Suggest this should be something like "verified" and "This message has a verified signature from X".

**Comment by protz** [comment]
ping @shirosaki

**Comment by shirosaki** [comment]
It seems that `isEncrypted` attribute is true against only signed PGP/MIME message and "decrypted" label is added.
https://github.com/protz/thunderbird-conversations/blob/master/modules/message.js#L579-L580

`isEncrypted` attribute comes from Thunderbird side code.
https://github.com/protz/thunderbird-conversations/blob/master/modules/message.js#L1757
https://github.com/protz/thunderbird-conversations/blob/master/modules/message.js#L1844

Original message header would be needed to check only singed.

**Comment by SimJoSt** [comment]
I have the same problem with a S/MIME signed email.

**Comment by Standard8** [comment]
I think this may be fixed in the latest version of Conversations. If it isn't please feel free to re-open this or file a new issue and we can take a look.
