### ISSUE TITLE
Displaying messages hangs since TB 45

### ISSUE THREAD

**Issue by scheinercc** [protz/thunderbird-conversations#1070]
Since I have updated to TB 45 (Mac) I have problems getting the messages displayed at all when switching between them. It happens not all the time, but once it starts no other messages in the current folder besides the one already loaded into the view gets displayed. I first have to switch to any other folder, switch back to the original one to then be able load other messages. After a couple of messages it happens again. It seems rather random but somewhat related to leaving conversations with more than one message.
I couldn't see anything that seems related in the Error Console.
Not sure if it this issue is associated with #1014, but as it is not just taking long, but not switching messages at all I opened this new bug.

When I installed TB45 I was using TC 2.11 and updated now to the latest nightly 2.11pre, last updated 29/03/ with no change.

**Comment by Dexterp37** [comment]
This seems related to #1062. The fix  (#1069) was merged yesterday and the updated version of the addon will be out soon.

**Comment by scheinercc** [comment]
Thanks. Will keep an eye out for the update and update this issue.

**Comment by Dexterp37** [comment]
Cool! Please let us know if that fixes the issue :-)

**Comment by protz** [comment]
New version is live on amo. Thanks for your patience everyone.

~ jonathan

**Comment by scheinercc** [comment]
Updated, switched TC on again and it works fine. I had a minor hang switching within a conversation, but I think I had them before as well sometimes. Thanks for the quick fix!

**Comment by sleeksorrow** [comment]
Sadly I have this issue also with version 2.11.1 on TB45. So maybe it's not fixed in all circumstances.

**Comment by protz** [comment]
Restart Thunderbird?

**Comment by Dexterp37** [comment]
@protz, do you think it would make any sense to instrument the getters/setters for |messages| (touched by #1069) to chase any edge case that pops out?

**Comment by protz** [comment]
Hmm, maybe...

I keep thinking that I need to rewrite the logic and make it much 
simpler... but this would require about two days off for me, which I 
don't really have...

**Comment by protz** [comment]
But yeah, at least I'd be up for instrumenting.

**Comment by joshwand** [comment]
FWIW I had to go to "Get Add-ons" and reinstall (over my existing 2.11.1 install) to get it to work.
