### ISSUE TITLE
"Between" column empty. T18n issue?

### ISSUE THREAD

**Issue by sleeksorrow** [protz/thunderbird-conversations#1071]
The "between" column does not show any content for me with version 2.11.1 after updating Thunderbird from ancient ubuntu package version (38.6.0) to 45.0

Maybe this is some translation issue, because in the past I was used to have all text from Conversations Add-On to be translated correctly to german, but now all strings are english.

Will happily test things and provide info at request.

**Comment by protz** [comment]
Restart Thunderbird?

**Comment by MaluNoPeleke** [comment]
I have the same issue even after a restart with the German version of Thunderbird 45 and v2.11.1

**Comment by protz** [comment]
The column is no longer supported. Use the built-in correspondents 
column... it should go away, I don't know why it doesn't.

**Comment by MaluNoPeleke** [comment]
There is nothing like "correspondents" available and also all conversation related labels are written in English instead of German, which is quite strange.
![image](https://cloud.githubusercontent.com/assets/1446541/14644830/b7e7ffba-0653-11e6-83f6-e7a6094beb90.png)
![image](https://cloud.githubusercontent.com/assets/1446541/14644873/d1bb80a6-0653-11e6-8fcb-c88a679bcb50.png)

**Comment by pianoslum** [comment]
I am not up-to-date, but missing translations could be bug 622 again. This could happen if some of the files mentioned in that ticket are imported during initialization.

**Comment by protz** [comment]
Hmm... weird, I don't remember changing anything in there...

**Comment by MaluNoPeleke** [comment]
I also think that is has something to do with translations because directly after the update from Thunderbird 38 to 45 the conversation extension wasn't updated yet and everything was correctly displayed in German but after I updated the extension and a restart it switched to English.

**Comment by protz** [comment]
Yeah I need to repackage a new version of the addon with the 
translations included. I don't know how I failed this version... :(

**Comment by protz** [comment]
https://addons.mozilla.org/en-US/thunderbird/addon/gmail-conversation-view/versions/ has a pointer to 2.11.2 which fixes this. Sorry about the issue! Please shout out if this build doesn't fix your issue.

Regarding the "Between" column, please try out this build: it should definitely get rid of the column.

https://jonathan.protzenko.fr/thunderbird-conversations/201604301510-2.11+.xpi

You are now expected to use the newer "Correspondents" column introduced in Thunderbird 38. Not sure how it's called in German... it does what "Between" does, but better.

**Comment by MaluNoPeleke** [comment]
2.11.3 works as expected, thanks for that!
