### ISSUE TITLE
Plugin appears to not work with TB 45

### ISSUE THREAD

**Issue by ben-thul** [protz/thunderbird-conversations#1073]
I recently upgraded to Thunderbird v 45.0 and attempting to display any message with the plugin enabled displays "loading". As soon as I disable the plugin, messages display correctly again.

**Comment by protz** [comment]
Make sure you've updated the plugin, then restart Thunderbird.

~ jonathan

**Comment by ben-thul** [comment]
Ugh… that fixed it. Of course, TB is supposed to do this on its own. Sorry for the hassle and thanks for an amazing plugin!

**Comment by protz** [comment]
No worries!
