### ISSUE TITLE
No translation (Polish) after update

### ISSUE THREAD

**Issue by Vegebutcher** [protz/thunderbird-conversations#1074]
Yesterday I updated the plugin to 2.11.1 and the Polish translation is missing (BTW, I am the co-author of it). What happened?

**Comment by protz** [comment]
Can you check that the translations are indeed in the .xpi? I may have 
messed up something

**Comment by Vegebutcher** [comment]
The .xpi contains only one locale: en-US...

W dniu 19.04.2016 o 19:59, Jonathan Protzenko pisze:

**Comment by MaluNoPeleke** [comment]
See bug #1071

**Comment by protz** [comment]
https://addons.mozilla.org/en-US/thunderbird/addon/gmail-conversation-view/versions/ has a pointer to 2.11.2 which fixes this. Sorry about the issue! Please shout out if this build doesn't fix your issue.
