### ISSUE TITLE
Extra blank space at bottom of window

### ISSUE THREAD

**Issue by blerner** [protz/thunderbird-conversations#1075]
With TBConv 2.11.1 and TB 45.0, on Win7 (haven't tested other environments yet) I get weird extra "glass" at the bottom of the window.  It's about 1 toolbar tall, and only appears when Thunderbird is started maximized.  When I resize the window and then re-maximize it, the gap goes away.  I tried checking with DOM Inspector, and there's no element in that position besides the window itself.
![extra-glass](https://cloud.githubusercontent.com/assets/918464/14770559/863cbe40-0a42-11e6-9974-7767c5b224a9.png)
^ it's the gray bar at the bottom of this screenshot, below the status bar.

I tried disabling all of my addons except TBConv, and the problem remains.  I tried disabling TBConv, and the problem goes away.  I tried restoring all addons, and the problem stays gone.  I tried re-enabling TBConv (and restarting TB), and the problem comes back.  So I'm pretty sure it has something to do with TBConv, though I have no idea how.

This isn't a major problem, since it can be "fixed" by resizing the window, but it does seem odd.

**Comment by protz** [comment]
Huh I thought it was a bug in Thunderbird itself! Never thought the 
addon could cause it... I have no clue :(. As usual, help is most welcome.

~ jonathan

**Comment by blerner** [comment]
You tend to develop on a Mac, though, right? If you're seeing it too, that implies it's not an OS-specific issue...

**Comment by protz** [comment]
No, I've been seeing it on Windows only. I develop primarily on Linux, 
but my new employer tends to encourage the usage of windows laptops ;-).

~ jonathan

**Comment by blerner** [comment]
Is it possible that the window-is-ready logic that the bootstrapper and monkey-patcher use has changed slightly?  Or that one of your targets isn't there, so you're adding an item to the main window itself when it should've been nested somewhere?

**Comment by mkruselj** [comment]
I can confirm this issue. I also thought it was a TB bug, but nope... if I run TB in safe mode (or diable TBConversations), that empty space/black strip doesn't happen at all, so it's pretty obvious it's TBConversations' fault...

http://forums.mozillazine.org/viewtopic.php?f=39&t=3010931&p=14636117#p14636117

**Comment by blerner** [comment]
On a new Linux laptop, with TB 45.1.1 and TBConv 2.11.4, I *don't* see the empty strip...I think.  I haven't quite figured out how exactly Ubuntu is maximizing the window, so it's possible it starts non-maximized and then gets maximized, which triggers the resizing which triggers the reflowing of the UI so that the problem goes away.  It's quite tricky to describe: when I relaunch TB, it gets launched maximized, but the UI starts drawing as if it were non-maximized, and there's a solid gray background where the UI isn't getting drawn.  Then it reflows almost immediately, and everything snaps into the correct position with no extra background gray peeking out.

@mkruselj can you confirm that starting non-maximized and maximizing, or starting maximized and then restoring and re-maximizing, causes the problem to disappear?

**Comment by mkruselj** [comment]
Yes, I can confirm that case with maximizing, as well as disabling TBConversations also remedies the problem. Except of course I don't WANT to disable TBC (there's an awkward acronym if there ever was one :D)

**Comment by lehasb** [comment]
I can confirm this is still an issue with Thunderbird 52.2.1 and Conversations 2.11.4 on Windows 10. Color is the system Accent color.

Have there been any changes in the non-stable releases that might have fixed this, or is it still an 'unknown cause' bug?

**Comment by jeweloper** [comment]
some remarks:
1. The bug seems to only occur if TB "window layout" is set to "Wide View" or "Vertical View". The default option "Classic View" doesn't seem to be affected.
2. It also doesn't occur (regardless of the selected "window layout"), if the tabs aren't drawn into the (windows) title bar. (TB parameter "mail.tabs.drawInTitlebar" is set to "false").

OS: Win10
TB: 52.3.0
TBC: 201706111701-2.13+(2.12pre?)

**Comment by SemperRoto** [comment]
I also have this issue.
  
  Thunderbird version:
    57.7.0 (32bit)
    Thunderbird Conversation version:
    2.13.4
    Operating System:
    Windows 10 Home 10.0.17134 (1803)

When starting Thunderbird with Conversations active and the program does start as maximized window there is a additional empty big bar beneath the status bar single colored in the win10 design color. When starting unmaximized this does not occur. This seems to be a bug.

**Comment by Standard8** [comment]
This is no longer an issue on the latest Thunderbird (68) with Conversations (3.0.16) on Windows 10.
