### ISSUE TITLE
"Expand/collapse all messages" toolbar button doesn't seem to work reliably

### ISSUE THREAD

**Issue by blerner** [protz/thunderbird-conversations#1076]
(TB 45, TBConv 2.11.1, Win7)

This is a non-deterministic scenario, but: I have a message thread with emails in my inbox, my sent folder, and another folder.  Clicking on the arrow icon in the conversation bar while in the normal 3-pane conversation view (folders, messages, message) only toggles the first message.  Weirdly, if I click on "Show conversation in new tab", and then clicking on the expand/collapse button in that new tab, it works fine.  If I go back to the main tab, it doesn't work again.  But if I then click on a few of the messages in the message list (and wait for them to expand), and then try the button again, it does toggle all messages.

If I can get a more reliable repro, I'll try to record that.

**Comment by protz** [comment]
Hmm... this is weird. Let me know if you can pinpoint it further.

**Comment by Standard8** [comment]
I think this is working fine in the latest versions, we've had a lot of changes since 2.11.1 and a rewrite. If it is still an issue, please feel free to reopen or file a new issue.

**Comment by blerner** [comment]
Ok.  I'm still stuck on TB60, though, until some more addons catch up to TB68, so it'll take me some time to revisit this.
