### ISSUE TITLE
Lost of french translation

### ISSUE THREAD

**Issue by pointu** [protz/thunderbird-conversations#1079]
Since last update (to 2.11.1) we lost french translation ...

**Comment by LaurentBarbareau** [comment]
I confirm

**Comment by ruiposse** [comment]
I can confirm that pt-PT is also missing from the email header options (reply, forward, etc).

**Comment by protz** [comment]
https://addons.mozilla.org/en-US/thunderbird/addon/gmail-conversation-view/versions/ has a pointer to 2.11.2 which fixes this. Sorry about the issue! Please shout out if this build doesn't fix your issue.
