### ISSUE TITLE
Blank E-Mail with TB45

### ISSUE THREAD

**Issue by HyperCriSiS** [protz/thunderbird-conversations#1081]
Hi,

with newest update I cannot read E-Mails.
The preview stays just black. Also opening the Mail just displays a blank windows.

Regards,
Hyper

**Comment by protz** [comment]
Until 2.11.2 is approved on addons.mozilla.org, please use
https://jonathan.protzenko.fr/thunderbird-conversations/201605011513-2.11+.xpi
(and close the issue if that solves the problem for you!).

Thanks,

Jonathan

**Comment by HyperCriSiS** [comment]
Hi,

opening an E-Mail works now but preview is still broken.

Thanks,
Hyper

**Comment by msprotz** [comment]
Have you restarted Thunderbird after the upadte?

**Comment by HyperCriSiS** [comment]
Yes...

**Comment by HyperCriSiS** [comment]
It seems that this broke my Thunderbird now even with the addon disabled.
When I do a search and want to open a mail, it is also blank.
Do you think something different could be wrong here?

**Comment by protz** [comment]
If, after a restart, and after the addon disabled, Thunderbird still 
behaves incorrectly, then the issue is probably unrelated to the addon...

**Comment by HyperCriSiS** [comment]
I had time to make further tests.
Unfortunately it seems that it is still this addon causing the issues.
After I disable it, the issue is still there, but after a restart then, everything works fine again.

Which logs can I provide you to fix this?

Thanks,
Hyper

**Comment by zippy007** [comment]
Hi,

I have the same problem. Since Thundebird 45.1.0 on OSX the conversations view is broken. Emails open blank and preview does not work. Seems the plugin got broken. I have had to disable it to read emails. Is there any fix for this ?

**Comment by msprotz** [comment]
So, what I mean is, you have to upgrade the addon, THEN restart Thunderbird.

If that doesn't solve the problem, hit Tools > Error Console, clean the output, try to read a mail, and tell me of any errosr that show up.

**Comment by protz** [comment]
Closing for lack of reproducible steps.
