### ISSUE TITLE
wrong language TB45

### ISSUE THREAD

**Issue by der8en** [protz/thunderbird-conversations#1082]
Hello, since the update of Thunderbird to version 45.0 is Thunderbird Conversations in English
Thunderbird is installed on German
Before that everything was fine
![tb-fehler2](https://cloud.githubusercontent.com/assets/19150585/14958925/5c383ac4-108d-11e6-8db3-ae13a4caf6ff.jpg)

**Comment by protz** [comment]
Until 2.11.2 is approved on addons.mozilla.org, please use
https://jonathan.protzenko.fr/thunderbird-conversations/201605011513-2.11+.xpi
and close this issue if that solves your problem. Thanks!

**Comment by der8en** [comment]
Thank you
