### ISSUE TITLE
TB45 SMIME signed message show "Signed" in conversation view but not signed in "Message Security Info" (or icon in classic view)

### ISSUE THREAD

**Issue by rocketraman** [protz/thunderbird-conversations#1083]
I'm seeing that in Thunderbird 45 signed messages do show as "signed" in conversation view. But now, they show as such ONLY in conversation view with a little green "signed" icon.

Doing "Message, View Security Info" shows **incorrectly** that the message is **not** signed. Viewing the message in the classic view also does not show the classic signed icon, which is clickable to get the security details. Also, there is no way to get the signature details from conversation view. Disabling the conversation view extension restores proper operation of viewing emails with S/MIME signatures.

This used to work fine i.e. conversation view did not previously interfere with TB's built-in S/MIME handling, so some recent change somewhere seems to have broken it.

**Comment by protz** [comment]
Seems like a duplicate of #1066
