### ISSUE TITLE
Mails from Mailinglist are displayed as blank

### ISSUE THREAD

**Issue by leezu** [protz/thunderbird-conversations#1084]
Mails from a Mailinglist are not displayed correctly with the conversations addon for me. If I open them in the classic view, at least the attached messages can be seen.

The expected behaviour for me is, that the attached eml files are displayed inline.

I am using Thunderbird 38.4.0 on Linux with Conversations 2.10.2.

![conversations1](https://cloud.githubusercontent.com/assets/946903/15033788/760dcbec-12a1-11e6-8255-c37aadd61fa9.png)
![conversations3](https://cloud.githubusercontent.com/assets/946903/15033803/ae26a40e-12a1-11e6-90bb-7152038e502c.png)

**Comment by protz** [comment]
You probably need to enable the "I love attachments" option in the addon's preferences... reopen if that doesn't help. Thanks!

**Comment by leezu** [comment]
Unfortunately it does not help.

However, marking multiple messages, the first part of the mailinglist emails will be displayed within the preview section.

**Comment by leezu** [comment]
It seems I do not have the right to re-open this issue.

**Comment by protz** [comment]
This is likely a pathological corner case. Please confirm that after enabling the option, then restarting Thunderbird, you still have the same issue.

**Comment by leezu** [comment]
I can confirm that a restart does not fix the issue. I also installed the "Show All Body Parts" Addon and enabled it in the View menu.

**Comment by pianoslum** [comment]
Well, did you try to disable that extra addOn as well (and restart)? Might be a compatibility issue...

**Comment by leezu** [comment]
Unfortunately disabling "Show All Body Parts" does not help either. I installed it, as it seems to be required for the "Thunderbird Conversations" "I love attachments" option to work.

**Comment by protz** [comment]
Have you tried checking View > Display attachments Inline ?

**Comment by leezu** [comment]
This fixes the issue. Thanks :)

**Comment by leezu** [comment]
Furthermore I can confirm that the "I love attachments" is not needed in this case. Simply enabling "Display attachments Inline" suffices.

Maybe it should be enabled automatically after installing the Addon?

**Comment by protz** [comment]
The addon disables it via the setup assistant -- in most cases, it just 
results in enormous images being displayed in a very unsettling fashion.
