### ISSUE TITLE
New emails are added to wrong conversation

### ISSUE THREAD

**Issue by henchill** [protz/thunderbird-conversations#1085]
If i'm viewing a conversation, and I use the write button to create a new email thread, that new email is linked to the conversation that is currently being viewed. So essentially, completely unrelated emails are being grouped together as part of the same conversation. The attached example shows four unrelated emails being shown as one conversation. I've given the messages different colors based on the thread they are part of. 
![convo-bug](https://cloud.githubusercontent.com/assets/5391836/15056397/408e05b6-12c6-11e6-907c-d66cff2a2475.png)

**Comment by protz** [comment]
I'm confused. I think that it's normal that if you hit "reply", then the 
reply is linked to the conversation you're replying to. If you want to 
start a new thread, compose a new message...?

**Comment by henchill** [comment]
The issue is that if you compose a new message, for whatever reason, that
new message is linked to the conversation you were viewing as if they were
part of the same conversation although they are not.

**Comment by protz** [comment]
Using the "write" button that is next to the "get messages" button?

**Comment by henchill** [comment]
Yes.

**Comment by protz** [comment]
This is https://bugzilla.mozilla.org/show_bug.cgi?id=646225 I suspect (see https://github.com/protz/thunderbird-conversations/wiki)
