### ISSUE TITLE
Gallery view doesn't seem to be working in latest version

### ISSUE THREAD

**Issue by blerner** [protz/thunderbird-conversations#1087]
I get two errors:
Timestamp: 5/6/2016 3:36:07 PM
Error: ReferenceError: $ is not defined
Source File: chrome://conversations/content/gallery/js/gallery.js
Line: 113

Timestamp: 5/6/2016 3:36:07 PM
Error: ReferenceError: jQuery is not defined
Source File: chrome://conversations/content/gallery/js/jquery.lightbox-0.5.js
Line: 473

And a tab titled "tbGallery" with no content in it.  Could this be part of the recent packaging/building problems?

**Comment by protz** [comment]
No, it's a fallout from the fact that jquery was removed from 
Thunderbird itself. @shirosaki sent a patch for that a while ago... but 
I guess I neglected to perform the same fix for the gallery view.

**Comment by msprotz** [comment]
Please try https://addons.mozilla.org/en-US/thunderbird/addon/gmail-conversation-view/versions/ (2.11.4). Thanks=

**Comment by blerner** [comment]
Seems better now :)
