### ISSUE TITLE
Sort messages in a thread purely by date

### ISSUE THREAD

**Issue by lindsayad** [protz/thunderbird-conversations#1088]
Hi all,

Is there a way to sort messages in a thread purely by date? I get a lot of email from google groups, and sometimes this mail gets grouped into sub-threads which can result in non-chronological ordering. This is demonstrated in the attached image.

![not_sorted_by_date](https://cloud.githubusercontent.com/assets/10248304/15303981/97bacfd4-1b6f-11e6-9b3a-f99db12e407d.png)

**Comment by protz** [comment]
That's the grouping feature of Thunderbird (the "thread pane"). In the 
conversation view emails are sorted by date

**Comment by lindsayad** [comment]
Ah, I see it very nicely sorted by date in the conversation pane. Thank you!

![sorted_by_date](https://cloud.githubusercontent.com/assets/10248304/15304808/631c7e4e-1b74-11e6-929e-22709dd04a94.png)
