### ISSUE TITLE
"Allow remote content from..." problems

### ISSUE THREAD

**Issue by gregorko** [protz/thunderbird-conversations#1090]
When I activate the plugin the remote content privacy options menu show strange entries:

![clipboard-2](https://cloud.githubusercontent.com/assets/647058/15455250/0ba216c6-204f-11e6-843f-6024776e6d70.jpg)

When I disable the plugin the menu shows correctly:

![clipboard-1](https://cloud.githubusercontent.com/assets/647058/15455260/2c8504de-204f-11e6-8644-ffc933fd1dfe.jpg)

**Comment by protz** [comment]
Yes... there was a corresponding discussion somewhere in bugzilla and then I couldn't understand what needed to change on my side to fix this. Pull request welcome.

**Comment by protz** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1266356

**Comment by Standard8** [comment]
The UI is much simpler now, and this doesn't happen.
