### ISSUE TITLE
Thunderbird Conversations Still Mixing Up Emails

### ISSUE THREAD

**Issue by oliverb456** [protz/thunderbird-conversations#1094]
#789 #1093 #1085 Thunderbird is mixing up emails that are not in the same thread. My gmail account is grouping messages correctly, but Thunderbird is including random messages within threads. It almost seems like Thunderbird Conversations is grouping emails based on keywords.

**Comment by protz** [comment]
This is https://bugzilla.mozilla.org/show_bug.cgi?id=646225 I suspect (see https://github.com/protz/thunderbird-conversations/wiki)
