### ISSUE TITLE
Add option to selectively use Galery View, Contact Hovercards, Threaded View

### ISSUE THREAD

**Issue by smihael** [protz/thunderbird-conversations#1095]
It would be nice if one could select which plugins should be used. Some of the features are not alwasy working properly (see https://github.com/protz/thunderbird-conversations/issues/1094), but I would like to continue using other cool features (for example Contact Hovercards with profile picture and link to recent conversations).

**Comment by protz** [comment]
Too much work... but thanks for the suggestion.
