### ISSUE TITLE
'Reply (all) in new window' opens multiple windows

### ISSUE THREAD

**Issue by trife** [protz/thunderbird-conversations#1099]
Steps to repeat:
1. Receive email
2. Open email in new tab
3. Receive additional email that gets added to conversation
4. Switch to tab from (2)
5. Click 'Reply (all) in new window'

The number of new windows opened is equal to the number of messages in the conversation. If you close the conversation and reopen it, this issue does not exist.

**Comment by protz** [comment]
Probably some event handler that gets attached again.

**Comment by Standard8** [comment]
This should be fixed in the latest Thunderbird 68 / Conversations 3.0.16 - we've rewritten the UI and changed how the event listeners work.
