### ISSUE TITLE
Tabs aren't loaded anymore

### ISSUE THREAD

**Issue by danielcalencar** [protz/thunderbird-conversations#1101]
Steps to reproduce the bug:
1. Start thunderbird
2. open some e-mails of interest and leave them opened
3. close thunderbird
4. start thunderbird

-> the tabs that should have been loaded are empty and have the title "Conversation reader"

I am using thunderbird 45.1.1/pt-br on Windows 10

**Comment by Linuspogo** [comment]
Seems to be a duplicate of Issue #1091
