### ISSUE TITLE
can't figure out how to sort folders/accounts

### ISSUE THREAD

**Issue by cstacy** [protz/thunderbird-conversations#1103]
The documentation makes mention of some kind of icon for sorting folders?
I would like to control the order of accounts under both the global inbox,
and especially the order of folders under the individual accounts below.

I was using the "manual sort folders" addon, but it doesn't seem to play with other extensions so I removed it. Does your extension really subsume it's functionality?  Thanks!

**Comment by protz** [comment]
No. I happen to be the author of "manually sort folders" but this extension has another purpose.
