### ISSUE TITLE
Page not working

### ISSUE THREAD

**Issue by mrahmadt** [protz/thunderbird-conversations#1106]
Hello

in the FAQ you are referring to this link http://blog.xulforum.org/index.php?post/2010/11/27/Thunderbird-Conversations-plugins which is not working,

any chance you can write the content to github wiki?

**Comment by protz** [comment]
Argh! Yes that would be helpful. Thanks for reminding me of it.

**Comment by protz** [comment]
In the meanwhile, there's some sample plugins in the source tree already (e.g. enigmail.js)

**Comment by Standard8** [comment]
I'm going to close this in preference to #1431 - we're going to be changing how these plugins work soon, so we'll do that and document this all at the same time.
