### ISSUE TITLE
Improper updating of existing plugin with TB45, needed reinstall

### ISSUE THREAD

**Issue by wolftune** [protz/thunderbird-conversations#1107]
With the new TB version, I today had to disable thunderbird-conversations in order to read any messages at all. It just stays stuck on "Loading…" while this is enabled. See https://support.mozilla.org/en-US/questions/1118646

**Comment by davidpuzey** [comment]
I was seeing this too.
I tried disabling and re-enabling the Addon, when I clicked on the "Apply changes" button I'd get log messages like this:
JavaScript strict warning: resource://conversations/modules/conversation.js, line 86: ReferenceError: reference to undefined property this._toRun

In the end I tried reinstalling the Addon and that seems to have fixed it. I'm guessing something went wrong during upgrade.

**Comment by martinclaus** [comment]
@davidpuzey Your suggestions fixed this problem for me!

**Comment by wolftune** [comment]
@davidpuzey +1 that worked, changing the title here

**Comment by protz** [comment]
I think it's an upgrade issue... restarting Thunderbird would've solved it.
