### ISSUE TITLE
two vertical scrollbars in some emails

### ISSUE THREAD

**Issue by OlegYch** [protz/thunderbird-conversations#1108]
![screenshot_20](https://cloud.githubusercontent.com/assets/268312/17083869/f5ad5ffe-51b5-11e6-815a-ca46181790d4.png)
here is an example of a email from quora
for some reason it has two scrollbars, the inner one doesn't scroll anything, but prevents the outer scrollbar from captuting focus

**Comment by SimJoSt** [comment]
I can report to have run into this problem also.
Just from memory I would say it was with html mails only, but I can't say for sure.

**Comment by protz** [comment]
There's absolutely nothing I can do about this, sadly.

Mozilla has always declined to provide proper web support for that scenario (see https://bugzilla.mozilla.org/show_bug.cgi?id=80713); as such, I end up with terrible, terrible "hacks" to compute the proper height of the inner iframe, and then sometimes these hacks fail. I see no solution looking forward.
