### ISSUE TITLE
can´t install

### ISSUE THREAD

**Issue by joysone** [protz/thunderbird-conversations#1109]
Hi,

i´m running TB 14.2 on Windows and wanted to install Conversations 2.11.4. But the Installassistent is working without ending... Console:

Zeitstempel: 28.07.2016 22:52:22 Fehler: 2016-07-28 22:52:22    Conversations.AssistantUI   ERROR   Error in customization actionSetupView  Quelldatei: resource:///modules/gloda/log4moz.js Zeile: 691

Zeitstempel: 28.07.2016 22:52:22 Fehler: 2016-07-28 22:52:22    Conversations.AssistantUI   ERROR   TypeError: eid(...) is null Quelldatei: resource:///modules/gloda/log4moz.js Zeile: 691

Zeitstempel: 28.07.2016 22:54:16 Fehler: 2016-07-28 22:54:16    Conversations.Stub  ERROR   No such string Details Quelldatei: resource:///modules/gloda/log4moz.js Zeile: 691

Any idea? Thanks!

**Comment by pianoslum** [comment]
See https://github.com/protz/thunderbird-conversations/issues/1114

TB 14 is rather old, isn't it?
