### ISSUE TITLE
Copy email address icon mistakenly shows "paste" image

### ISSUE THREAD

**Issue by erros84** [protz/thunderbird-conversations#1111]
Thunderbird 45 (Windows 10) with Conversations Enabled: Steps to reproduce:

In a message, I mouse over the sender's email address in the header.

![2016-08-08 15_06_04-start](https://cloud.githubusercontent.com/assets/986339/17484585/8a680e8c-5d82-11e6-8a8e-97e2a2bf0ac6.png)

The resulting dialogue presented me with an option to "Copy email address to clipboard", but surprisingly the icon displayed is the international standard for "Paste" (the clipboard and sheet). (See attached image 2016-08-08 15_06_04-Start.png)

Expected results:

This is obviously a copy option, and not a paste option. The image on the icon should be the standard for copy, with two sheets of paper slightly offset. For example: http://hexler.net/gfx/_docs/touchosc-editor-basics2.png

**Comment by protz** [comment]
Can you submit a pull request that fixes this? The icon should have an open license.

**Comment by protz** [comment]
I seem to recall the icon came from the famfamfam set.

**Comment by xi** [comment]
The corresponding icon from the famfamfam silk icon set is probably "page_copy": ![page_copy](https://cloud.githubusercontent.com/assets/202576/23066808/a505862a-f51c-11e6-815d-6dfb9e654d35.png)

However, I don't really think that this improves usability because it is a very pale icon.

**Comment by protz** [comment]
@xi we could probably come up with something better, more in line with the new set of icons for the material design re-skinning... what's the material icon for copy?
