### ISSUE TITLE
Button is labeled "undefined" with PGP Mail

### ISSUE THREAD

**Issue by yoshimo** [protz/thunderbird-conversations#1113]
Following setup:
- Thunderbird 45.2.0
- Enigmail 1.9.4
- TB Conversations 2.11.4

I noticed that the button in the light blue box that says "mail was decrypted, signature NOT verified.  "press Import Key" to download the key" is labeled "undefined" if TB-Conversations is enabled.

Without TBC there are 2 Buttons "Import Key" and "Details"

**Comment by Siggi0904** [comment]
Yes, I can confirm that.
I think there is a problem in Tunderbird Conversations.

- Thunderbird 45.4.0
- Enigmail 1.9.5
- TB Conversations 2.11.4

**Comment by protz** [comment]
@shirosaki ... thoughts?

**Comment by yoshimo** [comment]
Enigmail 2.0 with a large redesign is also coming up early next year.
Just as a heads up

**Comment by Standard8** [comment]
A lot has changed in the last few years wrt Conversations. If this is still an issue in the latest Thunderbird/Conversations/Enigmail please feel free to re-open or file a new one.

A screenshot would help as well.
