### ISSUE TITLE
First run assistant never completes

### ISSUE THREAD

**Issue by zigojacko** [protz/thunderbird-conversations#1114]
Running Thunderbird Conversations on Windows 7 64-bit and the 'First run assistant' never completes, it just sits there with the spinning icon saying 'Working...'. Have tried numerous times and left it for days but doesn't seem to be doing anything. It does not seem like any of the emails have been converted to conversations either although it has grouped all the inboxes, drafts, sent, archives etc folders for all each mailbox.

I wouldn't say there is an excessive amount of emails in my Thunderbird and I have used this add-on before on the same mailboxes previously without issue and on a Windows 8 laptop, it did not have a problem.

Is there anything I can do to figure out why this isn't working?

**Comment by NullFragment** [comment]
I've been having the same issue on Win10 and OSX. It seems like it's the newest version of Thunderbird that's causing the issues. I have been using this add-on for quite a while now with no problems, but in the past week or two it has just stopped functioning.

**Comment by Dragnell87** [comment]
After the last update of Thunderbird 45.2 i have the same issue on linux

**Comment by zigojacko** [comment]
Any advice on this problem @protz ?

**Comment by cpoms** [comment]
I have the same issue on Windows 8.1 / Thunderbird 45.2 / Thunderbird Conversations 2.11.4.

**Comment by cdysthe** [comment]
Having the same issue on 45.2.0 running Ubuntu 16.04 x64

**Comment by alpha-and-omega** [comment]
Same here. Icedove (rebranded Thunderbird) 45.2.0. Debian Linux 64x.
It worked half a year ago.
I tried to disable/enable addon after experiencing crashes (yes, crashes started ~2-3 months ago). I successfully disabled addon, but was unable to enable it again. Only restore from backup saved me.
Can you please tell me how to debug this ?

**Comment by bro3234** [comment]
Experienced this same issue on 45.3.0 running on a Mac with OS X 10.10.5.

**Comment by lindsayad** [comment]
Same issue, 45.2.0, Ubuntu 16.04 x64. Just like others, conversations worked great until about a month ago; must have been one of the new thunderbird releases that broke conversations

**Comment by lindsayad** [comment]
If I had some idea where the bug was, I would be willing to try to look into a fix because I love this add-on when it works

**Comment by zigojacko** [comment]
Yeh, same. I wouldn't have a clue where to start with looking into a fix for this and it has currently made a right mess of my Thunderbird frustratingly. Shame it has been broken for quite a while now and no response from the developer. Hopefully someone else will notice this from experiencing the issue and have a better idea on what is needed to fix it.

**Comment by pianoslum** [comment]
I think the relevant exception is this:

`
2016-09-23 01:28:33	Conversations.AssistantUI	ERROR	Error in customization actionSetupView
2016-09-23 01:28:33	Conversations.AssistantUI	ERROR	TypeError: this.dbView is null
2016-09-23 01:28:33	Conversations	DEBUG	
DBViewWrapper.prototype._viewFlags@resource://gre/modules/dbViewWrapper.js:1308:1
DBViewWrapper.prototype.showThreaded@resource://gre/modules/dbViewWrapper.js:1724:7
MsgSortThreaded@chrome://messenger/content/threadPane.js:267:3
Customizations.actionSetupView.install/moveOn@resource://conversations/modules/assistant.js:202:9
Customizations.actionSetupView.install/waitForIt@resource://conversations/modules/assistant.js:221:11
Customizations.actionSetupView.install@resource://conversations/modules/assistant.js:225:7
install@chrome://conversations/content/assistant/assistant.xhtml:32:31
onFinish@chrome://conversations/content/assistant/assistant.xhtml:83:11
onclick@chrome://conversations/content/assistant/assistant.xhtml:1:1
`
`mainWindow.MsgSortThreaded();`

This is non-Conversations-Code and I cannot step into it. Does anybody know what this function does?

**Comment by pianoslum** [comment]
I think this is a bug on thunderbird side. I filed a report here: https://bugzilla.mozilla.org/show_bug.cgi?id=1305008

The commit that (likely) introduced it had Thunderbird 45.0 as milestone. This would be the explanation why the bug occurs for the latest version.

**Comment by pianoslum** [comment]
I just want to add that for me (Arch linux, TB 45) the setup also never completes but the addon works without problems afterwards!

**Comment by pianoslum** [comment]
The bug I mentioned above has been fixed on the thunderbird side. This is included in tb 50, I don't know whether it is going to be added for tb 45 as well.

There was another issue: assistant.js:213 refers to the between-column, which is deprecated by now.

As I think that both calls are not too important, I deleted/uncommented the respective lines in this branch: https://github.com/pianoslum/GMail-Conversation-View/tree/FixInstallationHanging
With this fix, the installation works for me.

@zigojacko , @NullFragment , @Dragnell87 , @cpoms , @cdysthe , @alpha-and-omega , @bro3234 , @lindsayad would you be so kind to test the fix? I included the conversations.xpi in my branch, which can be installed via the addOns menu.

As usual, there is no warranty for anything, but I hope it should work for you!

**Comment by zigojacko** [comment]
That's great work @pianoslum, thanks for trying to get this fixed. I have updated Thunderbird to the latest version of 45 but also downloaded the beta 50. I removed the add-on, re-added it from your version and changed the default view to threaded and it 'appears' so far to be working as expected (although continuing to test).

Thanks very much! :)

**Comment by nicholashead** [comment]
Could this have something to do with the "Between" column? That part of the setup never works/shows up for me. Even when I try and manually add the column, it's not on the list.

**Comment by pianoslum** [comment]
I think so - I just deleted the line in my commit https://github.com/pianoslum/GMail-Conversation-View/commit/b8bd37d073aaf332bce526e0126a78a10e7f1175

Unfortunately I have no insight what to do that the column shows up again, sorry...

**Comment by protz** [comment]
Tremendous thanks to @pianoslum -- just merged his branch in and will issue a bugfix release shortly.

The between column is gone; the new "Correspondents" column in Thunderbird 45+ does the job better and, I suspect, with better performance too.
