### ISSUE TITLE
Switch from BzAPI to the Bugzilla native REST API

### ISSUE THREAD

**Issue by edmorley** [protz/thunderbird-conversations#1116]
Since the former is deprecated and 2-10x slower in many cases. See:
https://bugzilla.mozilla.org/show_bug.cgi?id=1301541
https://bugzilla.mozilla.org/show_bug.cgi?id=1035804

https://github.com/protz/thunderbird-conversations/blob/b989e21b7b0e8340286d8bde81e9a3d3cb508798/content/stub.compose-ui-bz.js#L49-L54

**Comment by protz** [comment]
Hi Ed,

Sorry for the delay in responding. I have close to zero time for the addon except for the bug triaging and occasional critical bugfix. Do you think you could submit a pull request? I'd love to integrate that change...

Thanks,

Jonathan

**Comment by Standard8** [comment]
We're going to be dropping the bugzilla integration, hence closing out.
