### ISSUE TITLE
Set a User Agent when making requests to Bugzilla's API

### ISSUE THREAD

**Issue by edmorley** [protz/thunderbird-conversations#1117]
It's best practice to set an informative User Agent when making requests to an external API, and helps those maintaining the API track the sources of inefficient queries/heavy load :-)

https://github.com/protz/thunderbird-conversations/blob/b989e21b7b0e8340286d8bde81e9a3d3cb508798/content/stub.compose-ui-bz.js#L245-L250

**Comment by protz** [comment]
Pull request most welcome! thinking about issuing a bugfix release while I have some respite from my daily work during the holiday season... if you feel like fixing this before the next point release, let me know :)

**Comment by Standard8** [comment]
We're going to be dropping the bugzilla integration, hence closing out.
