### ISSUE TITLE
Google Maps links must be used in an iframe

### ISSUE THREAD

**Issue by blerner** [protz/thunderbird-conversations#1118]
![screenshot](https://cloud.githubusercontent.com/assets/918464/18570707/507f25b4-7b7a-11e6-9c6b-c3e6a851a7d8.jpg)

**Comment by protz** [comment]
Do you have any fix in mind? Otherwise, I'm inclined to just remove this feature (I would happily merge a pull request that does so.)

**Comment by blerner** [comment]
No, I hadn't looked into it.  From https://developers.google.com/maps/documentation/embed/guide, it looks like the fix is to just tweak the URL built up at https://github.com/protz/thunderbird-conversations/blob/master/modules/plugins/embeds.js#L144, I guess.

**Comment by protz** [comment]
Just tried this and it doesn't help. I guess they must have some sort of sniffing going on... this is potentially hard to debug.
