### ISSUE TITLE
"Reply" and "Reply All" fields are too wide and "shrink" when conversation opens

### ISSUE THREAD

**Issue by pianoslum** [protz/thunderbird-conversations#1122]
This only happens when both "Reply" and "Reply All" fields are shown in the quick reply pane (i.e. if there is more than one recipient).

If so, the width for both fields is too wide (perhaps the same width as a single "Reply" field for the one-recipient-case) and you can see that both fields shrink until they fit. This lasts less than a second but is visible nontheless.

I guess you just have to adjust the initial width but I could not find where to edit it!

**Comment by protz** [comment]
Isn't it the CSS animation that is meant to happen? Happy to take a pull request that improves the behavior...

**Comment by pianoslum** [comment]
Iirc this happens only on this computer (I think it depends on the resolution). For me it look odd that the two field are on two "lines" at first and then slide into one.
Is this expected behaviour?

![shrink](https://cloud.githubusercontent.com/assets/8868890/21624453/6f9516fa-d207-11e6-9b0f-6d3ed0263075.gif)

**Comment by msprotz** [comment]
Oh no the expected behavior is that they are on the same line at first... probably some -moz- prefix stopped working.

**Comment by pianoslum** [comment]
@xi As I see you're good with CSS - and I have no clue... Can you reproduce this, or do you have an idea what could be causing it?

**Comment by msprotz** [comment]
It seems to have been fixed by @xi's  latest pull request, which, incidentally, could use some help for debugging code https://github.com/protz/thunderbird-conversations/pull/1141 :)

**Comment by xi** [comment]
I haven't really looked into the quick reply code yet. If the issues is really somehow fixed by #1141 that good. But I expect a lot of refactoring opportunities there.
