### ISSUE TITLE
[FR] Google Inbox features

### ISSUE THREAD

**Issue by ildar** [protz/thunderbird-conversations#1124]
The Inbox as a new vision of Google has a few features that GMail doesn't. That'd be very nice to have them.
The 1st one of them is "postponing" a message until the right time for it.
What do you think?

**Comment by protz** [comment]
I have very, very little time available for the addon so, sadly, I must decline the feature request; if you came up with a pull requests that implements it, I'd be more than happy to provide guidance and review it, though.
