### ISSUE TITLE
How do you fix the loading tab of the conversation 

### ISSUE THREAD

**Issue by itsdeux** [protz/thunderbird-conversations#1125]
I've had this problem for a long time and I would hope some one can help me out here to solve this... 

The conversation that I want to have open after closing the Thunderbird, doesn't load back up. 

![thunderbird conversation tab loading](https://cloud.githubusercontent.com/assets/20030734/20452109/5d01d952-adb7-11e6-978f-c1d6389e987e.jpg)

Any help please!!!

**Comment by martinjuju** [comment]
Duplicate of #1091 
see also #1123

**Comment by itsdeux** [comment]
I'm fairly new to this coding thing, how would i go about doing this?
