### ISSUE TITLE
Disabling sent from some accounts

### ISSUE THREAD

**Issue by luison** [protz/thunderbird-conversations#1130]
I am trying to use the extension but my setup includes aprox 7 large to massive accounts read with imap. One of them includes a system account from which we send various system automatic emails which makes some emails I receive loaded with "related" threads that are really irrelevant.
Could not find a setting to disable the extension from working either with a whole account of the ones configured or with an specific folder like "sent". 
In case that option is not available please consider this a suggestion. Thanks.

**Comment by protz** [comment]
I have very, very little time available for the addon so, sadly, I must decline the feature request; if you came up with a pull requests that implements it, I'd be more than happy to provide guidance and review it, though.
