### ISSUE TITLE
Unified Inbox should search "Sent Folder" only for conversations in the Inbox 

### ISSUE THREAD

**Issue by cpacchierotti** [protz/thunderbird-conversations#1131]
I would like to see the messages that I have sent in the Unified Inbox only when they are part of a conversation I have in my Inbox.

For example, now, if I send a brand new e-mail (no thread involved), the sent e-mail appears in the Unified Inbox, which feels strange. However, if that e-mail is part of a larger conversation that is in my Inbox, then it should be there, part of its own conversation.

Thank you very much.

**Comment by protz** [comment]
This is an underlying Thunderbird issue and there's not much I can do about it, sadly... so I'm closing this. The unified inbox is a Thunderbird feature -- I'm pretty sure you could find on bugzilla.mozilla.org a comparable feature request.

Thanks,

Jonathan
