### ISSUE TITLE
[FR] visual marks in the threads list

### ISSUE THREAD

**Issue by ildar** [protz/thunderbird-conversations#1132]
Inbox/GMail interfaces also feature some advanced visual marks for threads. I'd like to see at least following:

1. Mark the threads which have messages in Drafts
2. show the names of IMAP folders that contain messages from this thread

**Comment by protz** [comment]
I have very, very little time available for the addon so, sadly, I must decline the feature request; if you came up with a pull requests that implements it, I'd be more than happy to provide guidance and review it, though.
