### ISSUE TITLE
Messages in the message viewer window should have the same sort order as in the email list window

### ISSUE THREAD

**Issue by lyspooner** [protz/thunderbird-conversations#1149]
Messages in the message viewer window should have the same sort order as in the email list window

Or I would like the option to manually put new messages at the top of the message window. 

Thank you.

**Comment by pianoslum** [comment]
According to the FAQ:

> I want the most recent message on top:
> The conversation view doesn't have support for reversing the order of the messages. There used to be such a feature, but it added a tremendous amount of complexity in the code, so the big 2011 summer rewrite removed the feature.
