### ISSUE TITLE
Cannot finish setup - Either 'Indexing' forever, or conversations doesn't enable

### ISSUE THREAD

**Issue by kobaz** [protz/thunderbird-conversations#1160]
Conversations has been broken for me since thunderbird version 47 or so.  I've tried all the thunderbird betas, and I downloaded the latest dev version: https://jonathan.protzenko.fr/thunderbird-conversations/201702191737-master.xpi

Usually what happens is in my activity window it says 'indexing'.  And just sits there... there's no % complete, or any counts/numbers estimated... zero information.

I've tried removing all of my index files in thunderbird (*.msf files).  I've disabled and enabled global search indexing, and removed the sqlite index files.

I really miss conversations... I haven't been able to use it in years.  Any help would be greatly appreciated.

**Comment by elioqoshi** [comment]
I get the same problem everytime, on Windows and Linux. I just cancel the process and Conversations works fine for me anyway. But yeah, we should look into this

**Comment by kobaz** [comment]
![indexing](https://cloud.githubusercontent.com/assets/1695852/23665149/adcf72ae-0325-11e7-8dc9-2cb63ba29ffa.png)

Here's what happens when it's stuck indexing

**Comment by kobaz** [comment]
![indexing](https://cloud.githubusercontent.com/assets/1695852/23665199/ce76cebc-0325-11e7-8361-394a5cbfab53.png)

Here's what happens when it's stuck indexing

**Comment by kobaz** [comment]
I have conversations enabled in View -> Conversations View

All the other normal options are turned on, such as sort by threads and etc.  But conversations never loads the list of related emails.  I only see one email body listed.

Example: Here's an email in the middle of a thread that only shows itself and nothing related... (All emails in all threads are like this)

![conversations](https://cloud.githubusercontent.com/assets/1695852/23665607/f2547f40-0326-11e7-81fe-65638bfa0575.png)

**Comment by kobaz** [comment]
Here's a bit from my Error Console

2017-03-07 12:06:49	Conversations.Conversation	WARN	Warning: gloda query returned no messages

2017-03-07 12:06:49	Conversations.Message	WARN	Streaming the message because Gloda has not indexed it, this is BAD

**Comment by protz** [comment]
I think Gloda is basically broken on beta, earlybird and nightly. This
breaks pretty much the rest of Conversations.

**Comment by doits** [comment]
I can confirm that switching back to 45.8.0 solved this problem for me

**Comment by protz** [comment]
Thanks.
