### ISSUE TITLE
Vertical alignment is gone for attachment icons

### ISSUE THREAD

**Issue by protz** [protz/thunderbird-conversations#1162]
![image](https://cloud.githubusercontent.com/assets/214707/23837978/c3977d12-074d-11e7-898a-9540f434bf89.png)

@xi @fllp any clues?

Thanks,

Jonathan

**Comment by elioqoshi** [comment]
By the way, can we design new icons for attachments? Some which feel less skeuomorphistic? I could do them if you would agree. Just would need a list of icons we support right now

**Comment by msprotz** [comment]
https://github.com/protz/thunderbird-conversations/tree/072fd4aa60a85679ac5a30d366305040f4ae50e1/skin/icons

**Comment by elioqoshi** [comment]
@msprotz Cool, will get right to that
