### ISSUE TITLE
Tag + names feels crammed

### ISSUE THREAD

**Issue by protz** [protz/thunderbird-conversations#1163]
![image](https://cloud.githubusercontent.com/assets/214707/23840137/f9b5123a-075f-11e7-8bf3-162dfbe34e4c.png)

Did @elioqoshi's design intend to have more spacing around these? It feels a little heavy right now.

@xi @fllp 

Thanks!

Jonathan

**Comment by elioqoshi** [comment]
Yeah, it should have a bit more spacing, probably like this:

![label](https://cloud.githubusercontent.com/assets/5436686/23853852/d1f5121a-07ee-11e7-9696-858e49ba2ef8.jpg)

This is about 150% more spacing of the original
Also, the ' x ' is not perfectly aligned vertically. Needs to be a tad bit higher.
