### ISSUE TITLE
No icon for preview

### ISSUE THREAD

**Issue by msprotz** [protz/thunderbird-conversations#1164]
![image](https://cloud.githubusercontent.com/assets/10673049/23841688/41d6a3a6-076c-11e7-8a02-dda5fbe0c954.png)

@xi @fllp any idea what icon may work?

Thanks!

Jonathan

**Comment by elioqoshi** [comment]
I'd suggest the visibility icon from Material design:
https://images.duckduckgo.com/iu/?u=http%3A%2F%2Fimage.flaticon.com%2Ficons%2Fsvg%2F60%2F60809.svg&f=1

https://material.io/icons/#ic_visibility

**Comment by xi** [comment]
The visibility icon is already in use to to toggle read/unread. What about [pageview](https://storage.googleapis.com/material-icons/external-assets/v4/icons/svg/ic_pageview_black_24px.svg)?

**Comment by pianoslum** [comment]
The pdf-icon is not properly centered, btw...

**Comment by elioqoshi** [comment]
@xi pageview sounds good, yes

**Comment by fllp** [comment]
Too bad there's nothing that would pass for a 'new' sticker  in material
icons. Like this: http://fontawesome.io/icon/certificate/
That would work better for read/unread, i think. 'visibility' then would
be a good choice for preview.
Any chance we could 'import' that?

**Comment by xi** [comment]
> Any chance we could 'import' that?

I can check

**Comment by xi** [comment]
Ok, I was a bit confused. #1165 fixed the original issue that there was no icon. But we also discussed that we want to use the eye for preview and a star to toggle read/unread. That was discussed in #1168. I will do a proper fix this week.
