### ISSUE TITLE
freeze when viewing specific email

### ISSUE THREAD

**Issue by Chris115v** [protz/thunderbird-conversations#1167]
When I try to view the attached email, TBird freezes with the spinning beach ball and 100% CPU for about 2 minutes, then comes back and shows the email. The email address is not known, so at first it's blocking images. If I click to show remote images, same freeze happens for a couple minutes then it works again and shows the images. Also happens after I check always allow images from email address.

I'm able to view it fine in TBird safe mode. Only happens when I re-enable Conversations.

TBird 52.0b4
Conversations 2/20/2017  2.12pre

[fetch>UID>.INBOX>57327.INBOX%3E57327.txt](https://github.com/protz/thunderbird-conversations/files/840300/fetch.UID.INBOX.57327.INBOX.3E57327.txt)

[Spindump.txt](https://github.com/protz/thunderbird-conversations/files/840303/Spindump.txt)

[Sample of Thunderbird.txt](https://github.com/protz/thunderbird-conversations/files/840304/Sample.of.Thunderbird.txt)

**Comment by msprotz** [comment]
Can you send me the faulty email using the email address at jonathan.protzenko.fr ? Please (in the menus) Message > Forward As > Attachment, otherwise I won't be able to do anything with it.

**Comment by Chris115v** [comment]
I am not able to pull it up, oddly. TBird search finds it but I can't actually get to the email. I may have deleted it, so not sure why TBird is showing it while my gmail account isn't.

**Comment by protz** [comment]
Closing (no repro). Thanks for reporting...
