### ISSUE TITLE
Conversion not loading when Thunderbird opened

### ISSUE THREAD

**Issue by LupusUmbrae** [protz/thunderbird-conversations#1169]
I've noticed that if I close Thunderbird with a conversation open in a new tab, then open it again the new tab will always be `loading`, and the tab itself will always be called `Conversation Reader`.

This also occurs if i drag the tab to create a new window. New tabs work fine

![tb converstaion reader loading](https://cloud.githubusercontent.com/assets/914585/23987651/87cbffc4-0a22-11e7-86d8-1da99cd3d20f.PNG)

**Comment by protz** [comment]
https://jonathan.protzenko.fr/thunderbird-conversations/ has a development
version that fixes this problem... if that fixes your issue, please close
this. Thanks!

**Comment by spagetticode** [comment]
I would like to confirm the development version fixes this issue! I've been looking for a solution for this problem for quite some time now. Thanks Protz for developing this addon. Greatly appreciated.
