### ISSUE TITLE
Email window size/position

### ISSUE THREAD

**Issue by js017** [protz/thunderbird-conversations#1170]
The email window size/position isn't remembered when restarting Thunderbird when using Thunderbird Conversations. Is there a way to set a custom view for an email window size/position and have Thunderbird remember it the next time it starts? When opening an email in a new window or reading it in the preview pane, only the most recent email in the conversation is expanded by default. In order to expand all emails in the conversation, you have to click the "Expand/collapse all messages" button each time you open an email. Is there a way to change it to expand all emails in the conversation by default without having to change the setting each time you open a new email? Is there a way to change the sorting order of conversations and save the setting to use by default? Is there a way to get Thunderbird Conversations to work without creating a copy of the sent email in the inbox folder? Thanks.

**Comment by xi** [comment]
> Is there a way to change it to expand all emails in the conversation by default without having to change the setting each time you open a new email?

The first option in the Thunderbird Conversations preferences should do exactly that.

> Is there a way to change the sorting order of conversations and save the setting to use by default? 

No, the emails are always sorted by date.

> Is there a way to get Thunderbird Conversations to work without creating a copy of the sent email in the inbox folder?

Yes, that just works for me. I do not remember what I set in the intiail setup though. Maybe just run the assistent again?

**Comment by js017** [comment]
Ok. Thank you. Have a good day.
 
-----Original Message-----

**Comment by protz** [comment]
@xi 's answers are correct. Thanks.
