### ISSUE TITLE
Proposal: Remove quick reply

### ISSUE THREAD

**Issue by xi** [protz/thunderbird-conversations#1177]
This is just a thought, and maybe it is not good at all. I just wanted to hear what other people think about this.

When looking through the open issues, I realized that a lot of them are related to quick reply. I do not myself use that feature and I feel that it is nice, but not essential this the add-on. Given that @protz has little time for maintenance, I propose to remove the quick reply feature completely. This would have some benefits:

- The overall complexity would be reduce, meaning less maintenence effort is required.
- Security issues due to the lacking enigmail integration would go away.
- Many issues would be obsolete.

What do you think about this?

**Comment by rnc** [comment]
While for myself I don't use it (and there is an item in the FAQ about disabling it : https://github.com/protz/thunderbird-conversations/wiki/Tips-and-tricks:-Disabling-the-%22Quick-Reply%22-feature ) I _bet_ that as soon as it is disabled people would complain ;-) Depending on what other developers think, would deprecation and disable-by-default be an initial option ?

**Comment by elioqoshi** [comment]
I use Quick Reply more than I use Normal Replies, so I'd hate for it to go away. Let's rather try to fix it and offer options to disable it, rather than completely removing it. Or we could separate it to another Add-On? "Quick Reply for Conversations"

**Comment by protz** [comment]
I also use it very much and I suspect other people do, too. I'd be interested in providing feedback on how to fix it...

**Comment by bevoorrading** [comment]
Considering I never use the Quick Reply and can get annoyed sometimes when I accidentally press it instead of the new-window-reply-button, I would appreciate an option to disable it more obvious than [the trick mentioned](https://github.com/protz/thunderbird-conversations/wiki/Tips-and-tricks:-Disabling-the-%22Quick-Reply%22-feature). But I enjoy Conversations way too much to make any kind of complaint for such a minor fuss.

**Comment by Fidelix** [comment]
I don't use it ever. It's buggy as hell (sorry to be so blunt but it's true) and doesn't support any kind of text styles.

It would be nice to at least have an option to remove it. Why was this issue closed?

**Comment by xi** [comment]
@Fidelix this issue is not about *disabeling* the feature. That is already possible. This issue was about *removing* the feature from the code completely in order to improve maintainability. The issue was closed because it was decided that the benefits outweigh the cost.

**Comment by Fidelix** [comment]
@xi thanks for the info.

How is it possible to disable the feature?
(without using an external, no-longer supported addon)
