### ISSUE TITLE
OSX Drag & Drop Attachments not working

### ISSUE THREAD

**Issue by NeoRey73** [protz/thunderbird-conversations#1181]
in OS X dragging attachment(s) from Thunderbird and dropping it to save it in Finder is not working with Conversations add-on installed

Mac OS X 10.11.6
TB 45.8.0

**Comment by protz** [comment]
This is a long-standing issue in Thunderbird, I think. https://bugzilla.mozilla.org/show_bug.cgi?id=377621

**Comment by philpav** [comment]
I have no problems to move attachments to Finder folders by drag & drop without this addon. 
It would be so great if this could be fixed.
