### ISSUE TITLE
Sent messages are no longer shown in the conversations view in Thunderbird 52

### ISSUE THREAD

**Issue by boris-petrov** [protz/thunderbird-conversations#1182]
Before, whenever a message was sent (and was in the `Sent` folder), it would show in my `Inbox` conversations view. Something has changed in Thunderbird 52 and this is no longer so for newly sent messages - i.e. I can see the old ones from before the upgrade but not the new ones I've sent after the update. Ideas?

**Comment by kumarpranay** [comment]
I upgraded to Thunderbird 52 (and still on 2.11.4 for the add-on). I have this setup on MacOS and Windows7 and on both I cannot see the conversations mails anymore. Emails that are in a thread on the folder email list view also do not group in the conversation in the message pane.

Anyone seeing the same issues?

**Comment by BelzebubsGrandson** [comment]
Hello guys,

I think I have found what is the issue after the 52 update, but we are still waiting on resolution. Please check issue I have opened named "[Indexing messages broken after Thunderbird 52 update](https://github.com/protz/thunderbird-conversations/issues/1184)" for more info. hope it helps.

Thanks,
Pavle

**Comment by protz** [comment]
This latter issue is now fix, about to issue a new release.

Thanks for reporting,

Jonathan
