### ISSUE TITLE
Unrelated Converstations grouping together

### ISSUE THREAD

**Issue by aformica** [protz/thunderbird-conversations#1183]
![thunderbird](https://cloud.githubusercontent.com/assets/27222141/24868302/a0216720-1ddd-11e7-8e1d-ad80dc6c4715.JPG)

**Comment by pianoslum** [comment]
See https://github.com/protz/thunderbird-conversations/wiki/What-is-threading

**Comment by protz** [comment]
Thanks @pianoslum
