### ISSUE TITLE
Scrollbar in list of mails stops working

### ISSUE THREAD

**Issue by Hi-Angel** [protz/thunderbird-conversations#1185]
Steps to reproduce:

1. Install the addon, use its default settings.
2. Restart Thunderbird.
3. Click with middle mouse button the scrollbar at the list of mails

*(alternatively, with the addon installed, reproducible by enabling/disabling the addon, and restarting)*

**Expected**: the list jumps to the point of the click, as it works without the addon.

**Actual**: Thunderbird opens a "Conversation Reader" window, as if not the scrollbar was clicked, but a selected mail.

Interestingly, this is the only scrollbar with the problem, i.e. all other scrollbars in the browser continue working as expected.

**Comment by protz** [comment]
Can you try the latest version from https://jonathan.protzenko.fr/thunderbird-conversations/ and let me know if it helps?

**Comment by Hi-Angel** [comment]
Yay, it works!

**Comment by Hi-Angel** [comment]
Thank you!

**Comment by protz** [comment]
Thanks for your patience.

**Comment by Hi-Angel** [comment]
No worries, I understand you work on the project in spare time ☺
