### ISSUE TITLE
Grey background on TB 52.1.1

### ISSUE THREAD

**Issue by phenix-factory** [protz/thunderbird-conversations#1191]
Hello,

Linux Mint just update my Thunderbird to 52.1.1

![a propos de mozilla thunderbird_021](https://cloud.githubusercontent.com/assets/1810149/26170259/0e07d456-3b41-11e7-85a2-a04b4eda4f6a.png)

With the stable release from Mozilla's website I got a medium grey background, with text on white.
I build a an XPI to do some testing.

![selection_022](https://cloud.githubusercontent.com/assets/1810149/26170578/3a90b76c-3b42-11e7-800d-c0948f3316b6.png)

Same problem.

Nice visual improvement by the way, when will it be released in the Mozilla's website ?

**Comment by kroka** [comment]
This might be related to #1159.

**Comment by phenix-factory** [comment]
Hello,
Maybe, i dont know.

I build an XPI from the repo https://github.com/fllp/thunderbird-conversations i still have the issue.

I m sad, because I can't live without conversation !

**Comment by sparusaurata** [comment]
Same problem, also with TB 52.1.1...
Any way to solve this?
![sans titre](https://cloud.githubusercontent.com/assets/17063513/26490319/1cb06128-420b-11e7-9e50-82b9bfad4b3d.png)

**Comment by protz** [comment]
Can you try https://github.com/protz/thunderbird-conversations/pull/1159 and tell me if that helps? If it doesn't help, then commenting on that pull request would be most helpful, with screenshots and more information about your system.

Thanks!

Jonathan

**Comment by irgendwie** [comment]
@protz #1159  works like a charm, at least for me

>% thunderbird -V
 Thunderbird 52.1.1

**Comment by fllp** [comment]
@phenix-factory: Just as a follow up: Did you build the XPI from the correct branch? It should be `tb-beta-fixes`.

**Comment by phenix-factory** [comment]
@fllp I didn't check the branch, so maybe it's wrong. I'll try !

**Comment by phenix-factory** [comment]
@fllp You are right ! I was on the wrong branch. You version solved my problem, thank you !

Maybe time to merge it ? :+1:

**Comment by fllp** [comment]
@phenix-factory: glad to hear!

> Maybe time to merge it ?

That depends. Maybe setting a fixed color isnt the best solution here, considering that different OS's might define a window background color than white for TB (or there's custom user definet color). This won't be picked up right now.  
But without a proper color keyword i dont see much alternatives.

What do you think @protz, @elioqoshi?

**Comment by protz** [comment]
This is tricky because users on Linux will want their theme's default 
background color to be honored. I don't remember why making the iframe's 
backgrounds transparent wasn't an option...

**Comment by fllp** [comment]
@protz: I got around to take a closer look at this.

The grayish message frame isn't truly transparent, it just gets the same colour as the surrounding containers. The responsible code is [`background-color: -moz-default-background-color`](https://github.com/protz/thunderbird-conversations/blob/master/skin/conversation.css#L183). Since the color keyword no longer inherits white but a greyish (at least for linux) color like seen below.  

**The problem**:  
AFAICS there is no way to change the white background of the iframe containing the message as its defined *inline* (iframe code by TB: `<body bgcolor="#FFFFFF" text="#000000">`).  
The color white itself theoretically could be changed in TB settings. For me, adjusting that setting only resulted in the custom color being shown until the actual message was loaded. After that, the white background was back.  
For Conversations, I tried overriding it via CSS but couldn't manage to do so. I guess you'd have to manipulate the DOM with JS code to make it work.

I can't test this on Windows and OS X but i strongly suspect TB to hard code white/ignore custom colors as background for the message body there as well.  
So, i suppose hardcoding the background of .message in Conversations would  be justifyable since in this particular matter TB doesn't care about native system colors either.

----

**TB's default message viewer**
![TB's default message viewer](https://user-images.githubusercontent.com/15898292/30006487-f90d86ae-90f9-11e7-86d0-3611aa59f0e5.png)

**Status quo: greyish frame**

![Status quo: greyish frame](https://user-images.githubusercontent.com/15898292/30006502-1a53f88e-90fa-11e7-9c72-354a4e13af36.png)

**Comment by fllp** [comment]
@elioqoshi: any thoughts on this from a designers perspective?

**Comment by protz** [comment]
Actually Thunderbird Conversations does change this, if I remember correctly:

https://github.com/protz/thunderbird-conversations/blob/master/modules/message.js#L1976

perhaps we just need to change these two lines?

**Comment by fllp** [comment]
> deal with people who have bad taste
love that comment :grin: also how Conversations is not opinionated in this matter.

Ok, so here is how it looks if i change the background line to 
`let fg = Prefs.getChar("browser.display.background_color");` 

![Set background color to foreground](https://user-images.githubusercontent.com/15898292/30082991-0e60f8bc-928d-11e7-8c7d-fbc9aba492f0.png)
(my taste is allright, the green is just for testing purposes :wink:)

So the problem remains, only now at least custom colors are respected. But i think these could be injected into the message-wrapper?

Oddly enough, i get the same result if i change the following line (1977) to this: `let bg = Prefs.getChar("browser.display.foreground_color")`. Im not really savvy with JS though.

**Comment by protz** [comment]
perhaps what needs to happen is:
- run `getComputedStyle` on the outer conversation HTML document to get the body's background color and foreground color
- then, use these instead of the prefs for setting the background/foreground

what do you think?

**Comment by fllp** [comment]
i see, didn't know about getComputedStyle.
well it sounds fine to me.
but it would mean that custom color settings of users would be
disregarded, right?

if that should be avoided, how about setting the color of the outer HTML
to the color set by the user? by default, this should be white. So in
effect this should look the same as @elioqoshi's designs.
And if a user sets any different color, the wrapping HTML and the
message's iframe would both get that same color. However ugly and
against the design that color may go, it would at least display as one
solid block.

**Comment by protz** [comment]
That seems good and consistent to me!

**Comment by protz** [comment]
(if we can get things to work this way, of course)

**Comment by joh** [comment]
Any quick workaround for this? One that doesn't require rebuilding the extension?

**Comment by fllp** [comment]
@protz: Sorry for the late response. Unfortunately right now I lack the JS skills and predominantly the time to do this. Maybe @Standard8 or someone else could pick this up?

@joh: You could try to overwrite the respective CSS with a userchrome.css in your profile directory. The necessary changes are here 9c6e9e4c21189932a2d727633676b9a1388da8d0 and here 192836d1936071fc19e884d4796ece062fbad54d. Haven't tried if that works though.

**Comment by trustin** [comment]
Tried putting `chrome/userChrome.css` to the profile directory but I still see the gray background. Anyone succeeded?

**Comment by rocky7x** [comment]
Solution with Stylish in #1196 works fine for me.

**Comment by trustin** [comment]
@rocky7x Stylish seems incompatible with Thunderbird accodring to addons.mozilla.org. Is there any workaround?

**Comment by rocky7x** [comment]
Check this page: https://addons.mozilla.org/en-US/firefox/addon/stylish/versions/

And download version 2.1.1 - it works with TB 52.4

**Comment by VinTz1** [comment]
This solution is just a fast workaround, but at least I do not hardcode the colors. I think changing the colors in the settings should not be allowed.

**Comment by kroka** [comment]
@trustin The following `chrome/userChrome.css` works for me:
```
.message,
.quickReply .textarea {
        background-color: #fff !important;
}
```
For the quick-reply area I had to set the color to `.textarea` instead of `.textWrap` as in 298a95de9fcfc3b55de61fa3b5f83b170a2a9379

**Comment by Standard8** [comment]
I don't think we've had any reports of this in Thunderbird 60, so closing out. If it is still happening, please check in Thunderbird 68 when it is released with the latest version of conversations.
