### ISSUE TITLE
Keystroke Ctrl-A is interpreted as A  in preview panel

### ISSUE THREAD

**Issue by isthisausername** [protz/thunderbird-conversations#1195]
System W7
Thunderbird 52.1.1 (32)
Thunderbird Conversations 2.11.4

<Ctrl-A> (select all) in the preview-panel of the actual mail is interpreted as <A> (archive). Of course the focus is on the content of the preview-panel.
Please check and repair
If you have further questions do no hesitate to contacting me
Cheers

**Comment by protz** [comment]
Looks like an actual bug and relatively easy to fix... thanks
