### ISSUE TITLE
Re-opens closed message pane

### ISSUE THREAD

**Issue by ryantate** [protz/thunderbird-conversations#1206]
I prefer to turn off the Message Pane in Thunderbird, so my inbox is simply a list of messages, and I double click to open a message. This works fine with Thunderbird Conversations EXCEPT after I open a thread (double clicking to open a new window), it always re-opens the Message Pane for some reason. I can close the Message Pane again but this is annoying and obviously unworkable.

Experienced this using 	201706111612-master.xpi on Thunderbird 52.1.0.

**Comment by Standard8** [comment]
I just tried this and it is working fine for me with the latest version of Thunderbird & Conversations. I guess we could have somehow fixed it in the last couple of years.
