### ISSUE TITLE
Own messages (incl. replies/forwards) not displayed in conversation anymore (TB 52)

### ISSUE THREAD

**Issue by scheinercc** [protz/thunderbird-conversations#1207]
I realised that since the update to 54.0b3 (macOS) my own messages (incl. replies/forwards) are not displayed within conversation lists anymore.

**Comment by wotis** [comment]
Not only in 54 beta, also with official Version 52.2.1

**Comment by DanStevens** [comment]
I've notice this too. Is this due to a change in Thunderbird or a change in Conversations?

**Comment by DanStevens** [comment]
I don't think it can be a chance in Conversations because this add-on hasn't had a new version since May 2016 (is it still in active development). Yet I tried downgrading Thunderbird to as low as version 45.8.0 but I still can't get this functionality back.

**Comment by wotis** [comment]
Yes, I also tried to reindex the mails, but my own messages still do not appear in conversation-view.

**Comment by DanStevens** [comment]
I've not retried reindexing. How is this done?

**Comment by wotis** [comment]
Just go into the addon-settings and start the installation assistant again.

**Comment by jfml** [comment]
I did do a reindexing and the problem persists : (

**Comment by Standard8** [comment]
This is a duplicate of #1184 - we've landed the fix in the repository, but we're waiting for a new release to be published. Hopefully will happen soon.
