### ISSUE TITLE
Possible issue with email indexing and Conversations.

### ISSUE THREAD

**Issue by escarti** [protz/thunderbird-conversations#1208]
Thunderbird: 52.2.1 under MacOS Sierra 10.12.5

Error: 
1. I noticed that my latest mails do not appear if I search for them.
2. I deleted the index sql to have Thunderbird rebuild it but it did not rebuild it.
3. I disabled Conversations and Thunderbird was then able to rebuild the database.
4. I re-enabled Conversations and the new emails are not being properly indexed anymore.

Conclusion:
I think Conversations is preventing indexing. I disabled it now. I think this should be looked into.

**Comment by Standard8** [comment]
This is the same as #1184, we're hoping to have a fix released soon.
