### ISSUE TITLE
Focus stolen on message open

### ISSUE THREAD

**Issue by Nesetalis** [protz/thunderbird-conversations#1209]
This behavior changed within the past few days. 
It used to be, I click on a message (LMB) in the list, and then click the delete key on my keyboard. Now, I click on a message, and the focus goes to the message, and delete key does nothing. I have to again click in the list pane to re-select the message before I can delete it.
Moving up and down with keyboard arrows also loses focus. This is a usability nightmare for managing 1000+ messages every day. If I am in the list pane, I obviously want to use the list pane, not the message pane! 
My extensions: Enigmail, Manually sort folders, and MinimizeToTray revived (MinTrayR)
Version: 52.2.1 (32-bit)

**Comment by Nesetalis** [comment]
An update. The bug went away randomly a few days later.

**Comment by Standard8** [comment]
Not sure what caused this, but I'll close this out, seeing as we don't seem to have other reports and it has gone away.
