### ISSUE TITLE
Contact picture URI not escaped correctly

### ISSUE THREAD

**Issue by chrisnig** [protz/thunderbird-conversations#1211]
In content/stub.xhtml:804, the contact picture URI is output. However, it is possible that this string contains a path to a local file which can contain backslashes on a Windows machine. These backslashes are not escaped, resulting in an invalid path and the contact picture can not be found.

The backslashes in the path should be escaped or replaced by forward slashes. I am not too familiar with the code of the extension, so I am unsure where this should be done. From having a first look, my guess would be that it could either be done in content/stub.xhtml:804 (place where this is output) or in modules/contact.js:411 (place where the getter is defined) or modules/message.js:489 (place where the contact is transformed into template data; imho this is the right place for the transformation).

**Comment by Standard8** [comment]
I believe with the recent rewrite in React, that this should hopefully no longer be an issue in the latest Thunderbird 68 / Conversations 3.0.16. If it is, please feel free to re-open or let us know.
