### ISSUE TITLE
This program made my fonts too small and pretty much messed up my file structure.

### ISSUE THREAD

**Issue by gh233** [protz/thunderbird-conversations#1214]
I am using Thunderbird 52 and installed this software hoping it would improve my email conversations view. It took a long time to do it's upkeep and I went on a walk and shopping while waiting.  Software said that the changes are  reversible, that "all you have to do is uninstall the add-on" and things would be fine. I have now uninstalled the software and guess what. Still the same old jumbled up mess.  I must admit I didn't know what I was doing in installing this, maybe this was the wrong version? I really like thunderbird--it crashes so less often than Outlook did. Outlook crashed every day, with great regularity and I won't use a browser for my email. I suppose I could unin/reinstall Thunderbird but my contacts would have to be migrated and I have invested time getting the settings just so...

**Comment by Standard8** [comment]
Without seeing a screenshot it is hard to say. I would suggest going to View -> Layout -> All, and that'll probably reset to the view you like.

**Comment by gh233** [comment]
I ended up having to reinstall thunderbird. Maybe I should take the post down?
