### ISSUE TITLE
Wiki Links to Nonexistent "Thunderbird Contacts" Link

### ISSUE THREAD

**Issue by nicholashead** [protz/thunderbird-conversations#1218]
https://github.com/protz/thunderbird-conversations/wiki links to an addon called "Thunderbird Contacts", but it either doesn't exist anymore - or is a bad/old URL that needs updating.

**Comment by Standard8** [comment]
Thanks, I've just removed the reference - I think it was an old add-on that was a labs experiment & not running any more.
