### ISSUE TITLE
Conversations breaks indexer: JS error

### ISSUE THREAD

**Issue by exteon** [protz/thunderbird-conversations#1219]
Hi,
Lately this error occurs for me when turning on Conversations:

```
TypeError: this.activeIterator.return is not a function indexer.js:897:7

pop: function gloda_index_callbackhandle_pop() {
     this.activeIterator.return();
```

This breaks indexing (it gets stuck at "Determining which messages to index in Sent".

**Comment by arty-name** [comment]
I guess it’s a duplicate of #1184

**Comment by Standard8** [comment]
Yep, duplicate of #1184
