### ISSUE TITLE
Change title in pref for "Toolbar buttons"

### ISSUE THREAD

**Issue by wolftune** [protz/thunderbird-conversations#1225]
I was searching forever for how to make delete actually delete both received and sent emails in a conversation (and I'm frustrated about years of undeleted sent emails up to now).

The preferences say "Toolbar buttons" as the title, and only reading the fine text makes it clear this is not about having buttons or not, this is about their behavior… some better title would be good. At least something like "Toolbar button behavior" or "Archive/delete behavior"

**Comment by protz** [comment]
Sure, can you submit a pull request?

**Comment by wolftune** [comment]
Sure, but do you prefer "Toolbar button behavior" or "Archive/delete behavior" or something else? I think I lean toward the latter of my two suggestions.

**Comment by protz** [comment]
The latter seems good!
