### ISSUE TITLE
"Expand Keysettings" shows key settings twice

### ISSUE THREAD

**Issue by blerner** [protz/thunderbird-conversations#1229]
Not quite sure when this happened, but I noticed it this morning after the latest update to 2.13.2.  In the options page for the extension, clicking on Expand Keysettings shows all the key settings, the "Create new hotkey" and "Restore default keysettings" buttons...and then shows everything a second time.  I haven't clicked around to see whether all the buttons and their doppelgangers are functional or not, but it does seem odd...

**Comment by Standard8** [comment]
I don't see this on my Mac.

Did you look at the setting straight after the update? Did you restart in-between?

**Comment by blerner** [comment]
I'm not sure.  I must've restarted since then, though, and now I don't see it.  However, right now, if I disable TBConv and re-enable it once, I see the hotkeys config appear twice.  If I disable and re-enable it again, when I go to expand the hotkeys config section I get an alert saying "Another window is already editing hotkeys.  Please use that window instead."  I then need to restart Thunderbird to reset TBConv to a clean slate.  I'm guessing maybe something isn't being unloaded properly when TBConv shuts down?

**Comment by Standard8** [comment]
We've removed the key settings from the latest version and the latest master, since they weren't used a terrible amount, had broken, and were complex. Hence, closing this out.

**Comment by blerner** [comment]
Bummer; I did like that ability :(

**Comment by Standard8** [comment]
There's a chance we'd bring something like it back once we finish our big rewrites. However, it'd need a good value proposition, and to be simple.
