### ISSUE TITLE
Reply option gone since newest update

### ISSUE THREAD

**Issue by fdellwing** [protz/thunderbird-conversations#1233]
* **Thunderbird version:** `52.2.1 (64-Bit)`
* **Thunderbird Conversation version:** `2.12.2`
* **Operating System:** `Linux dellwing 4.4.0-93-generic #116~14.04.1-Ubuntu SMP Mon Aug 14 16:07:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

**What did you do?**

I updated the addon.

**What did you expect to happen?**

That there will be a "reply" option in the headline of the mail, like before the update.

**What actually happened?**

There is none.

![conversations](https://user-images.githubusercontent.com/22813377/30063995-c2a441a4-9250-11e7-8d78-6199cf4165b1.png)

**Comment by protz** [comment]
Are you noticing anything in the Error Console? (in the tools menu)

It might be a good idea to clear it first then load the faulty email

Thanks,

Jonathan

**Comment by fdellwing** [comment]
The next day it works fine again. So it seems to be only a problem with a freshly upgraded conversations version.
