### ISSUE TITLE
Use OpenStreetMap links as alternative to Google Maps

### ISSUE THREAD

**Issue by karussell** [protz/thunderbird-conversations#1234]
I always used your plugin and it works smoothly :)

I recently discovered that an address is automatically linked to Google Maps. I know now that I can disable this, but I would like to configure an open alternative like OpenStreetMap :)

My TB version is 52.2.1 and the conversations plugin is at 2.13.2

**Comment by protz** [comment]
Yes! That seems like a good idea. I'd happily take a patch or a pull 
request.

**Comment by Standard8** [comment]
I don't think we have map support in the add-on any more. Thunderbird has it - if so, a bug should be filed with them to ask that to be changed.
