### ISSUE TITLE
signed email is not displayed when using enigmail 1.9.8.2

### ISSUE THREAD

**Issue by obama** [protz/thunderbird-conversations#1240]
* **Thunderbird version:** 52.3.0 32bit
* **Thunderbird Conversation version:** 2.13.2
* **Operating System:** Windows 10

**What did you do?** open a signed email

**What did you expect to happen?** see the email

**What actually happened?** a empty email

**Comment by Standard8** [comment]
Are there any messages on the Error Console when you open the email? (Tools -> Developer Tools menu option).

Also, have you reported this to Engimail?

**Comment by obama** [comment]
there is only this:
`unreachable code after return statement[Weitere Informationen]  jquery.tokeninput.js:470:4`

no i have not reported it to the enigmail

**Comment by protz** [comment]
@shirosaki is the author of this code and may have a clue :)

**Comment by unixforever** [comment]
So am I. Encrypted messages are not showing properly as well.

**Comment by MartB** [comment]
can confirm the bug with S/MIME signed messages.
I found a workaround though.

Enable "I Love attachments" and download the View All Bodyparts addon it will render the "broken" messages after that.

**Comment by Standard8** [comment]
I've now created a new developer release with @shirosaki's fix in it. If people can test it out, that would be great. I'll release it fully in a week or so if there's no issues raised.

To get the developer version, visit https://addons.mozilla.org/en-US/thunderbird/addon/gmail-conversation-view/#beta-channel and go to the "Developer channel" near the bottom of the page.

You can download it there, and then install it into Thunderbird.

**Comment by obama** [comment]
seems to work for me! just that there is an "undefined" button in the green field where the signature is verified.

**Comment by MartB** [comment]
I built myself a version and it worked with his fix so i guess its alright.
