### ISSUE TITLE
Sent Messages Not Showing

### ISSUE THREAD

**Issue by thescotthughes** [protz/thunderbird-conversations#1241]
I am still not seeing most sent messages in conversation view.

I tried both the development version and the 2017-09-05 release (201709051426-2.13+.xpi). Neither worked.

* **Thunderbird 52.3.0**
* **Conversations version: 2.13.2**
* **Operating System: Windows**

**Comment by Standard8** [comment]
On one of the other threads, it was suggested to:

* Shut down Thunderbird
* Remove global-messages-db.sqlite from your [profile](https://support.mozilla.org/kb/profiles-where-thunderbird-stores-user-data)
* Start up Thunderbird and let it re-index your messages (this might take a while).

**Comment by gebauer** [comment]
Well I hade the same issue.
Removing global-messages-db.sqlite did not help, but directed me into the right direction!
For some reason indexing of all my "sent"-folders were switched off. I personally did not do that!

You find the setting in the right-click menu of your sent folder under properties, first tab, first checkbox.

Afterwards everything worked fine again.

Best,
Jan

**Comment by Standard8** [comment]
@thescotthughes can you try checking the status of your folders like gebauer did?

**Comment by Luklek** [comment]
I had the same problem (with latest Thunderbird and Conversations).
Deleting global-messages-db.sqlite fixed it for me.

**Comment by Standard8** [comment]
Not quite sure what was happening here, maybe the global database was corrupt or something. Not had more reports of it, so closing this out.

**Comment by andypillip** [comment]
I had to "repear the .msf file", which was also an option in the sent-folder's properties dialogue.
