### ISSUE TITLE
Expand all messages not working properly with latest enigmail

### ISSUE THREAD

**Issue by unixforever** [protz/thunderbird-conversations#1242]
* **Thunderbird version:** 52.3.0
* **Thunderbird Conversation version:** 2.13.2(latest)
* **Operating System:** macOS

**What did you do?** I opened the enigmail-pgp encrypted conversation, and clicked 'Expand all messages'.

**What did you expect to happen?** I expected all messages to just expanded and show me all contents.

**What actually happened?** All messages expanded, but most of them was jus blank without any content.

Additionally, it doesn't work even if I just expand messages one by one. Also, there is no problem in non-encrypted(it means, not related to enigmail plugin) conversations.

**Comment by Standard8** [comment]
Looks like this is a duplicate of #1240

**Comment by unixforever** [comment]
Sorry!
