### ISSUE TITLE
Indexing still freezes

### ISSUE THREAD

**Issue by mitra42** [protz/thunderbird-conversations#1251]
* **Thunderbird version:**  56.0b4
* **Thunderbird Conversation version:** 2.13.3
* **Operating System:** High Sierra (fully updated)

I'm seeing the problem in https://github.com/protz/thunderbird-conversations/issues/1184  still - and it persists even if I disable Conversations, Quit, remove global-messages-db.sqlite and restart. I only started using Conversations again recently after many years not using it (its missing too many important TB features) so I'm almost certain this is correlates with indexing stopping.  Let me know if you want me to test anything.

**Comment by Standard8** [comment]
There's been quite a few changes to the add-on recently, although fundamentally, if there's a problem with the indexing, then really it is Thunderbird's issue, as Conversations doesn't do much with it.

If this is still an issue in the latest Thunderbird 68 & Conversations 3.0.16 then please feel free to reopen or file a Thunderbird issue. Having more details about what is happening would be useful as well, e.g. what are the CPUs doing, what does "freeze" actually mean, any messages on the error console, etc.
