### ISSUE TITLE
tag bubbles only show for incoming and not sent emails

### ISSUE THREAD

**Issue by wolftune** [protz/thunderbird-conversations#1252]
This seems somewhat related to #1025 which I also would very much like.

* **Thunderbird version:** Thunderbird 52.4.0
* **Thunderbird Conversation version:** 2.13.3
* **Operating System:** KDE Neon (Ubuntu 16.04)

**What did you do?**

I tagged one of my sent emails in a conversation. Later, I searched by that tag and saw the whole conversation with a highlight of that one email.

**What did you expect to happen?**

I expected to see the tag when I clicked on that email.

**What actually happened?**

I see no tag when viewing that email, just the color highlight in the conversation view.

Elsewhere, I see tags and conversation color highlights both, but only for incoming emails. I can't see the tag bubble with the x to remove it etc. if I'm looking at a sent email.

**Comment by wolftune** [comment]
update: I found an exception. Maybe this bug only happens for replies and not conversations that were *started* by a sent mail…

**Comment by wolftune** [comment]
I got the issue with a thread I started.

Another bit of clarity: I could use the keyboard shortcut to actually tag my own sent mail. But if I use a contextual menu, it doesn't matter if I click my own mail, it *only* will tag incoming mail.

**Comment by Standard8** [comment]
I've created a new issue for the context menu - #1449 - so that there's a nice clean issue.

I've also noticed that using the keyboard shortcut to tag older mail in a thread has stopped working, so I've filed #1450 for that.
