### ISSUE TITLE
Conversations doesn't work with latest Thunderbird (60)

### ISSUE THREAD

**Issue by Standard8** [protz/thunderbird-conversations#1255]
* **Thunderbird version:** 59.0a1
* **Thunderbird Conversation version:** 2.13.4pre
* **Operating System:** Mac

**What did you do?** Tested in latest daily

**What did you expect to happen?** Conversations to work

**What actually happened?** It didn't work, errors on the console:

NS_NOINTERFACE: Component returned failure code: 0x80004002 (NS_NOINTERFACE) [nsIPrefBranch.getComplexValue]

**Comment by koolx** [comment]
Conversations dont evenm work in the latest standard TB 52.5.

**Comment by Standard8** [comment]
@koolx Please can you file that as a separate issue, and describe what exactly you are seeing. Commenting on an existing unrelated issue is not helpful.

**Comment by koolx** [comment]
How is it an unrelated when my issue is the same as yours that TC dont work on the current version of TB?

**Comment by Standard8** [comment]
@koolx You mentioned Thunderbird 52, I mentioned Thunderbird 59 - they are very different and 59 is newer and has had more development than 52 (and 59 is a pre-release version) so it isn't surprising that TC might not work with the latest pre-release version.

Also, my first comment is listing a specific message that is occurring in the console (Tools -> Developer Toolbox -> Error Console), I very much doubt you are seeing that, or have even checked that (in this case, I know it is only going to happen in TB 58 & later as that's where the interface was removed).

I also can expect that TC is working fine for most of its users in 52, as we haven't been getting reports of issues. Therefore I suspect this is something else, and hence we need full details in a separate issue please.

**Comment by koolx** [comment]
ok

**Comment by rnc** [comment]
@koolx @Standard8  I run 52.4.0 on Fedora 27 without issues.I downloaded a 52.5.0 and it starts up fine with Conversations functioning as normal.

**Comment by koolx** [comment]
ok

**Comment by koolx** [comment]
e

**Comment by koolx** [comment]
@rnc Heres the problem:

I got 2 accounts in TB. When I send email from account A to B I get a notification in B's inbox that I got it. I then reply from account B and I get a notification in inbox A that I got it. But when I reply to account B, I dont get a reply NOR a notification in B's inbox. Whats even stranger is that the email and notification end up in account A's inbox, not B's. 

This error goes away when I disable Conversations.

This is a bug. Please try it on your end if you got more than one account set up. Conversely, I can generate and send you an error log, if possible. 

Let me know.

**Comment by fllp** [comment]
The same is true for the current beta. I get the same `NS_NOINTERFACE` for 58.0b3.

**Comment by pmbrandao** [comment]
With:
- Thunderbird version: 59.0b1
- Thunderbird Conversation version: 2.13.4 (from the AMO)
- Enigmail Version: 2.0a2pre
- Operating System: Windows 8.1

When I enable Conversations I get:
`String.trim is deprecated; use String.prototype.trim instead[Learn More]  prefs.js:80:15
String.toLowerCase is deprecated; use String.prototype.toLowerCase instead[Learn More]  prefs.js:80:15
TypeError: setting getter-only property "spec"[Learn More]  protocolHandler.jsm:62:5
Security Error: Content at moz-nullprincipal:{fd1d2826-92cc-4f61-a802-42f537e62139} may not load or link to chrome://conversations/content/assistant/assistant.xhtml.`
Closing the assistant and then selecting a message gives:
`TypeError: w.messageHeaderSink.enigmailPrepSecurityInfo is not a function[Learn More]  enigmail.js:176:5
Security Error: Content at moz-nullprincipal:{fd1d2826-92cc-4f61-a802-42f537e62139} may not load or link to chrome://conversations/content/stub.xhtml.
unreachable code after return statement[Learn More]  jquery.tokeninput.js:470:4`
And the message windows just states 

> Loading...
> Forward this conversation – Print this conversation

Seems some security constraints have been raised up on TB 59??
Currently I disabled Conversations to being able to see messages.

Best and thank you for a very valuable addon.

**Comment by Standard8** [comment]
Update for this:

- 'master' is now becoming the version that will support TB 60 & beyond. It looks like it'll be too much work to support pre-60 versions, so we'll be dropping those.
- There's been some work on master to fix compatibility, however at the moment, message views & preferences don't work.
- I have a patch in progress for preferences, though it'll likely take a while to complete, as it is basically a rewrite of the code & port to html.
- Message views I'm not quite sure what's up yet, I'm asking @protz for help. It could be the security error, but I'm not 100% sure if that's right or just a bogus error.

At the moment, master isn't worth playing with until we can find a solution for the message views.

**Comment by Standard8** [comment]
I've just pushed a couple of new patches to master. They still don't fix the message preview window, but we do now get further.

Currently to get the message preview window to largely work, I have to add `document.allowUnsafeHTML = true` to stub.xhtml. That's due to some changes in gecko for various reasons, I'll have to work out what to do about those.

**Comment by koolx** [comment]
I currently have 2.13.4. So is there an update already?

**Comment by Standard8** [comment]
Just found this: https://bugzilla.mozilla.org/show_bug.cgi?id=1450315#c8 and https://bugzilla.mozilla.org/show_bug.cgi?id=1433871#c14.  So we need to move away from jQuery, I think the intermediate step might be to allowUnsafeHTML, then do the larger work for rewriting.

**Comment by MartinX3** [comment]
16. May 2018 >>>> Thunderbird v60 ESR <<<< will arrive

**Comment by Standard8** [comment]
@MartinX3 I think we know that. If you want to help, we can provide you with things that need fixing. If you don't want to help, please be quiet and stop spamming us and putting us under more pressure than necessary.

This is a spare time project for me, I don't have to do it, I do it because I want to.

**Comment by MartinX3** [comment]
@Standard8 
Read the definition of spam (I didn't spam...), and don't write in an angry way.

I only wanted to give a helpful hint about the official release of the WebExtension Thunderbird.

**Comment by koolx** [comment]
Will there be a new update to Coversations? I currently have version 2.13.4... T\hanks.

**Comment by fllp** [comment]
I am not a mantainer of this project, so please excuse me if I'm jumping the gun here...
---
@koolx:  
Given your previous comments and way of communicating here on GitHub, I would like to suggest a few reads that should hopefully help *you* getting satisfactory answers and help and spare *developers* unnecessary annoyances in the future. This is *not meant to be personal* but intended to help.

[First read](http://catb.org/~esr/faqs/smart-questions.html#intro)  
[Second read](http://catb.org/~esr/faqs/smart-questions.html#prune)
[(important) Third read](http://catb.org/~esr/faqs/smart-questions.html#urgent)  
and a nice addition: [fourth read](http://catb.org/~esr/faqs/smart-questions.html#courtesy)

**Comment by koolx** [comment]
@flip,

I can respect that. This seems like a dev site not a forum as someone suggested before, which to an extent I kinda dont agree. But whatever the case, where can I ask questions about updates if my question is not warranted here since there's no other way that I know of to find that info?

**Comment by Standard8** [comment]
Ok folks, let me spell it out. As per my previous comments in this issue, we are working towards a new version. I have been doing most of the work, and it is in my SPARE time. Which I don't have much off.

Repeatedly asking if there's going to be a new version, or prompting when the next version of Thunderbird is going to be out DOES NOT HELP. Especially when we're ALREADY commenting there IS [WORK](https://github.com/protz/thunderbird-conversations/issues/1255#issuecomment-378159460) IN [PROGRESS](https://github.com/protz/thunderbird-conversations/issues/1255#issuecomment-379575588).

We've already looked at the fact this is broken on the beta releases, so why wouldn't we have looked at or got some sense of the date for when the next Thunderbird gets released?

Yes, there will be a new version for Thunderbird 60.x, no, I currently have no idea if it will be before or after 60 is released (nor do I know how long it will be afterwards). It depends on what time I have available, it may happen quicker if other people help.

I would LOVE for more people to help, and I would LOVE to work with them. That's why I commented on the progress in the first place. That's why there are helpwanted bugs.

Money is not a factor. I have a full time job, I have children and a house on which we're doing lots of work. When I do work on conversations, it is because I choose to, because I want to, because I like the interface it gives me in Thunderbird & I find it useful. I do work on it when I feel like it.

Yes, I do get annoyed when people are asking if/when an obviously in progress new version is going to be released, or prompting on dates, because it feels to me like you are demanding that I do something for you.

This is a choice, not a job. Just like for many open source developers.

And now this is another 15 mins I've spent responding, when I could have been working, doing other things, or actually doing something towards the next version of conversations.

**Comment by Standard8** [comment]
I've just eventually found time to sort out the preferences to work with TB 60. The styling isn't great, and the key mappings are hidden for now (they need more work), but you can at least set preferences correctly now. I also reworked the descriptions to tooltips, again not quite as ideal, but the best I could do for now based on available time.

I also fixed another minor issue.

Next up is to fix "SimpleStorage" which will hopefully get us close to the end.

**Comment by Standard8** [comment]
Just discovered an issue. When trying to use the inline send, it fails. I'm seeing:

```
TypeError: msgDate.toLocaleFormat is not a function
getArchiveFolderUriFor resource://conversations/modules/stdlib/send.js:75:25
	sendMessage resource://conversations/modules/stdlib/send.js:314:21
	send chrome://conversations/content/stub.compose-ui.js:799:12
	onclick chrome://conversations/content/stub.xhtml:1:1
```

Suspect that's another old API that needs replacing.

**Comment by Standard8** [comment]
I believe I've now fixed the inline send in the update I've just pushed (to [stdlib](https://github.com/protz/thunderbird-stdlib/pull/22), then updated here).

**Comment by Standard8** [comment]
I've also just reverted an incorrect change from earlier - I'd miss-understood the docs, and it was breaking undoing the monkey patching (something that happens on uninstall or upgrade).

Hopefully we should be in a much better state now.

**Comment by DerXteMensch** [comment]
Any news? :) Can it already somehow be used with tb60 beta?

**Comment by MartinX3** [comment]
TB V60 will probably released after the 24.07.2018

https://wiki.mozilla.org/Thunderbird/StatusMeetings/2018-07-10

They fixed almost all release preventing bugs with Beta 10

**Comment by Standard8** [comment]
Good news! 2.14.1 has just been approved and is now available from https://addons.thunderbird.net/thunderbird/addon/gmail-conversation-view/

If you find any issues please file them as new issues.

**Comment by MartinX3** [comment]
https://wiki.mozilla.org/Thunderbird/StatusMeetings/2018-07-24#Version_60
Nice, the v60 RC3 build is also finish.
They will release it as soon as possible as the "Provider for Google Calendar" addon bug got fixed.
