### ISSUE TITLE
Sender icons/thumbnails should be optional

### ISSUE THREAD

**Issue by marszysz** [protz/thunderbird-conversations#1256]
The feature of sender thumbnails (which are mostly icons of 2 letters on a coloured background in my case) should really be optional. There should be a switch in the settings pane which would allow to disable this - ideally only when there is no real thumbnail, but for me the complete disabling would be OK. Those icons are really distracting for me in the context of Thunderbird.

**Comment by Standard8** [comment]
At this moment in time, I don't want to add more complexity with lots of options. This is the only complaint I've heard about it in the last couple of years so closing it out.
