### ISSUE TITLE
Saving of quick replies is broken

### ISSUE THREAD

**Issue by Standard8** [protz/thunderbird-conversations#1257]
As noted by @cyberDrake in #1100, saving drafts in the quick reply window isn't working.

I started looking at it, and it is this change that has broken it: https://github.com/protz/thunderbird-stdlib/pull/17/files#diff-29b2b38439805dfd0ffa1c6895840b35R128

It looks like the generators need to be handled differently (I can't remember why I specifically used that bit of code there).

**Comment by symbolisch1234** [comment]
could you, until this is resolved, please just add an option to not show the quick reply window, instead open replies in the new message window? 

i just lost a really long email to this. disabling the plugin for now. really like it, really want it back, but eating my emails is a **total dealbreaker**.

**Comment by rnc** [comment]
https://github.com/protz/thunderbird-conversations/wiki/Tips-and-tricks:-Disabling-the-%22Quick-Reply%22-feature

**Comment by smu55** [comment]
Just had the same problem with loosing emails and wanted do disable quick replys. But beware that the newest stylish verson ist not compatible with thunderbird. It will not appear in the thunderbird extensions either. You have to open the stylisch page manually, search for an older compatible version from the version history and sideload it.

**Comment by jfml** [comment]
Stylish 2.1.1 seems to work for me (TB 52.8.0 ): https://addons.mozilla.org/en-US/android/addon/stylish/versions/2.1.1 Thanks @rnc & @smu55!

**Comment by Standard8** [comment]
I believe this should all be fixed in the new version we're developing for Thunderbird 60 (in beta). It is currently only available if you build it on this repository from master. We're testing it out and hopefully going to release it soon.

**Comment by jfml** [comment]
@Standard8 That's amazing! Thanks for the good work! ^__^

**Comment by cyberDrake** [comment]
I am very much looking forward to the fix! Thanks for the hard work.

**Comment by Standard8** [comment]
Thunderbird 60 is out now, and we've released the 2.14.x series that goes with it. I believe this is fixed now, so closing. If there are still problems, please file them as new issues.
