### ISSUE TITLE
How can I add a bzapi URL?

### ISSUE THREAD

**Issue by cleeland** [protz/thunderbird-conversations#1258]
I have an internal-only bugzilla instance available with a bzapi.  How can I get conversations to "know" about it so I can take advantage of bugzilla goodness?

**Comment by Standard8** [comment]
I don't think there is a way at the moment, we'd probably accept a patch to add to the list via a pref.

**Comment by cleeland** [comment]
thanks for the feedback.  I'd totally forgotten about this.  I'll take a look at hacking up a first-cut at a patch.

**Comment by cleeland** [comment]
Got something cobbled together that's ugly at https://github.com/cleeland/thunderbird-conversations/tree/issue/1258_bzurlprefs but is untested.  As this is my first foray into any kind of JS development or mozilla development it might take me a bit of time to put together a dev/test environment.

**Comment by Standard8** [comment]
Bugzilla integration is going to be dropped soon as it is quite complex and we suspect it is little used. Hence closing out.
