### ISSUE TITLE
[Feature Request] - New Message list

### ISSUE THREAD

**Issue by LeonardoDG2084** [protz/thunderbird-conversations#1259]
Hi, I loved this extension, it is so perfect!, 

Just a question, there is plans to create a new message list concept, like 2 lines message view as outlook does?

Thanks and congrats for your project!!!

**Comment by Standard8** [comment]
Do you mean in the message list at the top? If so, I think that is unlikely as it really needs Thunderbird core to do it.

**Comment by Standard8** [comment]
Assuming this is the message list at the top. If so, then we're not likely to be able to do that easily. There is a Thunderbird bug on it somewhere.
