### ISSUE TITLE
Utilize BountySource so that we can pay to prioritize issues and development

### ISSUE THREAD

**Issue by abomi** [protz/thunderbird-conversations#1260]
I would like to donate to the project, especially, if it will mean more active development.

**Comment by Standard8** [comment]
This is up to @protz.

**Comment by protz** [comment]
Hello,

First of all, thanks for suggesting this. I'm really happy that users would be ready to pay for an addon that I wrote!

Unfortunately, the problem lately hasn't been income, but rather time. I tend to be fairly busy during the week and I must say I've found it hard to spend yet more time in front of the computer on the weekends. Hence, the slow pace of development.

I sadly don't think a monetary incentive would help, in this case, so I feel compelled to decline -- it would be dishonest to pretend I'll develop more if you give me money.

If you have any sort of skills, though, contributions are the most effective way; sorting issues on the bugtracker, helping out other fellow users, or even contributing code...

Thanks!

Jonathan

**Comment by protz** [comment]
(I would like to add that if @Standard8 is interested, though, I'd would totally be up for this, assuming the money is directed towards him, rather than myself.)

**Comment by Standard8** [comment]
I'm not interested either, like @protz, this is a spare time thing for me, especially as I use it so much. I'd rather have more people helping us keep it going by contributing.

**Comment by pianoslum** [comment]
Still, there's bountysource and the like. If anyone offered rewards for specific bugs, new developers might become aware of the project.

Btw, there's already an open bounty for conversations ;-) https://www.bountysource.com/issues/2629125-fake-headers-bug-574441-when-run-through-getmessagescollectionforheaders-return-totally-unrelated-messages
