### ISSUE TITLE
Enigmail - Replying in Thread Fails to Encrypt, New Window Reply Still Works

### ISSUE THREAD

**Issue by abomi** [protz/thunderbird-conversations#1261]
* **Thunderbird version:**
52.5.0 (64-bit)

* **Enigmail version:**
1.9.9

* **Thunderbird Conversation version:**
2.13.4

* **Operating System:**
MacOS High Sierra 10.13.1

**What did you do?**
When using the Reply/Reply All buttons at the bottom of a thread, Enigmail gives an error, fails to encrypt and can't send the message.  Encrypt, Sign and PGP/MIME are all checked.  Making the reply from a new window works without a problem.

Also, messages being written from the thread's reply form don't seem to be saving.  Not sure if this is also an Enigmail handling issue.  My drafts are set to be encrypted before saving.

**What did you expect to happen?**
The message should be encrypted and sent without any trouble, as it is when replying from a new message window.

**What actually happened?**
Enigmail Alert
KEY_CONSIDERED
INVC_RECP 10
FAILURE sign-encrypt 53
<OK>
Send Message Error
Sending of the message failed.
Sending of the message failed.

**Comment by Standard8** [comment]
I've now put up 2.14.5 for add-ons review, hopefully it'll get published within the next day or so. This includes the PR #1291 from @shirosaki that will hopefully fix all the issues when working alongside Enigmail 2.x

I'm going to mark this as closed. Please feel free to file a new issue with full details (and preferably console logs) if this is still an issue in 2.14.5.
