### ISSUE TITLE
Signed messages displayed blank (with enigmail and thunderbird conversations)

### ISSUE THREAD

**Issue by doits** [protz/thunderbird-conversations#1262]
* **Thunderbird version:** 58.0b3
* **Thunderbird Conversation version:** 2.13.4
* **Operating System:** MacOS 13.0.3

**What did you do?** Try to view a signed message

**What did you expect to happen?** Message displays

**What actually happened?** Message stays blank

I've installed **enigmail 2.0a2pre** and Thunderbid does not display signed messages I receive. Even when I open it in classic reader, the body stays blank. When I disable thunderbird conversations, it is displayed correctly.

**Comment by MBurchard** [comment]
I do not have this problem with Thunderbird 52.7.0, Enigmail 2.0.1 and Thunderbird Conversations 2.13.4.
Seldom messages remain unread and the pages are white. A restart of the Thunderbird helps here.

**Comment by irgendwie** [comment]
Seems to only affect S/MIME signed messages

**Comment by obama** [comment]
i have the bug too 2.13.4 and enigmail 2.0.5

**Comment by 73** [comment]
- Thunderbird: 52.9.1
- Conversations 2.13.4
- Enigmail 2.0.7
Same here.

**Comment by shirosaki** [comment]
Enigmail 2.0 changed internal structure in large. So it doesn't work with current Enigmail plugin.
It is difficult to fix bugs for now.

**Comment by shirosaki** [comment]
I created a patch for this. #1291 for Thunderbird 60.

**Comment by Standard8** [comment]
Thanks to @shirosaki for working on this. I've just merged #1293 which is simpler than #1291 and from the enigmail author.

I believe this should fix the decryption of emails. I've just created version 2.14.3 that is now in the add-on review loop that includes the fix, hopefully it should be accepted in the next couple of days. Note that 2.14.3 only works with Thunderbird 60.x. We won't be realising a version for 52.x.

@shirosaki As I don't use enigmail, it is unclear if there's still more work to be done here, or if there's other engimail issues to resolve, e.g. #1261 maybe? If you could advise, that would be most useful. Thank you.

**Comment by Standard8** [comment]
2.14.3 has just been approved and is now available for update/download (for TB 60), so if people can try it and give feedback that'd be useful.

**Comment by cryptoluks** [comment]
Hi,

tried latest official plugin 2.14.4 with Enigmail 2.0.8 and Thunderbird 60, but S/MIME signed messages are still blank.

I compiled also directly from git, but did not work either.

Thanks for your effort.

**Comment by Standard8** [comment]
I've now put up 2.14.5 for add-ons review, hopefully it'll get published within the next day or so. This includes the PR #1291 from @shirosaki that will hopefully fix all the issues when working alongside Enigmail 2.x

I'm going to mark this as closed. Please feel free to file a new issue with full details (and preferably console logs) if this is still an issue in 2.14.5.
