### ISSUE TITLE
Not showing pdf preview

### ISSUE THREAD

**Issue by joebelladonna** [protz/thunderbird-conversations#1263]
* **Thunderbird version:** 52.5.2
* **Thunderbird Conversation version:** 2.13.4
* **Operating System:** win 8.1

**What did you do?** Clicked on a "preview" link next to an attachment of a pdf file

**What did you expect to happen?** To see a preview of a pdf file in a new tab.

**What actually happened?** New tab opened, but there were no pdf preview, only blank white tab background.

**Comment by iraklisg** [comment]
Same here running TB 52.5.2 (64-bit) on Debian :cyclone:

**Comment by fllp** [comment]
AFAIC Thunderbird has JavaScript disabled by default for some time now. Since that is also an issue if you want to access a GoogleMail account (the auth form is a WebView requiring enabled JS), it might as well be the reason for PDF.js not to work.

**Comment by Standard8** [comment]
@joebelladonna, @iraklisg is this all PDFs, or just certain ones. I'm running the same versions & pdfs are loading just fine here.

> AFAIC Thunderbird has JavaScript disabled by default for some time now. Since that is also an issue if you want to access a GoogleMail account (the auth form is a WebView requiring enabled JS), it might as well be the reason for PDF.js not to work.

That's unlikely to be the case - the file would have been downloaded as part of the email, and the tab that opens isn't going to have javascript disabled (javascript is only disabled on message previews).

**Comment by iraklisg** [comment]
@Standard8 In my case, preview seems to fail for all pdfs... To put it anoter way, at least it fails for all pdfs I tried to preview so far...

**Comment by joebelladonna** [comment]
@Standard8 All PDFs. I can open it by clicking on open button, but not to preview it. It simply gives be blank tab.

**Comment by Standard8** [comment]
Is this still an issue with Thunderbird 60 & the latest conversations version?

**Comment by Standard8** [comment]
If this is still an issue, then I think we'd need a specific example, and error console output. It is all working for me in TB 60 in the latest version.
