### ISSUE TITLE
Blank Preview in Beta 58 with TC 	201709051426

### ISSUE THREAD

**Issue by scheinercc** [protz/thunderbird-conversations#1264]
* **Thunderbird version:** 58.0b3
* **Thunderbird Conversation version:** 2.13.4 (201709051426)
* **Operating System:** Mac OS

**What did you do?**
Hit the preview button

**What did you expect to happen?**
The preivew tab to open and to display a preview of a pdf

**What actually happened?**
The tab opened blank.

This also happened with previous versions of 58.0b*. I had a quick look in the error console, but nothing came up.

**Comment by doits** [comment]
dupe of #1263

**Comment by Standard8** [comment]
Duplicate of #1255

**Comment by Standard8** [comment]
Opps
Duplicate of #1263
