### ISSUE TITLE
Addon leaking links from e-mails by doing DNS lookups

### ISSUE THREAD

**Issue by xdanx** [protz/thunderbird-conversations#1265]
Hello,

I would like to start by saying this is a great extension!
* **Thunderbird version:** 52.4.0
* **Thunderbird Conversation version:** 2.13.4
* **Operating System:** Ubuntu 16.04

**What did you do?**

Unfortunately, after checking my computer's netflow I noticed DNS requests from Thunderbird to  domains mentioned in various e-mail I have received.

There is no HTTP traffic, just DNS requests.

**What did you expect to happen?**

I would expect this addon not to leak any links I have received (even in encrypted e-mails!), as this is a huge privacy issue regarding users' e-mails.

**What actually happened?**

The addon is generating DNS requests to some links that exist in various e-mails. After removing the addon, the issue disappeared. 

Let me know what you think, I can submit wireshark screenshots also.
Thanks,
Dan

**Comment by Standard8** [comment]
The short-term work around is to go to Preferences(/Options) -> Advanced -> General -> Config Editor, and toggle `network.dns.disablePrefetch` to `true`.

For the longer term fix, I need to find the right place to insert `messagepane.docShell.allowDNSPrefetch = false;`.

**Comment by Standard8** [comment]
I've just pushed a fix for this to master. Seems to work afaict. We'll be releasing it with the next major version, hopefully in a couple of weeks.

**Comment by xdanx** [comment]
Thanks a lot for your fix. Looking forward to the release.
