### ISSUE TITLE
Broken in Beta 59.0b1

### ISSUE THREAD

**Issue by scheinercc** [protz/thunderbird-conversations#1267]
* **Thunderbird version:** 59.0b1
* **Thunderbird Conversation version:** 2.13.4
* **Operating System:** macOS 10.11

**What did you do?**
Open email after updating to 59

**What did you expect to happen?**
Email gets displayed.

**What actually happened?**
<img width="640" alt="image" src="https://user-images.githubusercontent.com/817856/36348022-eb737bd4-14bb-11e8-85e0-174fe30c0fc9.png">

**Comment by karakatsanism** [comment]
I am having the same problem.

**Comment by M-Falken** [comment]
Hello
Same for me

**Comment by Standard8** [comment]
No need for the +1s. This is a duplicate of #1255

**Comment by scheinercc** [comment]
Thanks @Standard8
