### ISSUE TITLE
Different emails with same Message-ID are not displayed

### ISSUE THREAD

**Issue by ValdikSS** [protz/thunderbird-conversations#1268]
* **Thunderbird version:** 52.6.0
* **Thunderbird Conversation version:** 2.13.4
* **Operating System:** Fedora Linux 27

**What did you do?**
I got 3 different messages with same Message-ID (original message, forwarded and edited message and a copy of the second).

**What did you expect to happen?**
All three messages are displayed in conversations.

**What actually happened?**
Only the first message is displayed in conversations. Clicking on second or third message in the main view shows the overall latest message in conversations (either received or sent). For example, right now the latest message is a message I sent as a reply. Clicking on second (forwarded) message opens my latest sent message.

**Comment by protz** [comment]
I think this is going to be hard to fix as the message-id is treated as a unique key, and several emails with the same message-id are assumed to be identical, and only one is picked to be displayed in the conversation; do you have any suggestion on how to better handle this?

thanks,

Jonathan

**Comment by ValdikSS** [comment]
I'm not sure if this is a mail server web interface issue that the forwarded message got the same message ID (these messages are sent using web interface), or is this a common situation.
I had this problem only once.
Thunderbird without the extension displays every message.

**Comment by Standard8** [comment]
I think what we're doing with de-duping is reasonable, and this doesn't seem to be an issue for lots of people.

The message-id is meant to be a unique key, so if something in the system is making it the same, that's going to be hard to deal with.

Thunderbird probably gets away with it as it isn't trying to do conversation views as such.

**Comment by eli-schwartz** [comment]
The only reason I can think of for this is if you receive the same email twice, for example, an email is cross posted to two different mailing lists and you receive both copies. In such cases it doesn't seem unreasonable to show only one of them.

**Comment by ValdikSS** [comment]
@eli-schwartz, no, when I created this issue I got 3 different emails, with different text, from the person I had a conversation with. He used web interface of Ukrainian mail provider, I think it was i.ua. And that webmail generated emails with same IDs for some reason. I could not see his newer reply unless I disabled thunderbird-conversations.
