### ISSUE TITLE
Problem with compatibility

### ISSUE THREAD

**Issue by lisuml** [protz/thunderbird-conversations#1270]
* **Thunderbird version: 52.7.0**
* **Thunderbird Conversation version: 2.14pre**
* **Operating System: Arch Linux (64 bits)**

**What did you do?**
Upgraded thunderbird from 52.6 to 52.7
Upgraded thunderbird conversations from commit cd5c5c4 to commit 100641d

**What did you expect to happen?**
thunderbird conversation built from cd5c5c4 commit seemed to work just fine with after upgrading thunderbird to 52.7 and I was expecting commit 100641d to work as well

**What actually happened?**
After upgrading thunderbird conversation to commit 100641d and re-starting thunderbird 52.7, the plugin got disabled with the message: Thunderbird Conversations is incompatible with Thunderbird 52.7. I tried downgrading both the plugin and thunderbird (both of them at the same time and also separately), but nothing helped. When running thunderbird conversations cd5c5c4 on top of thunderbird 52.6 I now also see the message: Thunderbird Conversations is incompatible with Thunderbird 52.6 and the plugin remains disabled

**Comment by Standard8** [comment]
Sorry, but we're starting on making master work with Thunderbird 60 beta, and it'll be dropping support for older versions. Unfortunately it'll be too much work/additional code to support both.
