### ISSUE TITLE
BzAPI for bugs.kde.org

### ISSUE THREAD

**Issue by Frederick888** [protz/thunderbird-conversations#1271]
Hi,

The notice I got in Thunderbird led me to the [wiki](https://github.com/protz/thunderbird-conversations/wiki/BzConversations) page and I can confirm that the API endpoint of bugs.kde.org is just `https://bugs.kde.org/rest`.

For instance, I could run
```
curl https://bugs.kde.org/rest/bug/300000
```
...to fetch the details of this bug. And they also allow generating API keys at https://bugs.kde.org/userprefs.cgi?tab=apikey

**Comment by protz** [comment]
hello,

thanks for looking into this!

could you submit a pull request to modify the following table? https://github.com/protz/thunderbird-conversations/blob/master/content/stub.compose-ui-bz.js#L49 I believe the keys are the value of the X-Bugzilla-URL and the values are the API endpoint... thanks!

**Comment by Frederick888** [comment]
@protz There you go #1272 
For some reason they are not using https in in the email header field 🤔

**Comment by Standard8** [comment]
We're going to be dropping the close bugzilla integration as it doesn't seem that useful and adds complexity we don't want to support at the moment.
