### ISSUE TITLE
Help on CSS file to make dark theme.

### ISSUE THREAD

**Issue by Luklek** [protz/thunderbird-conversations#1274]
Hello,
I am using Stylish to make Conversations have a dark look, but I am not very good at CSS (I am very bad^^)
Anyone could help fix these 2 issues?
How to change the line divider color in conversation list?
How to make the background dark but keep the "Reply" text in the quick reply box?
Below my CSS and screenshots.

![Image](https://imgur.com/fypnVrk.png)

![Image](https://imgur.com/8EyKOF2.png)

`
/* changes background color of the message body*/

body
{
background-color: #202020 ;
  color: #fff;
}

/*removes background image of the buttons in the header and changes the background color*/

/*eliminates the box shadow*/

#conversationHeaderWrapper
{
background-color: #000 !important;
}

/*changes attributes of the conversation header*/

#conversationHeader
{
padding: 4px 10px !important;
background-image:none !important;
border-bottom: 1px solid threedshadow !important;
border-bottom-color: #000 !important;
border-top: 0px solid threedhighlight !important;
background-color: #424242 !important;
min-height: 35px !important;
max-height: 33px !important;
}

/*changes text from bold to normal, changes font size, and centers text top to bottom*/

.subject
{
font-weight: normal !important;
padding-top: 0px !important;
padding-bottom: 12px !important;
margin-top: 0px !important;
margin-bottom: 12px !important;
font-size: 14px !important;
  color: #fff;
}

/*changes border around  the message and eliminates the shadow*/

.message
{
border: 3px solid #3c3c3c !important;
box-shadow: none !important;
background-color: #242424 !important;
  color: #fff;
}

.snippet {
color: #e5e5e5 !important;
}

.quickReply
{
background-color: #242424 !important;
}

.to
{
color: #fff !important;
}
.contactName
{
color: #fff !important;
}
.fromField
{
color: #fff !important;
}
.senderName
{
color: #fff !important;
}

.recipientList
{
color: #fff !important;
}
.smallEmail
{
color: #fff !important;
}

.recipientListSeparator {
  color: #fff;
}

.replyMethod > label {
  cursor: pointer;
  color: #fff;
}

.quickReplyIcon {
  width: 100%;
  height: 32px;
  font-size: 1.4rem;
  position: absolute;
  z-index: 100;
  top: 50%;
  left: 0;
  margin-top: -16px;
  line-height: 32px;
  text-align: center;
  color: -moz-nativehyperlinktext;
  white-space: nowrap;
  overflow: hidden;
}

.textarea
{
background-color: #242424 !important;
  z-index: 0;
}

.textWrap
{
background-color: #242424 !important;
}

.attachments{
color: #FFF !important;
}
.buttonReply {
color: #FFF !important;
}
.buttonReplyAll {
color: #FFF !important;
}
.buttonReplyList {
color: #FFF !important;
}
.buttonForward {
color: #FFF !important;
}`

**Comment by ikirudennis** [comment]
Looks like this should do it:
```
#message_list > li {
border-bottom-color: #abcdef;
}
```

I used the Developer Toolbox to find that out. `Tools > Developer Tools > Developer Toolbox`

As a side note: perhaps Stylish has its own help system that might be more appropriate, in case my code above doesn't do the trick, or if you have more questions.

**Comment by Luklek** [comment]
My other question has any solution too? "How to make the background dark but keep the "Reply" text in the quick reply box?"
Thanks a lot anyway even if you can't help anymore!

**Comment by Standard8** [comment]
I would suggest looking in the developer tools. There's an inspect button that you can use to locate the element you want to style and then look at the css already applied. You can also test adding further rules in that as well.

I'm going to close this now as this is just a request for information rather than an actual issue.
