### ISSUE TITLE
Some messages don't load when clicked

### ISSUE THREAD

**Issue by 360path** [protz/thunderbird-conversations#1276]
* **Thunderbird version:** 52.7.0 (32-bit)
* **Thunderbird Conversation version:** 2.13.4
* **Operating System:** Windows 10

**What did you do?**
I have some messages / message threads in my folder that don't open if I click those. 

**What did you expect to happen?**
The thread shows normally, just like the other threads.

**What actually happened?**
The preview pane only shows "Loading..." or the subject of the previously selected message / thread. Other mails are opened fine. If I double-click those mails to open them in a new tab it just says "Loading..." and nothing happens.

I turned on the logging for Conversation and this is the output in the error console:
```
unreachable code after return statement[Learn More]  jquery.tokeninput.js:470:4
chrome://conversations/content/stub.xhtml : Unable to run script because scripts are blocked internally. (unknown)
XML Parsing Error: mismatched tag. Expected: </span>.
Location: 
Line Number 2610, Column 11:  (unknown):2610:11
2018-05-09 14:23:59	Conversations.Conversation	ERROR	SyntaxError: An invalid or illegal string was specified
  log4moz.js:691
	CApp_append resource:///modules/gloda/log4moz.js:691:7
	Logger_log resource:///modules/gloda/log4moz.js:380:7
	Logger_error resource:///modules/gloda/log4moz.js:388:5
	_Conversation_onQueryCompleted_bug547088 resource://conversations/modules/conversation.js:629:9
2018-05-09 14:23:59	Conversations.Conversation	ERROR	SyntaxError: An invalid or illegal string was specified

```

**Comment by Standard8** [comment]
You might want to investigate the messages themselves to see if there's any strange characters or contents. It could be something that we're not handling right.

**Comment by Standard8** [comment]
This is quite old now, and we've rewritten how we render the UI.

If it is still an issue on the latest conversations (3.0.16) on Thunderbird 68, please feel free to reopen or file a new issue.
