### ISSUE TITLE
The "Options"/"Preferences" button in the remote content bar does not appear when message is shown in a new tab

### ISSUE THREAD

**Issue by Kyatric** [protz/thunderbird-conversations#1278]
* **Thunderbird version: 52.8.0 (32 bits)**
* **Thunderbird Conversation version:2.13.4**
* **Operating System:Win 7 Pro SP 1**

It used to look like this : https://support.mozilla.org/fr/kb/contenu-distant-dans-les-messages#w_afficher-le-contenu-distant-pour-un-message-particulier-lexpaediteur-ou-le-site-web

Now it just looks like this : https://prod-cdn.sumo.mozilla.net/uploads/gallery/images/2014-09-25-05-51-53-b75564.png without the "Options" button.

I'm not authorizing distant content and relied on this button to check the images for the few mails I'm interested in.
My display is set to Original HTML.

> Worth noting, if I switch to "Discussion view", I do have a link "Le contenu distant a été masqué : afficher le contenu distant" (distant content has been hidden: display the distant content) which is the option I'm looking to have back.
Yet the Options button is more comfortable.

If I deactivate the addon, I'm getting the button back which leads me to believe the addon is in cause.

Expected results:

I just want the Options button back, thanks.
Or a way to configure my client so it works as I'm used to.

I originally opened a thunderbird bug report : https://bugzilla.mozilla.org/show_bug.cgi?id=1464240

**Comment by Standard8** [comment]
This appears to only be an issue in the "open message in a new tab" case, viewing as part of the message list, conversations has its own remote content handler, also opening in a new window also shows the button.

**Comment by Cuchelain** [comment]
It isn't just missing in new tabs, it is also missing in the preview pane.  The only ways I've found to make it appear is open message in a new window or disable the extension.  Neither is really a good solution.

**Comment by Standard8** [comment]
This is it for me on the preview pane, works fine there:

<img width="715" alt="screen shot 2018-05-31 at 14 33 36" src="https://user-images.githubusercontent.com/520844/40785161-a7842e04-64df-11e8-93ef-544226a0e409.png">

**Comment by pbarney** [comment]
It is not on my message pane either. (Conversations 2.13.4, Thunderbird 52.8.0)

**Comment by Kyatric** [comment]
@Standard8 What you are showing is what I refer to in my report as the fact it is "working" when you have the "Discussion view" activated in the "Display" menu.

If you deactivate it, it goes back to the regular Mozilla's view, and the options button does not show up nonetheless. 

Yet, if you deactivate the plugin, the button shows up again.

Screenshot showing both sides (in French) : https://kyatric.com/work/2018.06.05.png

**Comment by Ratithoglys** [comment]
I have the exact same issue in both the preview pane and the new tab.
The button still show in a new window also.

And I also use Thunderbird 52.8.0 French UI with Conversations 2.13.4.
The problem persists if I switch the locale to en-US

**Comment by BrendanSimon** [comment]
Any progress on this?

FYI.  Same symptoms on Mac platform.

- `Preferences` button does **not** show up in preview pane.
- `Preferences` button does **not** show if select "Open Message in New Tab".
- `Preferences` button **does** show if select "Open Message in New Window".
- `Preferences` button **does** show if `Conversations` extension is **disabled**.

**Comment by Standard8** [comment]
For me, this is a low priority compared to other work I want to do. If someone can investigate and provide a patch, we'll gladly take it.

My suspicion is that this would lie in how we're stubbing the message pane. A starting point would be to work out what happens when "Conversation View" is enabled versus when it isn't.

**Comment by arnonsha** [comment]
I have the same issue on Linux (TB 52.9.1, conversation version 2.13.4)
Can't see button both in message pane, and in new tab.

The only bypass is to open the message in a new window (or disable the conversation extension)

Please fix

**Comment by Standard8** [comment]
I happened across this whilst I was looking at some other code. The issue is now fixed in the latest master and on the 2.15+ branch.

I've just pushed v2.15.8 for review to the add-ons site. This has the fix. Note that the 2.15.x series is only compatible with Thunderbird 68, and currently has quick reply disabled due to other issues.

**Comment by michelverhagen** [comment]
@Standard8 Mate! Thanks! It's been a pain for a VERY long time!
