### ISSUE TITLE
thunderbird 59+ support

### ISSUE THREAD

**Issue by PackElend** [protz/thunderbird-conversations#1280]
I'm running TB 60 but unfortunately thunderbird-conversations isn't compatible yet.
When will it be supported

**Comment by nd-** [comment]
Have you read #1255 before posting and asking "When will it be supported" ?

And specially this answer from @Standard8 : 
https://github.com/protz/thunderbird-conversations/issues/1255#issuecomment-384895760

**Comment by PackElend** [comment]
Haven't found that one although I search back for a year.
Thank you for the hint

**Comment by Standard8** [comment]
Duplicate of #1255
