### ISSUE TITLE
Enhancement: Add a "Reply to List" Link or Button When Answering to Mailing Lists

### ISSUE THREAD

**Issue by code-chicken** [protz/thunderbird-conversations#1282]
* **Thunderbird version:** 52.8.0
* **Thunderbird Conversation version:** 2.13.4
* **Operating System:** Windows 10 Professional

**Action**
I answered to a mailing list.

**What I expected to happen**
The To: address field should contain the email address of the mailing list

**What actually happened:**
The To: address field contained the the address of the person I answered to

Suggestion: At least if there is a **List-Post:** header line there should be a way to use the address of the mailing list as recipient.

![image](https://user-images.githubusercontent.com/3024019/41251199-7a158b1a-6db9-11e8-8cc1-b1ce6df18734.png)

![image](https://user-images.githubusercontent.com/3024019/41251080-2b3968ae-6db9-11e8-82c6-08d7b8fcc9ef.png)

**Comment by Standard8** [comment]
Conversations is already relying on Thunderbird's global database to provide indication if there is a list or not. As far as I can tell, [Thunderbird's global database uses list-post](https://searchfox.org/comm-central/rev/39dfe669890195fca6422bd773def263376bc8f2/mailnews/db/gloda/modules/fundattr.js#485-489).

The reply to list indication has also be working fine for me.

Could you try viewing using the classic reader, and check there's a toolbar button to reply to list?

Also, could you try restarting Thunderbird, going to Tools -> Developer Tools -> Error Console and see if anything appears when you open one of the list messages?

I'm thinking there may be an issue around somewhere that causes this to break in strange situations.

**Comment by code-chicken** [comment]
Hi Mark,

you are right - somehow this works fine now. However, by some reason it didn't work a couple of days ago. I cannot reproduce it any more.

Thank you

**Comment by Standard8** [comment]
No problem, glad it is working.
