### ISSUE TITLE
Stuck on "loading" when TB ui in hebrew.

### ISSUE THREAD

**Issue by nadavtoledo** [protz/thunderbird-conversations#1284]
* **Thunderbird version:**
52.8
* **Thunderbird Conversation version:**
2.13.4
* **Operating System:**
Manjaro 17

**What did you do?**
Running TB: thunderbird -uilocale he

**What did you expect to happen?**
TB conversation to work
**What actually happened?**
every mail i click on, just stay blank and it says loading...

The same thing happened with TB 38+ on windows 7.
The only combination the worked on windows was TB37 +conversation 2.8.1
upgrading conversation to 2.9 and up or TB to 38 and up , didnt work anymore
on manjaro I haven't checked yet.

**Comment by Standard8** [comment]
Thanks for the report. It seems like there's an issue with Hebrew. We formulate a string for the message and try and put it into the .innerHTML, but it doesn't like that. I'm suspecting we need to escape some of the localised strings. Not quite sure where yet, maybe in handlebars-wrapper.js

**Comment by Standard8** [comment]
I've just checked this in the latest version of Conversations, and this appears to be working correctly now. We did a big rewrite and that appears to have helped fix this.

I'm sorry that this has taken so long.

Looks like there's quite a few RTL improvements that could be made, so we'll try and look into those soon as well - I've just filed #1421 for that.
