### ISSUE TITLE
Not working with Thunderbird 52.9.1 

### ISSUE THREAD

**Issue by MartinX3** [protz/thunderbird-conversations#1285]
* **Thunderbird version:** 52.9.1 
* **Thunderbird Conversation version:** 2.13.4
* **Operating System:** Linux Mint 19

**What did you do?**
Update Thunderbird

**What did you expect to happen?**
Conversation-Tree's

**What actually happened?**
No Conversation-Tree's

**Comment by MartinX3** [comment]
After a system restart (application restart did not help), I've got my conversation tree structure back, but if I delete a collapsed entry at its root, this undeletable entry occur (will go away, if I restart thunderbird):
![grafik](https://user-images.githubusercontent.com/4518092/42726136-f2c0e650-878f-11e8-9277-6b520b17ce16.png)

**Comment by Standard8** [comment]
Conversations doesn't affect the message list itself. It only affects the preview window. If you've got issues in the message list, then this is most likely an issue with Thunderbird itself.

**Comment by MartinX3** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=209501
Yes, you're right.
This bug exist since 15 years!
Thank you!
