### ISSUE TITLE
Conversations not re-formed in a moved folder

### ISSUE THREAD

**Issue by bloodwood** [protz/thunderbird-conversations#1287]
* **Thunderbird version:** 52.9.1 (64 bit)
* **Thunderbird Conversation version:** 2.13.4
* **Operating System:** Linux Mint 18.3

In Tbird I'm working between a Gmail account and a ProtonMail account. Might the encryption in Protonmail present problems for TBird Conversation?

**What did you do?**
Copied a folder from one account to another account. The folder has nearly 1,000 emails in it.

**What did you expect to happen?**
Threaded conversations to appear, like how they appear in the original folder.

**What actually happened?**
Emails are unthreaded. I select View>Sort by>Threaded, and View>Threads>Collapse all threads - nothing happens.

**Comment by Standard8** [comment]
If selecting the view options doesn't fix it, then this is a Thunderbird issue. Conversations only affects the display of the messages in the preview window, not in the message list. You can probably reproduce that if you turn off conversations.

Even if it is in the message preview window, conversations gets the threading information from Thunderbird itself.

You can file an issue with them at https://bugzilla.mozilla.org.
