### ISSUE TITLE
No german translation in Version 2.14.1

### ISSUE THREAD

**Issue by thebugfixnet** [protz/thunderbird-conversations#1288]
* **Thunderbird version:** 60.0b10 (32-Bit)
* **Thunderbird Conversation version:** 2.14.1
* **Operating System:** Win 10

**What did you do?** Activated Conversations :)

**What did you expect to happen?** Menus, Buttons, Texts in same language as the rest of Thunderbird. In my case German.

**What actually happened?** The conversation-texts are all in english

**Comment by Standard8** [comment]
Ah yes, my fault. I forgot that these needed copying across. I'll see if I can release a new version tonight or tomorrow.

**Comment by Standard8** [comment]
I've fixed it, and the branch has all the localisations again. The new version is up for review on AMO, I suspect that will get reviewed in the next day or two.
