### ISSUE TITLE
Converasations 2.14.2 Appears to Break Calendar

### ISSUE THREAD

**Issue by e6lk7dqzm83p** [protz/thunderbird-conversations#1292]
* **Thunderbird version:**
60.0b10 (64-bit)
* **Thunderbird Conversation version:**
2.14.2
* **Operating System:**
Qubes (Fedora VM)

**What did you do?**
Installed the new version of Conversations

**What did you expect to happen?**
No significant change in behavior

**What actually happened?**
I no longer get the buttons to respond to calendar invites (e.g., Accept, Reject, Update), which was the case with the previous version of conversations.  I do see the buttons when I open the message in a new tab/window.

**Comment by Standard8** [comment]
@e6lk7dqzm83p Thank you for the report.

Can you go to Tools -> Developer Tools -> Error Console, and see if any messages appear when you select an invitation message?

**Comment by Standard8** [comment]
Ignore the bit about the error console, I was able to give it a quick go here, and there's nothing useful, but it is broken.

**Comment by Standard8** [comment]
Looks like Lightning has changed how it does calendar invite notifications, which broke our mechanism for hooking into those. I've fixed an import issue, which gets the notification displayed again, but no buttons. I'll need to carve out a bit of time to investigate that in more detail.

**Comment by e6lk7dqzm83p** [comment]
Thank you, and thank you for maintaining this excellent (and essential) add-on.

Please let me know if I can help in anyway...

**Comment by Standard8** [comment]
Just to follow-up here, 2.14.3 has just been released which includes the fix for this. Should be available by updating your add-ons.
