### ISSUE TITLE
PDF preview not working in TB 60

### ISSUE THREAD

**Issue by despecial** [protz/thunderbird-conversations#1297]
* **Thunderbird version:** 60
* **Thunderbird Conversation version:** 2.14.3
* **Operating System:** High Sierra

**What did you do?**
Upgrade to Thunderbird 60

**What did you expect to happen?**
Preview of PDF attachment

**What actually happened?**
New tab opens and preview is not loading: error message saying "ReferenceError: pdfjsLib is not defined" shows up.

**Comment by Standard8** [comment]
Thank you for the report, I'd messed up building it, as I forgot about the fact that the pdfjs library version had changed and I forgot to run `npm install`. I've filed #1298 to work up a permanent prevention.

For now, I've tagged a new 2.14.4 and rebuilt it. That's been posted for review on the add-ons site, so hopefully that'll get released soon.
