### ISSUE TITLE
Drafts are being displayed as part of the conversation

### ISSUE THREAD

**Issue by agusl88** [protz/thunderbird-conversations#1302]
When using IMAP (in this particular case, a gmail account), drafts are being saved and pushed to gmail automatically, and in thunderbird they are being displayed as part of the conversation like regular emails. As a result of this, sometimes i have 10+ copies of the same email as part of the conversation, and they are just partial drafts saved by thunderbird and pushed to gmail, and visually i have no way to distinguish them from the sent/recived emails.

Having them collapsed by default, and an option to hide them from the conversation would be great. Maybe some UI changes to help distingish them from regular emails, for those who want to display them as part of the conversation like gmail does.

**Comment by Standard8** [comment]
@agusl88 Is your draft folder somewhere special? When my messages are collapsed I see something like:

<img width="167" alt="screen shot 2018-09-05 at 20 56 22" src="https://user-images.githubusercontent.com/520844/45117701-4354da80-b14e-11e8-8d13-d978e3ebbe4a.png">

There's also a badge for it being in drafts when the message is expanded.

If you're getting multiple copies of drafts unintentionally, you might want to file that with Thunderbird themselves.

**Comment by Standard8** [comment]
No response and no duplicates, so unfortunately we don't know what the issue is here. Closing out.
