### ISSUE TITLE
Stylish is not recommended to be used. 

### ISSUE THREAD

**Issue by Yoshi8765** [protz/thunderbird-conversations#1304]
Hello, I took a look at your wiki page [here](https://github.com/protz/thunderbird-conversations/wiki/Tips-and-tricks%3A-Disabling-the-%22Quick-Reply%22-feature). Turns out Stylish isn't available on Thunderbird,  or recommended to be used anywhere since it was **bought out and tracks users.**

Is there any other way to disable the Quick reply?

**Comment by rnc** [comment]
I migrated away from Stylish and just placed the same information within `$HOME/.thunderbird/<profile>/chrome/userChrome.css` which works fine.

**Comment by Standard8** [comment]
I was wondering if it was possible via userChrome.css.... please feel free to update the wiki (if you can).

**Comment by rnc** [comment]
@Standard8  Updated https://github.com/protz/thunderbird-conversations/wiki/Tips-and-tricks:-Disabling-the-%22Quick-Reply%22-feature

**Comment by Yoshi8765** [comment]
Thanks everyone for the help. 
In Win10 64-bit, is this the profile folder accessible through 'Troubleshooting information-> Profile Folder'?
a `chrome` folder didn't exist, so I made it and created a new .css file.

**Comment by rnc** [comment]
@Yoshi8765 I don't have a Windows system accessible right now to test, but according to https://developer.mozilla.org/en-US/docs/Mozilla/Thunderbird/Thunderbird_Configuration_Files and https://superuser.com/questions/431289/where-is-userchrome-css and https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Runtime_Directories  you may need to create the folder but first establishing the correct profile folder is critical. What is the full path you are using?

**Comment by Yoshi8765** [comment]
@rnc I accessed my profile folder [here](https://my.mixtape.moe/zhoawi.jpg).

The full path is: C:\Users\[USERNAME]\AppData\Roaming\Thunderbird\Profiles\nkdzher6.default\
I created a `chrome` folder in here.

**Comment by rnc** [comment]
@Yoshi8765 That does look correct from the documentation. Its a bit surprising it doesn't work. Can you recheck your userChrome.css to ensure that the quickreply lines correctly end with line terminators?

**Comment by Standard8** [comment]
I've just tried it here - it worked fine if I dropped the namespace line, but with that it seems to not read the file.

I've therefore updated the Wiki, @Yoshi8765 can you see if that works for you now?

**Comment by Yoshi8765** [comment]
@Standard8 I can confirm it works now without the namespace line. Thank you!
