### ISSUE TITLE
add-on triggers exception: [javascript application] Failed to connect via oauth:...

### ISSUE THREAD

**Issue by PackElend** [protz/thunderbird-conversations#1306]
Thunderbird 60.0b11 (32-bit)
Thunderbird Conversations 2.14.4
Win 10 Enterprise 1703

Thunderbird beta 11 update leads to the exception  `[javascript application] Failed to connect via oauth: ...` It is thrown when I open an email.
If I disable thunderbird conversations, the problem is gone.

I any idea why and how to debug?

**Comment by Standard8** [comment]
Please can you use the reporting templates in future, it helps.

For starters, I have to assume you're on Thunderbird 60 beta 11 (the major version is important). Though you haven't said which version of Conversations you are on. Please check you are on the latest Conversations version by updating from the add-ons panel.

It should be 2.14.4, you can confirm that by clicking the "More" link next to the add-on description.

**Comment by PackElend** [comment]
> Please can you use the reporting templates in future, it helps.
my mistake I added all versin information

**Comment by Standard8** [comment]
Thanks. Please can you open the Error Console (under Tools -> Developer Tools and copy any errors you're seeing when you select an email. Maybe errors just after startup as well might help.

Having the full exception you're seeing might help as well.

Also, do you have any other add-ons installed? I'm wondering if one of those might be conflicting somehow.

**Comment by PackElend** [comment]
That text is the full exception
Will send debug log tomorrow
There are other add ons

Sent from a fair mobile

Le jeu. 6 sept. 2018 à 22:01, Mark Banner <notifications@github.com> a
écrit :

**Comment by Standard8** [comment]
Hmm, I didn't realise 60beta11 was fresh out. It seems to be working fine for me.

One other thought though, do you use a master password?

**Comment by PackElend** [comment]
no master password yet

**Comment by PackElend** [comment]
**Extensions**

Addressbooks Synchronizer	1.2.2	true	addressbookssync@ggbs.de
Auto Save Drafts Folders	0.3.0	true	asdf@d.lech
Automatic Dictionary	1.10.4	true	automatic_dictionary_extension@jordi_beltran.net
Before Tabs Toolbar	1.7	true	btt@paenglab.ch
Contact Tabs	2.6.4	true	contacttabs@janek.org
External Editor	1.0.3	true	{11d1a081-b8c3-4002-af38-6ad3e899fdfa}
Gmail Buttons	0.8.1	true	gmailbuttons@d.lech
IMAP Draft Unread	1.1.2	true	imapdraftunread@micz.it
Lightning	6.2b6	true	{e2fda1a4-762b-4020-b5ad-a41df1933103}
Lightning Invitation Notifier (LIN)	1.4	true	lightninginvitationnotifier@markus.pullmann
Manually sort folders	1.1.1	true	tbsortfolders@xulforum.org
MRC Compose	1.9.0	true	mrc_compose@mr-consultant.net
Provider for Google Calendar	4.4.1	true	{a62ef8ec-5fdc-40c2-873c-223b8a6925cc}
Quicktext	1.1	true	{8845E3B3-E8FB-40E2-95E9-EC40294818C4}
Signature Switch	1.7.1	true	{2ab1b709-ba03-4361-abf9-c50b964ff75d}
Stop Ignoring Reply:To	1.2	true	stopignoringreplyto@gelvins.com
TbSync	0.7.15	true	tbsync@jobisoft.de
ThunderHTMLedit	1.8.5	true	jorgk@thunderHTMLedit
G-Hub Lite	6.0.0	false	thundervoice@chris.schiffner
Thunderbird Conversations	2.14.4	false	gconversation@xulforum.org

**Comment by PackElend** [comment]
It looks like I was mislead, it looks like  Gmail Buttons 0.8.1 true gmailbuttons@d.lech messing all up 

I think that is the cause:

> TypeError: oauth.buildXOAuth2String is not a function[Learn More]  gmailbuttonsOverlay.js:489:26
> 	onSuccess chrome://gmailbuttons/content/gmailbuttonsOverlay.js:489:26
> 	connect/onPromptAuthAvailable/< jar:file:///C:/MEINS/TOOLS/Mozilla%20Thunderbird%20Beta/omni.ja!/components/msgOAuth2Module.js:145:11
> 	onRequestTokenReceived resource:///modules/OAuth2.jsm:230:9
> 	onRequestTokenReceived self-hosted:978:17
> 	httpRequest/xhr.onload resource://gre/modules/Http.jsm:70:9

**Comment by PackElend** [comment]
**Extensions**

**Comment by Standard8** [comment]
Yes, that is probably Gmail Button's issue. I'd suggest contacting them first as there's nothing that conversations can do here.
