### ISSUE TITLE
latest release not avaialble in TB

### ISSUE THREAD

**Issue by BrendanSimon** [protz/thunderbird-conversations#1311]
* **Thunderbird version:** 52.9.1 => Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:52.0) Gecko/20100101 Thunderbird/52.9.1
* **Thunderbird Conversation version:** 2.13.4
* **Operating System:** macOS High Sierra 10.13.6

**What did you do?** Go to add-on manager and click "Check for Updates" in Gear/Cog menu.

**What did you expect to happen?** Find latest TB Conversation => 2.14.5

**What actually happened?** TB said everything up to date (yet my TB Conversation is 2.13.4)

Is the latest release uploaded to Mozilla (or wherever) so TB Conversations can be upgraded via the normal TB update mechanism.

I'm happy to do a manual install as a workaround, but the Releases page only has source code.

It would be great if the a pre-built xpi file was available on the Release page for download and manual installation.

Maybe the xpi files are available elsewhere ?

**Comment by BrendanSimon** [comment]
Just discovered there is a TB 60, but my TB 52 said I was up to date.  I think the latest TB Conversations might only be compatible with TB 60.

**Comment by Standard8** [comment]
> Just discovered there is a TB 60, but my TB 52 said I was up to date. I think the latest TB Conversations might only be compatible with TB 60.

Yes, there were too many architectural changes between 52 & 60 for us to maintain compatibility.

> Unfortunately neither upgrade fixes issue #1278 for me :(

As I've already commented there it is low priority for me as there's other more important bugs and maintenance for me to do, but I'd welcome fixes proposed by anyone else.
