### ISSUE TITLE
No Longer threads

### ISSUE THREAD

**Issue by Licks17** [protz/thunderbird-conversations#1312]
* **Thunderbird version:**
* **Thunderbird Conversation version:**
* **Operating System:**

**What did you do? 

**What did you expect to happen?** Thread all conversations just like gmail

**What actually happened?** Conversations no longer threads my messages. I used to be able to delete a message after replying, but go back to it once I get a reply back from the original sender. As of September 21st this stopped working and I have everything updated.

**Comment by Standard8** [comment]
The default is not to index deleted messages - so even if you then got a reply, you wouldn't see it threaded (and this is what I've seen).

Have you maybe enabled "Include this folder in Global Search results" on your bin/deleted folder?

The other possibility here is that something has gone wrong with Thunderbird's indexing file, you might want to try rebuilding it as detailed here:

https://support.mozilla.org/kb/rebuilding-global-database

**Comment by Licks17** [comment]
It worked!

Thanks!

**Comment by Standard8** [comment]
Great.
