### ISSUE TITLE
Enigmail - Replying in Thread Fails to Encrypt, New Window Reply Still Works (Redux)

### ISSUE THREAD

**Issue by abomi** [protz/thunderbird-conversations#1319]
Reopening #1261, as requested.  Problem persists in 2.14.5.

* **Thunderbird version:** 60.2.1
* **Thunderbird Conversation version:** 2.14.5
* **Operating System:** Mac OS 10.14 (Mojave)
* **Enigmail version:** 2.0.8

**What did you do?** send an encrypted reply from the thread

**What did you expect to happen?** email would be encrypted and sent

**What actually happened?** 
```
Enigmail Alert
KEY_CONSIDERED <redacted key a> 2
KEY_CONSIDERED <redacted key a> 0
KEY_CONSIDERED <redacted key b> 0
INV_RECP 10 0x<redacted key b>
FAILURE sign-encrypt 53
```

**Comment by Standard8** [comment]
@abomi Is this still an issue?

Did you try replying in a normal email window?

Do any messages appear on the Error Console when you attempt to send the email?

**Comment by Standard8** [comment]
I'll need more info here, though it seems #1327 is similar, so I'll close this one for now.
