### ISSUE TITLE
Ignore certain folders when building a conversation view

### ISSUE THREAD

**Issue by maximbaz** [protz/thunderbird-conversations#1320]
* **Thunderbird version:** 60.2.1 (64-bit)
* **Thunderbird Conversation version:** 2.14.5
* **Operating System:** Arch Linux

Thunderbird creates a new Archive folder for every year, so when a message is moved to archive, it is moved to `Archives/2018` folder.

I tend to keep my Inbox empty, archiving all non-actionable messages asap. I'm very happy that once a new email arrives, Thunderbird Conversations is able to fetch the relevant thread from the archives, so I can quickly get an overview.

However, I would like to limit which folders Thunderbird Conversations is looking in. For example, I would like to allow it to look only in archive of the current year `Archives/2018`, i.e. not look in previous years like `Archives/2017`. 

My hope is that it will speed-up rendering of the conversation view, because for some threads it takes quite long time to build them.

Is this currently possible? I apologize if this is a duplicate, but I couldn't find an earlier issue.

I'm thinking about purely as an cheap alternative to https://github.com/protz/thunderbird-conversations/issues/1014

**Comment by Standard8** [comment]
I think I'd rather work towards something on #1014.

Although, thinking about it, I think if you right-click on the folder, and de-select "Include messages in this folder in Global Search results", then it might do what you want already.

In any case, closing this out in favour of #1014, as I think it would be time better spent on fixing that.

**Comment by maximbaz** [comment]
> Although, thinking about it, I think if you right-click on the folder, and de-select "Include messages in this folder in Global Search results", then it might do what you want already.

You are right, it worked!
