### ISSUE TITLE
allow folder buttons in fields to be d&d targets?

### ISSUE THREAD

**Issue by chanlists** [protz/thunderbird-conversations#1321]
Thunderbird version: 52.9.1
Thunderbird Conversation version: 2.13.4
Operating System: Windows 10

Thanks for providing this great add-on. I have been using thunderbird for a long time. Initially all my emails went into "Sent", though I like to archive email in the IMAP tree. So "Sent" grew a lot. Then I discovered the option to keep replies in the same folder of the original mail, and only the initial message of a thread and forwards would end up in "Sent". That reduced the "Sent" clutter quite a lot. Then I discovered "Conversations". Now I would like to clean up "Sent". For many messages, conversations shows me the message from "Sent" in the Inbox, together with other messages which I already moved to a dedicated folder, and it shows me the folder of those messages as a blueish button. Now it would make the cleanup of "Sent" a lot faster if for example I could drag and drop the respective message of the thread that is still in "Sent" onto that button for the folder of the other messages in the thread. Or is there a better way to do this? Thanks a lot,

Christian

**Comment by Standard8** [comment]
Whilst I can see that something like this may be useful, I would be concerned that as far as drag and drop goes, it is pretty undiscoverable and unexpected.

What I think you may want is a feature like something in the context menu, which gives you direct options to move all messages in the thread to one of the folders the messages in the thread are already located within. However, that's really outside the scope of this extension.

So I think I'm going to close this out, as I don't really want to support this here.
