### ISSUE TITLE
Conversations doesn't work with latest Thunderbird beta (64)

### ISSUE THREAD

**Issue by scheinercc** [protz/thunderbird-conversations#1323]
* **Thunderbird version:** 64.0b1 (64-bit)
* **Thunderbird Conversation version:** 2.14.5 (last updated 25/11/18)
* **Operating System:** macOS

**What did you do?** Updated TB to latest beta

**What did you expect to happen?** Hoped for TC to continue working

**What actually happened?** Got an incompatibility warning and only the option to remove TC

**Comment by Standard8** [comment]
Duplicate of #1308
