### ISSUE TITLE
Inline reply does not allow for attachments

### ISSUE THREAD

**Issue by parrenin** [protz/thunderbird-conversations#1324]
* **Thunderbird version:**  60.2.1
* **Thunderbird Conversation version:** 2.14.5 
* **Operating System:** Debian Stretch

**What did you do?**

I replied inline to an email ("Reply" button at the bottom of the message) and then I clicked on "add attachment". 

**What did you expect to happen?**

A file chooser window should appear to select the file to attach.

**What actually happened?**

Nothing.

**Comment by Standard8** [comment]
Fixed by #1329.

I've just posted a new version of the add-on. It should be published soon (once reviewed).

**Comment by Standard8** [comment]
Thanks to @dethmetaljeff for fixing this.
