### ISSUE TITLE
[bug] copy mail-address icon moves modal

### ISSUE THREAD

**Issue by despecial** [protz/thunderbird-conversations#1326]
* **Thunderbird version:** 60.3.1 (64-Bit)
* **Thunderbird Conversation version:** 2.14.5
* **Operating System:** Mac OSX Mojave

**What did you do?** 
In the preview pane. Hovering a mail address opens a modal with more options. Including the copy icon after the mail address.

**What did you expect to happen?**
be able to click the icon

**What actually happened?**
when clicking on the icon, the whole modal moves down- and sidewards (east-right) and still shows up. no address copied.

**Comment by Standard8** [comment]
I can reproduce, for at least the first time. Not sure why this is occurring.

**Comment by Standard8** [comment]
I believe the new version for Thunderbird 68 should fix this when Thunderbird gets released.
