### ISSUE TITLE
60.3.3 (32-bit) on Win10 Pro issues 

### ISSUE THREAD

**Issue by snowbound** [protz/thunderbird-conversations#1330]
* **Thunderbird version:** 60.3.3
* **Thunderbird Conversation version:** 2.14.5
* **Operating System:**Win10 Pro x64

**What did you do?**
I noticed that messages were not being threaded properly so I ran the extension's assistant. When it completed running the messages were fine. However if I click on any particular mail box including just the Inboxes I loose the sorting and get messages no longer being shown in conversation view.

**What did you expect to happen?**
The messages should remain in conversational view like it did in the 52.x versions of Thunderbird

**What actually happened?**

**Comment by Standard8** [comment]
If the threading in the message list is wrong, then this is a Thunderbird specific issue - please file it there. We don't do anything that would affect that threading.
