### ISSUE TITLE
Provide option to delete an attachment from a received email

### ISSUE THREAD

**Issue by mMuck** [protz/thunderbird-conversations#1332]
Hi,
thanks for this very good extension! I want to contribute a feature request. :wink: 
Sometimes I have to clean up my mail folders and want to delete big attachments (some friends still use mails as a picture sharing service :rage:). At the moment this seems to be only possible by using the classic mail view as a work-around.
Is there a plan to include this in tb-conversations?
Thanks!

**Comment by Standard8** [comment]
Thanks, I don't have a plan to add it at the moment, but I'd accept a patch for it.

**Comment by Standard8** [comment]
I've just looked at the code again. I think you should be able to do this by right-clicking the attachment.

**Comment by mMuck** [comment]
@Standard8 Thank you very much!! I didn't found that before. Checked it - you are right. This works.
Perhaps it would be better to additionally place the well-known three-dot-menu next to the three buttons (show, save, open) at each attachment. Would help other users.
