### ISSUE TITLE
Conversations is not respecting the automatically mark messages as read preference

### ISSUE THREAD

**Issue by TasGeorg** [protz/thunderbird-conversations#1334]
Thunderbird version: 60.4.0
Thunderbird Conversation version: 2.14.6
Operating System: Win 10

We have a policy that when issues on the messages are not solved, then the respective messages are left unread as an indicaton. So even though someone may read a message that is marked as unread, the message stays unread until manually set to read state.

![image](https://user-images.githubusercontent.com/3384844/50535816-9831bc00-0b56-11e9-8cc8-74b83e258e1c.png)

This worked flawlessly until "Conversations" installation. Now when I click any message in the reading pane, the message is set to read status even though the option is deactivated.

When I disable the addon, normal behavior returns.

**Comment by Standard8** [comment]
As far as I can tell, this doesn't happen when selecting messages in the message list, only when clicking on a message in the actual conversation view. Not quite sure where this is happening yet.

**Comment by TasGeorg** [comment]
> As far as I can tell, this doesn't happen when selecting messages in the message list, only when clicking on a message in the actual conversation view. Not quite sure where this is happening yet.

You are correct! Sorry for not mentioning this in my initial post. Nevertheless it would be really useful if there was a flag/switch that messages read_state would only changed manually even when clicking on a message in conversation view.

Don't know if this issue is valid anymore. Maybe it should be flagged as a feature request.

**Comment by Standard8** [comment]
I think I've found this now, just need to do a little more testing to check I'm not breaking anything.

**Comment by Standard8** [comment]
I think 48d1104 should fix it. I've limited to the case where both automatically marking as read and marking as read with a delay are turned off, so it shouldn't affect others.

I think the best way to test it is to push it out and see what the reaction is.
