### ISSUE TITLE
Clicking reply answers the next email

### ISSUE THREAD

**Issue by parrenin** [protz/thunderbird-conversations#1336]
* **Thunderbird version:**
60.3.1

* **Thunderbird Conversation version:**
2.14.7

* **Operating System:**
Linux

**What did you do?**
I answered to an email.

**What did you expect to happen?**
The recipient of my email should be the sender of the email I received.

**What actually happened?**
The recipient is the sender of the next email.
Note that a restart of Thunderbird solved the problem.

**Comment by Yoshi8765** [comment]
Hi, I have this issue as well. Has led to some confused people! Really annoying and I would consider it quite high priority.

What happens to me is that if I'm responding to person A's email, when I click reply, it instead brings me to reply to another person's (let's say person B) email thread, but has person A as the recipient! Really annoying and potentially can lead to a breach of privacy! I'm being much more careful about reply windows now...

**Comment by Standard8** [comment]
Which reply buttons are we clicking here?

Has this happened recently in 68? We've done a big UI rewrite that may have helped things here.

**Comment by Standard8** [comment]
Unfortunately without more information we're not going to be able to fix this. Hopefully the UI rewrite has helped in the latest versions.
