### ISSUE TITLE
Encrypted message content not displayed

### ISSUE THREAD

**Issue by freakboy3742** [protz/thunderbird-conversations#1338]
* **Thunderbird version:** 60.4.0 
* **Thunderbird Conversation version:** 2.4.17
* **Operating System:** macOS Sierra

**What did you do?**

Enabled the Enigmail plugin (2.0.9) and Conversations (2.4.17) 

**What did you expect to happen?**

Content of PGP encrypted messages displayed in the message view.

**What actually happened?**

The Green "decrypted" lozenge is displayed, but the message content is not.

Interestingly, if you disable the conversations plugin, navigate to an encrypted message (thereby exposing the encrypted content), then re-enable conversations, the encrypted message content is displayed.

**Comment by Standard8** [comment]
This should be working in the latest conversations on Thunderbird 68. I've not had reports about this recently.
