### ISSUE TITLE
The second youtube video cannot be played under the text "Found a link to a YouTube video." : Video unavailable

### ISSUE THREAD

**Issue by sebma** [protz/thunderbird-conversations#1343]
Hi, I'm using : 

* **Thunderbird version: 60.4.0 (64 bits)**
* **Thunderbird Conversation version: 2.14.7**
* **Operating System: Ubuntu LTS 14.04.5**

**What did you do?**

I just opened one email containing 2 link to two youtube videos.
Here is the second link that can be played in html5 by firefox but not by your addon : https://www.youtube.com/watch?v=NvMNf0Po1wY

**What did you expect to happen?**

The video can be played.

**What actually happened?**

The video can not be played.

**Comment by protz** [comment]
I think we should remove these embeds feature. Neither the youtube one 
of the maps one work anymore.

**Comment by Standard8** [comment]
I think removing those is probably the right thing to do, I've never really used those previews even if they're there (and I think if we keep them they should be somehow inlined) and we haven't had complaints about the maps, so its probably the right thing to do.

**Comment by Standard8** [comment]
These have been disabled, and I'll be dropping the rest of the code for them soon.
