### ISSUE TITLE
Text formatting + insert link buttons (when replying)

### ISSUE THREAD

**Issue by spcmd** [protz/thunderbird-conversations#1351]
* **Thunderbird version: 60.5.0 (64-bit)**
* **Thunderbird Conversation version:* 2.14.7 (latest as of today)*
* **Operating System: Arch Linux**

When I use the reply button in the conversation view, there are no text formatting options (bold, italic etc.), and can't insert hyperlinks. Can we get text formatting and 'insert link' buttons?

**Comment by Standard8** [comment]
Sorry, the reply view is meant to just be for quick replies. We don't want to add more to it at this time.
