### ISSUE TITLE
EMail Bodies missing

### ISSUE THREAD

**Issue by aspconv** [protz/thunderbird-conversations#1354]
I am using thunderbird-conversations add on from last 10 days.It was working well till yesterday,but from yesterday I am facing one problem in it.If conversation is large i.e. more than 4-5 mails then, when we going to view any mail, its missing body contents of that mail.It is not happening for small conversations i.e. 3-4 mails. I tried disabling and enabling of add on but problem persist.I am using windows7 PC with 2 GB RAM ,Thunderbird 60.6.1 and conversation 2.14.7 version.Need help...

**Comment by MartinX3** [comment]
They arn't missing, they come after a long waiting time.
i7-6700HQ CPU with samsung 860 evo.
Thunderbird is just slower than without this addon.
I assume because all mails get loaded at the same time.
The new multi threading of thunderbird
1. doesn't help
or
2. isn't used in this addon

**Comment by Standard8** [comment]
Is this still an issue with Thunderbird 68 and the latest conversations (3.0.16)?

There's been a few changes that should help performance a bit. Though big message threads may still be a little slow to load.

**Comment by Standard8** [comment]
Closing out old issue, if this is still an issue in the latest versions, please turn on debugging in the add-on settings, and get a log of this happening. Then file a new issue.
