### ISSUE TITLE
Drag a message to & from a conversation

### ISSUE THREAD

**Issue by sambul13** [protz/thunderbird-conversations#1356]
The addon at times fails to add a certain message to a  conversation, or adds a wrong message to it for whatever reason, some mentioned in its Wiki. Is it possible to add a feature to the addon allowing a user to manually select the offending message in a list, and drag it to or from a conversation?

**Comment by Standard8** [comment]
Thunderbird is handling the threading here, conversations is just displaying what is given to it. So you should file a bug against Thunderbird.
