### ISSUE TITLE
Preferences are not available in Thunderbird 68

### ISSUE THREAD

**Issue by Standard8** [protz/thunderbird-conversations#1364]
For some reason preferences can't be accessed in Thunderbird 68.

I suspect this is mainly a Thunderbird issue, since we've set the right settings, however I'm taking the opportunity to see if we can rewrite these in a WebExtension compatible way, which will get the preferences button back into the add-ons list.

**Comment by Standard8** [comment]
I'm t

**Comment by Standard8** [comment]
I'm trying to submit the new version at the moment - unfortunately addons.thunderbird.net won't let me do it due to the use of the WebExtension experiments code. I've poked a few places, and hopefully it'll get moving soon.

**Comment by Marco-errebi** [comment]
With version 2.15.9 (11 September 2019) I can enter in extension preferences, but I can't save them.

**Comment by Standard8** [comment]
I've now been able to submit the new version (2.15.13), hopefully it'll be approved within a couple of days.
