### ISSUE TITLE
Open Conversation in New Tab Button Does Not Function Thunderbird 68

### ISSUE THREAD

**Issue by sahil48** [protz/thunderbird-conversations#1365]
* Thunderbird version: 68.0
    * Thunderbird Conversation version: 2.15.8
    * Operating System: Windows 10

The "Show this conversation in a new tab button in the message area does not work when I click it.

![image](https://user-images.githubusercontent.com/6100774/64697162-3019d080-d46e-11e9-9b2d-d50a20cc3f50.png)

Double Clicking the message open the conversation in a new tab.

**Comment by Standard8** [comment]
Thank you for the report, I've fixed this locally. I'm hoping to push out a new version in a day or two.

**Comment by Standard8** [comment]
I've pushed the new version to the add-ons server for review. Hopefully it'll be reviewed in a day or so.
