### ISSUE TITLE
Problem with visible messages after update TB to 68.1.0

### ISSUE THREAD

**Issue by Scebio** [protz/thunderbird-conversations#1367]
After update Thunderbird to 68.1.0 Thunderbird Conversations 2.15.12 doesn't work, I can't see any messages. In console I see:

Webconsole context has changed
TypeError: browser.storage is undefined
prefs.js:26:1
<anonimowa> moz-extension://ffbff5a5-d9e2-41b5-b35a-8212b9a0baae/prefs.js:26
TypeError: win.gBrowser is undefined
3 viewSourceUtils.js:82:11
onOpen chrome://global/content/viewSourceUtils.js:82
Removing unsafe node. Element: select. jquery-3.2.1.min.js:2:10353
Błąd naruszenia bezpieczeństwa: treść zawarta pod adresem „moz-nullprincipal:{bd78e92a-a15d-44a2-ab62-ea9afd6dd2f5}” nie może zostać wczytana lub powiązana z „chrome://conversations/content/stub.xhtml”.
Removed unsafe URI from element attribute. Element: a. Attribute: href. jquery-3.2.1.min.js:2:10830
Removing unsafe node. Element: select. jquery-3.2.1.min.js:2:10830
Flattening unsafe node (descendants are preserved). Element: input. jquery-3.2.1.min.js:2:23229
Flattening unsafe node (descendants are preserved). Element: form. 2 jquery-3.2.1.min.js:4:18409

Someone can help me? Thanks.

HP ProDesk 400 G1 MT
Windows 7 Proffesional 64-bit SP1

![console](https://user-images.githubusercontent.com/55733566/65488512-9c062b00-dea9-11e9-8e62-a02d9dbc7d8f.JPG)

**Comment by Standard8** [comment]
Can you confirm you're using the `pl` locale of Thunderbird?

I've just tried that here and it is working fine. Did you try restarting Thunderbird?

If that doesn't work, could you try uninstalling Conversations and then installing it again.

I'm wondering if something went wrong on upgrade, the message about browser.storage being undefined shouldn't happen with Thunderbird. It shouldn't be critical for the extension at the moment, but it does indicate something isn't working quite right.

**Comment by Standard8** [comment]
@Scebio did you see my previous comment?

**Comment by Standard8** [comment]
Unfortunately no response so I can't help further.
