### ISSUE TITLE
Can't read any mail (Security error)

### ISSUE THREAD

**Issue by YerayAlonso** [protz/thunderbird-conversations#1369]
* **Thunderbird version:** 68.1.1 (32-bit)
* **Thunderbird Conversation version:** 2.15.13
* **Operating System:** Windows 10. Version 1903 Build 18362.295

**What did you do?**
Updated Thunderbird from v60 to v68. Updated all the addons. Restarted Thunderbird. Uninstalled and reinstalled Conversations addon. Restarted Thunderbird,...

**What did you expect to happen?**
This addon to work fine ;)

**What actually happened?**
I can see the list of mails but I can't open any of them.

Here the error I see in the console:
```
Error de seguridad: el contenido en moz-nullprincipal:{ecdc6a04-5e7d-46fa-bb65-06c069b8f83a} no puede cargar o enlazar con chrome://conversations/content/stub.xhtml.
```

**Comment by Standard8** [comment]
Presumably the message pane is just blank?

Were there any other messages on the console? Maybe non-error ones?

If not, please could you try going to the add-on manager, selecting Preferences next to the Conversations add-on, and then at the bottom, enabling the "Debugging" option. Restart and then grab the console output after selecting a few messages. You should be able to `Select All` and then copy.

**Comment by YerayAlonso** [comment]
I went back to Thunderbird 60.9.0 and Conversations 2.14.7 and it works again.

**Comment by YerayAlonso** [comment]
I'll give that a try and let you know

**Comment by YerayAlonso** [comment]
I had to disable "Registers" in the console. Otehrwise the log is too long for this post...

> 
> Removing unsafe node. Element: select. jquery-3.2.1.min.js:2:10353
> Error de seguridad: el contenido en moz-nullprincipal:{c73056a3-3c31-469c-8f52-2822014984da} no puede cargar o enlazar con chrome://conversations/content/stub.xhtml.
> Removed unsafe URI from element attribute. Element: a. Attribute: href. jquery-3.2.1.min.js:2:10830
> Removing unsafe node. Element: select. jquery-3.2.1.min.js:2:10830
> Flattening unsafe node (descendants are preserved). Element: input. jquery-3.2.1.min.js:2:23229
> Flattening unsafe node (descendants are preserved). Element: form. 2 jquery-3.2.1.min.js:4:18409
> unreachable code after return statement
> jquery.tokeninput.js:470:4
> 2019-10-04 11:27:35	Conversations.Conversation	ERROR	TypeError: MailServices.accounts.defaultAccount is null
> log4moz.js:769
> uncaught exception: 2147746065 autosync.jsm:251:30
> uncaught exception: 2147746065 autosync.jsm:251:30
>

**Comment by Standard8** [comment]
Do you have any email accounts installed? I assume you do.

In any case, this seems to be the critical part: `TypeError: MailServices.accounts.defaultAccount is null`

That means Thunderbird doesn't know what the default account is. I'm not quite sure why this has changed between 60 & 68, as I thought that part of our code was still pretty much the same.

In any case, if you go to Tools -> Account Settings, select your primary email account (if you have more than one), then at the bottom in the "Account Actions" menu, select "Set as Default".

Hopefully that should get you running again.

**Comment by YerayAlonso** [comment]
> In any case, if you go to Tools -> Account Settings, select your primary email account (if you have more than one), then at the bottom in the "Account Actions" menu, select "Set as Default".

That solved the problem!
I can't say how there was no primary account set... 
Thank you!

**Comment by YerayAlonso** [comment]
I had an RSS account to the top of the list (moved with [Manually-Sort-Folders](https://github.com/protz/Manually-Sort-Folders/)). I'm not sure if this could be resetting the primary account.
