### ISSUE TITLE
tags in the conversation shows nothing but only texts in white

### ISSUE THREAD

**Issue by ADeeeee** [protz/thunderbird-conversations#1370]
* **Thunderbird version:** 68.1.1 (32 bits) on release channel
* **Thunderbird Conversation version:** 2.15.13
* **Operating System:** Windows 10 64 bits

**What did you do?**
I was editing the userChrome.css and also the color, names of the tags (label) and just found out this problem after it's done.

**What did you expect to happen?**
It should works like a charm as normally conversation did because I didn't change anything to this extension, maybe.

**What actually happened?**
The mail content with tag (label) shows nothing but only the name of tags in white without the background color of tags.

After that, I canceled all the changes I've done and even if reinstalling this extension. It doesn't work anymore. Don't know how exactly to reproduce this. 

Here's the example after I highlight the position it is:
![image](https://user-images.githubusercontent.com/35981633/66493108-0d6bed80-eae8-11e9-92b2-560b4a933f48.png)

The tag and color works good in TB:
![image](https://user-images.githubusercontent.com/35981633/66494000-8881d380-eae9-11e9-9dcf-cf1cccbfbe7d.png)
![image](https://user-images.githubusercontent.com/35981633/66494235-e7dfe380-eae9-11e9-8d56-5f7a4cfed5f5.png)

Do I have any chance to fix it? If there's more info you need, please guide me a little to get it from TB. Thanks.

**Comment by Standard8** [comment]
The only thing I can suggest is to a) make sure you haven't got a userChrome.css in the profile directory any more, and b) if that doesn't work try starting up Thunderbird with the `-purgecaches` command line flag (only one dash).

That would clear some of the fast load cache that Thunderbird has and it may help.

**Comment by ADeeeee** [comment]
@Standard8 
Thanks for the advice! But both doesn't make it back:

a) tried to rename the chrome folder in profile and the css disabled for sure
b) restarted TB with the command line flag in shortcut.

**Comment by Standard8** [comment]
My only other thought here is to re-install everything, and maybe clear out any other caches you can find. Unfortunately this seems somehow self-inflicted, and I can't think what would have caused this to break when it was working originally.
