### ISSUE TITLE
New emails in a focused conversation are unexpandable

### ISSUE THREAD

**Issue by Hi-Angel** [protz/thunderbird-conversations#1373]
* **Thunderbird version:** 68.1.1
* **Thunderbird Conversation version:** latest git, commit 3583885
* **Operating System:** Archlinux

**What did you do?**

1. Send yourself a email
2. Once the email received, focus it.
3. Reply the email with a new one, send it.
4. Wait for the 2nd email to appear in the conversation you currently have focused.
5. Click the header of the 2nd email to make it expand.

**What did you expect to happen?**

The email gets expanded.

**What actually happened?**

Nothing. If you double click the header, the text on it gets selected. Overall, I found no way to expand it other than to switch to another conversation and then back.

**Additional information**

Ideally, the newly accepted email should get automatically expanded, so you can see its content without clicking the header.

**Comment by Hi-Angel** [comment]
Okay, so I debugged it a bit: turns out, the new `messageHeader` has no event listeners set.

I also found in console what seems to be the reason:

```js
TypeError: "$(...).appendChild is not a function"
    _Conversation_appendMessages resource://conversations/modules/conversation.js:751
    _Conversation_onQueryCompleted_bug547088 resource://conversations/modules/conversation.js:473
conversation.js:475:17
```

The `751` line that errors out is this:

```js
      $(".message:last").appendChild($(".quickReply")[0]);
```

I haven't used js previously, so I'm not sure yet what to do about it.

**Comment by Hi-Angel** [comment]
Overall, I see many warnings in console, mainly from jquery file, and that "unsafe node was removed". I wonder if that somehow relevant.

Other than this blind guess, I haven't manage to advance any further in debugging this problem.

**Comment by Standard8** [comment]
The quick reply element `.quickReply` isn't being created at the moment as I disabled all that. You might be able to comment out those 5 lines relating to the quick reply, and then the code would continue on.

I don't know if it will succeed or not though, there may be other things broken in that flow as well.

I have a [new branch](https://github.com/Standard8/thunderbird-conversations/tree/message-list-react) I'm working on that is going to replace a lot of this, but it isn't quite ready yet, as it is still missing a few major features atm (namely lightning & enigmail integration which I'll hopefully get to soon).

**Comment by Hi-Angel** [comment]
> The quick reply element .quickReply isn't being created at the moment as I disabled all that. You might be able to comment out those 5 lines relating to the quick reply, and then the code would continue on.

Thank you, I confirm that commenting out lines as follows fixes the problem:

```diff
diff --git a/addon/modules/conversation.js b/addon/modules/conversation.js
index 90af284..983dd69 100644
--- a/addon/modules/conversation.js
+++ b/addon/modules/conversation.js
@@ -748,13 +748,13 @@ Conversation.prototype = {
 
       // Important: don't forget to move the quick reply part into the last
       //  message.
-      $(".message:last").appendChild($(".quickReply")[0]);
-      // Re-enable to reply dropdown for the message that previously had the
-      // quick reply.
-      $(".messageFooter").removeClass("hide");
-      if ($(".quickReply").hasClass("expand")) {
-        $(".message:last .messageFooter").addClass("hide");
-      }
+      // $(".message:last").appendChild($(".quickReply")[0]);
+      // // Re-enable to reply dropdown for the message that previously had the
+      // // quick reply.
+      // $(".messageFooter").removeClass("hide");
+      // if ($(".quickReply").hasClass("expand")) {
+      //   $(".message:last .messageFooter").addClass("hide");
+      // }
 
       // Notify each message that it's been added to the DOM and that it can do
       //  event registration and stuff...
```
I'll gonna use this fix locally until the new branch gets merged.

-------

I wonder though: how is that the error was basically about the `.appendChild()` function not existing, which doesn't seem to be related to quickReply anyhow; and yet you guessed it correctly?

**Comment by Standard8** [comment]
> I wonder though: how is that the error was basically about the `.appendChild()` function not existing, which doesn't seem to be related to quickReply anyhow; and yet you guessed it correctly?

It is probably actually that the `.message` class doesn't exist any more, and in this case, it just happens to be related to the quick reply code.

I've also just pushed my branch to master. There's a [few things to fix](https://github.com/protz/thunderbird-conversations/milestone/7) before it can be shipped, but it should be good enough to test and work with. Certainly be good to have someone else testing it as well.

**Comment by Hi-Angel** [comment]
Thank you, I confirm the problem is fixed!

**Comment by Standard8** [comment]
Great, thank you for confirming.
