### ISSUE TITLE
Assign "open" action to attachment thumbnail instead of "preview" option.

### ISSUE THREAD

**Issue by kbauer** [protz/thunderbird-conversations#1374]
Currently, the default action when clicking attachments is to preview them in Thunderbird. This is rarely desirable for me:

  - I prefer opening PDF files externally. 
  - For some filetypes, there is no preview support (e.g. MS Office files). For those, the large icon has no action assigned at all.

It would be nice to have an option to change the action assigned to clicking the thumbnail icon.

---------------

* **Thunderbird version:** 68.1.1 (64-Bit)
* **Thunderbird Conversation version:** 2.15.13
* **Operating System:** Open Suse Leap 15.1

**What did you do?** Click on a PDF attachment.

**What did you expect to happen?** A popup asking me to (a) Save the file, (b) Display the file using a chosen application and (c) to remember the choice.

**What actually happened?** The PDF opens in the previewer, regardless of whether I click the "eye" icon or the attachment thumbnail.

**Comment by Standard8** [comment]
I think using preview is the right thing to do - if we can, then we display it in the quick preview (this is the same for images). Although it might not be the preferred default for everyone, I think having the default as something that keeps you focussed in the same application is reasonable.

The other options are already easily accessible by the buttons to the side of the attachment - you have the option to download, or to view in the appropriate application (as well as the eye). There's also the right-click option available.

Whilst we could have an option, I'm inclined to say no at this time - having more options increases the complexity and testing routes, and as we don't have automated testing in place, this is more likely to cause an issue. We might be able to think about this in future once things settle down a bit more from the refactoring, however for now, I'll tag it as future and close it.
