### ISSUE TITLE
Latest master: fix Enigmail integration

### ISSUE THREAD

**Issue by Standard8** [protz/thunderbird-conversations#1377]
I've just pushed the message list transition of React to the master branch.

This has switched us away from jQuery.

At the moment, the Enigmail integration is not present. That needs adding back before we can ship it.

**Comment by Standard8** [comment]
I've got a WIP in #1400, feedback welcome according to the constraints noted in the PR.

**Comment by yoshimo** [comment]
Keep in mind that Enigmail is being integrated into TB itself right now, so depending on the release you are targeting you might have to redo it again soon.

**Comment by Standard8** [comment]
> Keep in mind that Enigmail is being integrated into TB itself right now, so depending on the release you are targeting you might have to redo it again soon.

The part we're redoing here is the display of the results onto the messages. The Enigmail side largely isn't changing. We may have to redo things once they integration with Thunderbird, although that may be true with other changes anyway.

Unfortunately we'd probably get too many complaints if we shipped latest master without Enigmail support, so we do need to fix this regardless.

Hopefully once we get past shipping latest master, we can start thinking more about the WebExtension APIs and what we'll need to change in Thunderbird to make this add-on simpler.
