### ISSUE TITLE
Thunderbird Add-on "Folder Account" not working properly in newer versions(68.1 and up)

### ISSUE THREAD

**Issue by dave1039** [protz/thunderbird-conversations#1379]
Thunderbird's add-on folder account does not work correctly. When right clicking on a folder and going into properties in the General Information tab there is an option at the bottom that let's you choose from what account you would like to send the email from (From Account). When clicking on this and changing to the right one then clicking OK it seems to stick, but then when you go back into folder options it's changed right back to "Use Default."

**Comment by Standard8** [comment]
Sorry, this is nothing to do with Thunderbird Conversations. You need to find the author's site for the folder account add-on if there is one.
