### ISSUE TITLE
Change to Standard Time 

### ISSUE THREAD

**Issue by koolx** [protz/thunderbird-conversations#1383]
Is it possible to change TB Convo to standard time instead of military time? Military time is confusing for many people. 

I got the latest TB Convo 2.14.7 with win 10 and TB 60.9.1.

**Comment by rnc** [comment]
Having read up what you are talking about, I think you mean its actually using a 24hour clock? Note that I think 24hour clock formatting is subtly different to military time. In that case its likely its nothing to do with Conversations, or even Thunderbird but your system settings.

**Comment by koolx** [comment]
No, 12 hour time is NOT subtly different from military time. Its different and hard to calculate for those in USA. Win 10 system settings has nothing to do with how time shows up in TBC since I got my settings show 12 hour time. 

Hope the dev can either fix or provide an option to change this.

Also, I'm unable to update TBC to the latest v2.15.13. TB wont update it for unknown reasons. Any ideas???

.

**Comment by Standard8** [comment]
> No, 12 hour time is NOT subtly different from military time. Its very different and hard to calculate for those in USA.

rnc was talking about 24 hour vs military time.

Could you give some examples and/or screenshots for what you are talking about? Is the information in the message view different from that in the message list, if so how?

As far as I can tell, we're generally using the same routines that Thunderbird would be. 

If you disable Conversations, and select a message thread in the list view (note this has to be a thread, rather than multiple non-threaded messages), does that show the same date/times that Conversations is showing?

Also, you could try going into the add-on preferences for conversations and toggling "No friendly dates".

> Also, I'm unable to update TBC to the latest v2.15.13. TB wont update it for unknown reasons. Any ideas???

You need to talk to their support for issues with that - see the Thunderbird section on https://support.mozilla.org/

**Comment by rnc** [comment]
12 hour style time is e.g. 1pm. 24 hour is e.g. 13:00. USA style military time is 1300. Note the lack of colon. My system (in the UK) is set up to use `en_GB.UTF-8` which gives me 24 hour style clocks e.g. 22:11. I don't follow how its 'hard to calculate? - I've just been teaching my 7 year old it! 
I have just experimented and run `LC_TIME=en_US thunderbird` and sure enough I get e.g. 9:42 PM in the message thread time/date (looking at a single message).

**Comment by koolx** [comment]
Its not hard for you to calculate it since youre in europe or canada and youre used to it. We're in america where we dot use that idiocy. How did you run 'LC_TIME=en_US'?

.

**Comment by koolx** [comment]
Hi  Standard8.. Below is my screen shot of the issue circled in red. Hope its fixed:

![1](https://user-images.githubusercontent.com/8130105/69835349-d88a3600-120e-11ea-9659-54a3b68f8444.png)

**Comment by Standard8** [comment]
Oh that line ... see it always helps to say exactly where ... those lines are taken directly from the header of the email. For example, if you open a message using the classic reader and select View -> Headers -> All, you'll see the exact same line. You'll also see the same line if you view the email source.

The date/time is already shown in the top-right corner of the message, with the full date/time information on the tooltip, or if you turn off "friendly dates" then it shows the full date/time straight away.

For those displaying the full information, the time of day sent, and the timezone might actually be useful, as that would give some context as to when the sender has sent it.

Given that, I'm inclined to not fix this - the date/time is already displayed in a convenient location, and those displays are intended to be straight from the headers themselves - which may give additional useful information to the user.

**Comment by rnc** [comment]
> Its not hard for you to calculate it since youre in europe or canada and youre used to it. We're in america where we dot use that idiocy. 

Please refrain from such language and apologise for it. Do you now understand that it isn't military time but a 24hour clock?

>How did you run 'LC_TIME=en_US'?

On the Linux command line.

**Comment by koolx** [comment]
> Please refrain from such language and apologise for it. Do you now understand that it isn't military time but a 24hour clock?

Apologize for what. Dude get outta here. Stop being a weirdo. 

> On the Linux command line.

I'm not on linux.

**Comment by koolx** [comment]
HI Standard8,

Would you tell me the **earliest** version after v2.14.7 that entering the enter key twice produced double line spacing? Would appreciate it immensely. 

.

**Comment by Standard8** [comment]
@koolx: Your wording was:

> > Its not hard for you to calculate it since youre in europe or canada and youre used to it. We're in america where we dot use that idiocy.
...
> Apologize for what. Dude get outta here. Stop being a weirdo. Btw its 12 hour not 24 hour.

Using "idiocy" is demeaning and rude. That's not acceptable and I am not going to tolerate it here.

> Would you tell me the **earliest** version after v2.14.7 that entering the enter key twice produced double line spacing? Would appreciate it immensely.

I have no idea, I thought it was actually Thunderbird's fault not Conversations.

**Comment by koolx** [comment]
> @Standard8: Your misinterpretation was:
> > Apologize for what. Dude get outta here. Stop being a weirdo. Btw its 12 hour not 24 hour.
> 
> > > Using "idiocy" is demeaning and rude. That's not acceptable and I am not going to tolerate it here.

"Idiocy" is NOT "demeaning and rude" since it was NOT targeted against any person, only the time convention itself. The person to whom I said this mentioned I should apologize for something I was not at fault for. Thats weirdo behavior on his part therefore my statement was justified. 

What you should've done was reprimand him for saying something that triggered such a response. If you still see what I said as rude, you shouldn't engage people since youre overly sensitive and easily misinterpret words.

> > Would you tell me the **earliest** version after v2.14.7 that entering the enter key twice produced double line spacing? Would appreciate it immensely.
>
>>> I have no idea, I thought it was actually Thunderbird's fault not Conversations.

How is it TB's fault since this issue was raised in Conversations? Arent you the dev? I never had this issue until I updated to v2.14.7 which I currently have now. If there's something I can do to fix it in code let me know specifically. 

.

**Comment by Standard8** [comment]
> @Standard8: Your misinterpretation was:
> 
> > Apologize for what. Dude get outta here. Stop being a weirdo. Btw its 12 hour not 24 hour.
> > > Using "idiocy" is demeaning and rude.
> 
> "Idiocy" is NOT "demeaning and rude" since it was NOT targeted against any person, only the time convention itself.

I interpreted as referring to the choice a nation has made, that I still think is a valid interpretation and as a result why I think you where using demeaning language.

> The person to whom I said this mentioned I should apologize for something I was not at fault for. Thats weirdo behavior on his part therefore my statement was justified.
> 
> What you should've done was reprimand him for saying something that triggered such a response.

No. They were trying to understand and clarify exactly what was going on. Your original report wasn't clear as to where you were seeing items, and as a result there was a confusion.

> If you still see what I said as rude, you shouldn't engage people since youre overly sensitive and easily misinterpret words.

I expect respectful, and constructive discussions. You turned this into something worse than it needed to be through your use of language. You have previously been disrespectful and that doesn't help with how you are interpreted. I am not encouraged to engage with you further.

In any case, I'm closing this issue out, as previously commented, these are the direct headers from the email itself, and there are other locations that we display the time in a more friendly format.

**Comment by koolx** [comment]
>I interpreted as referring to the choice a nation has made, that I still think is a valid interpretation and >as a result why I think you where using demeaning language.

Haha.. So you're talking on all nations's behalf? You're now the official UN representative of earth. Wow!! Smh

>No. They were trying to understand and clarify exactly what was going on. Your original report wasn't >clear as to where you were seeing items, and as a result there was a confusion.

You dont know what he was thinking. Since he wanted me to apologize for something I didnt do I hugely doubt YOU know what he was thinking. 

>I expect respectful, and constructive discussions. You turned this into something worse than it needed >to be through your use of language. You have previously been disrespectful and that doesn't help >with how you are interpreted. I am not encouraged to engage with you further.

Its not a one way street, let alone your street. We expect respect from everyone including YOU in the same way you expect respect from everyone. You destroyed this thread by defending your troll buddy with your immaturity. You keep disrespecting others as you have with me in the past. I won't tolerate this again as you're acting like a jackass.
