### ISSUE TITLE
Latest v2.15.13 Does Not Install on Win 10

### ISSUE THREAD

**Issue by koolx** [protz/thunderbird-conversations#1384]
I got the latest TB Convo 2.14.7 with win 10. I tried to install the latest TB Convo v2.15.13. But when I try to install it TB says its a corrupt file. Why is this happening?

**Comment by Standard8** [comment]
2.15.13 only installs with the latest Thunderbird 68.x versions. I would guess that you're trying to install into Thunderbird 60.
