### ISSUE TITLE
Convert `locale/` data to `_locales/` data

### ISSUE THREAD

**Issue by siefkenj** [protz/thunderbird-conversations#1389]
I don't know much about localization, but it seems like localization information should be moving into the `messages.json` file in `_locales/` and accessed via `browser.i18n` instead of accessed with `StringBundles`. I have crated a PEG.js script that will parse the existing `*.properties` files and output `messages.json`-compatible JSON.

```
start = body:(c:Comment t:Translation { 
	const {name, ...rest} = t; 
    return {[name]: {...rest, description: c}} 
} / t:Translation { 
	const {name, ...rest} = t; 
    return {[name]: rest} 
})* _ { 
	let ret={};
    for (const item of body) {
    	ret = {...ret, ...item}
    }
	return ret }

SubToken = "%S" / "%s"
NonSubToken = [^\n%]

TranslationLine = t:(NonSubToken)+ r:(s:SubToken t2:NonSubToken* { return t2.join("") } )* { 
	const retLine = t.join("") + r.map((l,i) => `$SUB${i+1}$` + l).join("")
    const ret = {}
    r.forEach((l,i) => { ret[`sub${i+1}`] = {content: `$${i+1}`} })
    if (r.length > 0) {
		return {message: retLine, placeholders: ret} 
    }
    return {message: retLine}
    } /
    r:(s:SubToken t2:NonSubToken* { return t2.join("") } )* { 
	const retLine = r.map((l,i) => `$SUB${i+1}$` + l).join("")
    const ret = {}
    r.forEach((l,i) => { ret[`sub${i+1}`] = {content: `$${i+1}`} })
    if (r.length > 0) {
		return {message: retLine, placeholders: ret} 
    }
    return {message: retLine}
    }

Line = [^\n]*

Comment = c:(_ c:("#" l:Line {return l.join("")})+ {return c})+  {return c.join("").trim()}

Translation = _ i:Identifier "=" l:TranslationLine {return  {name: i, ...l}}

Identifier = $([a-zA-Z] $[a-zA-Z0-9-.]*)

NewLine = [\r\n]

_ = [ \t\r\n]* {return null}
```

Since this would be a one time conversion, I didn't work on making the code pretty...To use it, copy the parser into the "PEG.js grammar" section of https://pegjs.org/online and then a `*.properties` file into the "input" section.

Since the actual conversion will touch a lot of code, I've made this bug for discussion rather than going forward with any changes.

**Comment by Standard8** [comment]
This is definitely a conversation I'd like to do sometime. The one issue at the moment is that the core of the add-on - the jsm files, stub.xhtml, the assistant, don't actually have access to the browser.* APIs.

We either need to:

* On startup (see background.js), load the strings and pass them through to the backend via an experiment-api. The backend could then store them and have them loaded. 
* Expose an API that's a listener, so that background.js (or a similar file) adds the listener on startup, then as translations are required, the backend triggers the listener with the appropriate arguments and gets the strings.

It might be worth holding off a little bit on this - after master is shippable, I'm going to investigate moving more things out of bootstrap.js, at which time this might be a good time to look at it.

I'm hoping to put together a bit of a roadmap soon to outline the various ideas I've got around this.

**Comment by siefkenj** [comment]
Ah, that does seem complicated. Is the eventual plan to have stub.xhtml being run as a "user script" (or whatever the Thunderbird equivalent is...)? I like the idea of message passing and having the background script grab all the info needed. One problem though is async vs sync. Since `.getMessage()` also does string substitutions, we really need to call the function at different times in the app and can't get away with calling it once at the beginning (or so I would assume. I'm not familiar enough with the different strings). If we decided to pass strings back and forth to the background process, we would need string substitutions to be async. This could be done if, in each component, we have the component fetch strings on mount or some such, but it is slightly awkward.

I suspect a custom React hook could be made to eliminate most of the work when using function components, but I haven't tried to implement anything like that before.

**Comment by Standard8** [comment]
A little bit of an update here - I've recently moved the setup assistant across to be a WebExtension page, which has moved those strings across.

I've also removed the rest of the pages.dtd files.

The gallery is currently blocked by some Thunderbird issues, but once we get a response on those we might be able to move that forward.

The pdf viewer I have an idea for that might be possible - hopefully some info on that soon.

The final bit would be stub.xhtml. I'm actually wondering if we should hold off on the strings for that until we're a bit further down the WebExtension path - we might have to make stub.xhtml a WebExtension page, at which point, the L10n issues would go away, as we could use `browser.i18n`. Still thinking about it, but at the moment we might just want to hold off on this a bit.

**Comment by siefkenj** [comment]
Now, we should be able to use `content/es-modules/thunderbird-compat.js` to imitative `browser.i18n`. It could even do a search and if it fails it could try the `StringBundle` method. Of course, none of the fallback will be needed if it is moved to a WebExtension page.

**Comment by Standard8** [comment]
I was thinking about this a bit earlier today. I think it might be useful to migrate the strings across now-ish if we can simulate the `browser.i18n` functionality.

That way, we can get all our strings from the WebExtension side of things and then when/if we do try and load stub.xhtml as a WebExtension page, we won't have to deal with the strings as well.

The only thing I wouldn't try to migrate at the moment are the `pdfviewer.dtd` strings - hopefully what I'm working on in #1417 will make those redundant.

**Comment by siefkenj** [comment]
I looked into this yesterday. Do you expect to migrate things gradually to the webextensionsAPI or all at once?

From the gradual perspective: what do you think about a message bus between "background.js" and the legacy extension through the experimental API? This would allow one to request the `browser.i18n` functions to be called directly from a webextension rather than having them be mocked. (I ran into an issue with mocking which was figuring out how to get files from the `_locale` directory to load. `ChromeUtils.import` didn't seem to work.)

It would seem we might still want a message bus even after we've migrated so that the functions we need can be called from the legacy script before the exact functions we need are finalized in an experimental API

**Comment by Standard8** [comment]
Just realised, this is all done now.

**Comment by siefkenj** [comment]
That's great news!
