### ISSUE TITLE
High CPU load at switching to Unified Inbox

### ISSUE THREAD

**Issue by sambul13** [protz/thunderbird-conversations#1390]
I'm running Conversations 2.15.13 with Thunderbird 68.3.0 64-bit in Win 10 64-bit v1909 with all updates installed. At Thunderbird Conversations install and when enabling the disabled addon, I reviewed and approved all settings changes it suggested.

I continuously have the same problem with the addon. At switching to Unified Inbox each and every time, it causes high CPU load that lasts 3-5 min after the Inbox is shown with all its content. During this time its still possible to work with the inbox, but Thunderbird and other PC apps get slow. When switching to any other Unified message box like Sent, there is no such issue, and the switch is smooth with split-sec CPU load as watched by Windows Resource Monitor. The Unified Inbox is the largest Unified message box I've.

I tried to delete all Inboxes content (10-15 Inboxes with 50 to 5000 messages in each), cleanup DBs, and redownload them from IMAP servers a couple times, but the bug persists. There was no such bug before last Thunderbird upgrade from immediate previous 32-bit version. It seems like both 32-bit and 64-bit TB manifest this bug.

There are no conflicting addons installed as per Conversations FAQ, and disabling the addon initially causes a long CPU load once, then everything back to normal, and switch to Unified Inbox is near instant with TB Threading On. How I can submit some logs, or can the developer fix that bug?

**Comment by sambul13** [comment]
I wonder if after some initial mailbox content sorting, in subsequent switches to Unified Inbox the Conversation addon can request from TB only content changed from the time of previous opening of the same Unified Mailbox, instead of asking all existing data each time all over again? This would not only fix this bug, but generally vastly improve mailbox opening speed.

**Comment by Standard8** [comment]
Were your issues just after upgrading?

It could be that for some reason Thunderbird had decided to rebuild the global database of messages in the background - that can cause high CPU for a period of time. You can sometimes see the rebuild in progress if you go to Tools -> Activity Manager and look for things like "indexing". You may have to pause a bit for them to be show up.

Conversations should only be active when you actually select messages, and then only to display those messages. If you've large message threads (which could be across folders), then it can be a bit slow to display them, we are working on changes that should improve that a bit.

> There are no conflicting addons installed as per Conversations FAQ, and disabling the addon initially causes a long CPU load once, then everything back to normal, and switch to Unified Inbox is near instant with TB Threading On.

The initial CPU load is highly symptomatic of Thunderbird's re-indexing happening. I can't do anything about that - that is a Thunderbird issue.

You could try turning on the debugging option in the add-on preferences, restart and then go to Tools -> Developer Tools -> Error Console, that should give messages as to what the add-on is doing at any particular time. You could then try switching to the unified inbox and see what happens.

Though I'd highly recommend you give it a few hours to settle first - Thunderbird can take quite a while to complete a re-index.

**Comment by Standard8** [comment]
I've also just remembered that the other option is to try turning off global indexing in Thunderbird's preferences. Restart, install the add-on, restart and turn indexing back on again. Then give it a few hours to settle (depending on how many messages you have), then see what happens.

**Comment by sambul13** [comment]
> Were your issues just after upgrading?
_Yes, no problems before the upgrade_

> Thunderbird had decided to rebuild the global database of messages in the background
_Nope. At launch, there is check for new messages and their indexing, but its just a few. At switching btw Inbox and Sent, and back, there are no new messages at all, and no indexing at all in Activity Manager._

> Conversations should only be active when you actually select messages, and then only to display those messages.
_Something doesn't stick here. High CPU load and Conversation active after switching for 3 min, errors in Console. With Conversation disabled - no problems, everything is fast and low CPU. At opening messages in Conversation - no CPU spike, no problems. Only switching to Unified Mailbox causes problems. I suspect, Conversation tries to resort already sorted old staff every time, the entire DB instead of just a few new messages._

```
Use of Mutation Events is deprecated. Use MutationObserver instead. calendar-views.js:97:9
TypeError: window is null
2 Overlays.jsm:61:9
2019-12-10 18:08:39	Conversations.MonkeyPatch	DEBUG	Document is not ready (uninitialized), waiting...

uncaught exception: 2147746065 2 autosync.jsm:251:30
2019-12-10 18:09:32	Conversations.MonkeyPatch	DEBUG	Document is not ready (uninitialized), waiting...

uncaught exception: 2147746065 autosync.jsm:251:30
2019-12-10 18:12:02	Conversations.MonkeyPatch	DEBUG	Hockey-hack

GEThttps://github.com/notifications/beacon/AAQ63BLQWXI6OXJH7ONWS53QX7Z4BA5CNFSM4JYQADJ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEGQWG2A.gif
[HTTP/1.1 200 OK 803ms]

POSThttp://ocsp.digicert.com/
[HTTP/1.1 200 OK 107ms]

2019-12-10 18:14:22	Conversations.MonkeyPatch	DEBUG	Hockey-hack

2019-12-10 18:14:40	Conversations.MonkeyPatch	DEBUG	Hockey-hack
```

**Comment by sambul13** [comment]
OK, now I removed all addons, reinstalled TB, rebuild each of 15 inboxes and sentboxes, but the sorting done by Conversation still persists, meaning there is same mix of received and sent emails in Unified Mailbox as it was created by Conversations. And the same high CPU load resulting from it. I suspect, in last release something changed in sorting scenario, and may be its not Conversations code problem, but how it forcefully resorted the default messages order, may be no longer compatible with  the last TB.

Just yesterday everything worked perfect. How I can revert to the default sorting order in Unified Mailbox threaded view? I mean, no Sent messages at all should show up.

**Comment by sambul13** [comment]
I think I may have found one possible reason for high CPU load. I've a webcam mailbox that sends shots periodically to the server. Now it contains locally and on the server about 30K messages. the Conversations addon included all these messages into Unified Inbox by error, since they are not conversations since those messages are all outgoing with image attachments, and no incoming.

Now each time I open Unified Mailbox, TB probably tries to sort these messages, and the list is very long. Strange enough, in the Cam Outbox, no such sorting occurs at opening the mailbox. So Conversations triggers some regular mailbox checks in TB that usually don't occur otherwise.

When Conversations is deleted, another bug prevents it from restoring the default mailbox sorting, and Sent messages still remain visible in Unified Inbox.

So I got 2 questions: 
1. what settings file should I delete or option change to restore the default sorting order, so only Incoming messages are seen in Unified Inbox, and no Sent messages?
2. how to delete Sent cam messages only locally, but leave them on the server? The TB Mail Acc & Sync window says: "to recover disk space, old messages can be permanently deleted, both local copies and originals on the server". But I don't need to delete originals on the servers, only local copies. Its not enough to restrict sync period, since TB downloads ALL message headers anyway, and later they are erroneously moved by Conversations into Unified Inbox.

**Comment by sambul13** [comment]
Updated Conversations to v2.15.4, but the above bugs remain. More bugs found:
- once a new message is received and added to Conversations view in Unified Inbox, Thunderbird message marks "sent" and "received" disappear from the view. All grouped messages get unmarked. To get them marked again, I had to disable Conversations and restart TB.
- once a new message is received and sorted to its conversation, the conversation 1st message doesn't change font to Bold again. So if all conversations are collapsed, there's no way to find out in Unified Inbox that a new message was received.
- Conversations shows Change Settings Dialog only after being disabled and then re-enabled.  There's no way to change any of these settings in Conversations GUI when its enabled. There's no Advanced Options link in Conversation options view, despite its mentioned in the Dialog.

**Comment by Standard8** [comment]
> Updated Conversations to v2.15.4, but the above bugs remain. More bugs found:
> 
>     * once a new message is received and added to Conversations view in Unified Inbox, 

To clarify: Conversations has no control over the Unified Inbox - that is functionality in Thunderbird that Conversations switches the UI to display. Apart from that we don't control that view.

> ... Thunderbird message marks "sent" and "received" disappear from the view.

Which view? The list of messages at the top, or the message display at the bottom.

Exactly when does this happen? Is this when you're receiving a message in a thread you've already got open or something else?

> All grouped messages get unmarked. To get them marked again, I had to disable Conversations and restart TB.

"Marked" as what? Read/Unread? In a specific folder? As threaded?

>     * once a new message is received and sorted to its conversation, the conversation 1st message doesn't change font to Bold again. So if all conversations are collapsed, there's no way to find out in Unified Inbox that a new message was received.

A collapsed message thread with an unread message in it will be underlined - that's standard Thunderbird behaviour and not part of Conversations.

>     * Conversations shows _Change Settings Dialog_ only after being disabled and then re-enabled.  There's no way to change any of these settings in Conversations GUI when its enabled. There's no Advanced Options link in Conversation options view, despite its mentioned in the Dialog.

We should probably make that available from the options again. What do you need to access there?

**Comment by sambul13** [comment]
I mean that the "Subject" column attributes (curved icons "sent" or "received") disappear from Unified Inbox view with grouped conversations, and instead Sent messages are marked as straight arrows in "Correspondents" column.  It happens on receiving a new message and auto sorting it into a conversation.

I think users should be able to revert options changed when enabling Conversations addon, instead of manually deleting files in Profile. For that reason Advanced Options view should be accessible. Some of those can be accessed from TB Settings, but TB Settings UI is way too complex for a novice user, and scattered through many access points, so ita hard to find the needed setting or even figure out it exists.

**Comment by Standard8** [comment]
> I mean that the "Subject" column attributes (curved icons "sent" or "received") disappear from any mailbox view with grouped conversations, and instead Sent messages are marked as straight arrows in "Correspondents" column. It happens on receiving a new message and auto sorting it into a conversation.

Ok, that's a Thunderbird issue and you need to raise it with them. You probably want to report it with full steps to repeat and maybe screenshots at https://bugzilla.mozilla.org.

> I think users should be able to revert options changed when enabling Conversations addon, instead of manually deleting files in Profile. For that reason Advanced Options view should be accessible. Some of those can be accessed from TB Settings, but TB Settings UI is way too complex for a novice user, and scattered through many access points, so ita hard to find the needed setting or even figure out it exists.

I've just filed #1393 for that.

**Comment by wsmwk** [comment]
@sambul13 Have you filed the Thunderbird bug?
And, no server side filters are involved, correct?

**Comment by sambul13** [comment]
@wsmwk I didn't have a chance yet due to holidays. No server side filters, otherwise the "Subject" column attributes would not appear or disappear on the same messages at each TB restart. May be you can file the bug? My experience with TB bugs fixing speed was the negative one, some took 20 years to move from one priority to another, and still do nothing  to fix, like no _Empty Trash_ RMC option in Unified Trash folder.

**Comment by wsmwk** [comment]
@sambul13 I don't plan to file a bug.  If the issue is important to you, then you are the best person to file it.

**Comment by sambul13** [comment]
Ooops... found that [Bug 1606094](https://bugzilla.mozilla.org/show_bug.cgi?id=1606094) .

**Comment by Standard8** [comment]
As far as I can tell, the issues here are mainly how Thunderbird behaves as a result of Conversations being installed. The performance issues would be there with Thunderbird as well, just triggered in different ways. Hence I think this should mainly be handled on the Thunderbird side rather than Conversations.
