### ISSUE TITLE
Message Tags not visible in the Reader UI

### ISSUE THREAD

**Issue by apaarfus** [protz/thunderbird-conversations#1391]
* **Thunderbird version:** 68.3.0 (32-bit)
* **Thunderbird Conversation version:** 2.15.13
* **Operating System:** Windows 7 Professional x64

**What did you do?**
1. Apply any built-in tag to a message
2. View the message in the Reader UI

**What did you expect to happen?**
In Thunderbird 60 with Conversation 2.15.13, the applied tag would be visible below the header information, similar to that in vanilla Thunderbird (albeit prettier).

**What actually happened?**
In Thunderbird 68.3.0 with Conversaiton 2.15.13, the applied tag does not appear in the header data for the message--however, there is still additional whitespace added between the header and message body sections of the Reader UI; indicating that it is simply not renderring the tag; even though it's attempting to handle the additional content.

### With Conversations Enabled
![Screenshot_4](https://user-images.githubusercontent.com/38731016/70477024-ef017e80-1aa5-11ea-9b48-1622e69f40a8.png)

### With Conversations Disabled
![Screenshot_5](https://user-images.githubusercontent.com/38731016/70477059-fcb70400-1aa5-11ea-9bbc-5efec5a50e4a.png)

**Comment by Standard8** [comment]
Thank you for the report, I remember fixing it on master when I was working on the React changes, and must have forgotten to check the release branch.

I've fixed it now, and will be putting a new version up in a little bit, it'll need add-on review from the Thunderbird people so it may take a day or two to come out.

**Comment by Standard8** [comment]
@apaarfus 2.15.14 got approval last night, quicker than I expected. If you go to Tools -> Add-ons, then click the Cog symbol, and Check for Updates, it should update.

You may need to restart to see the fix.
