### ISSUE TITLE
Make the setup assistant accessible from the options/preferences window again

### ISSUE THREAD

**Issue by Standard8** [protz/thunderbird-conversations#1393]
In 2.14.x the setup assistant was accessible from the options/preferences window.

I'd dropped it due to it not being quite as simple to get back, but we should re-add that option.

We could possibly just load it into a new tab - we might be able to do that within the WebExtension parts of Conversations.

It is probably also time we switched the setup assistant to a new tab anyway.

**Comment by sambul13** [comment]
It may not be enough to just unselect the options in the Setup Assistant for changed settings to revert back to defaults. Pls make sure that previously changed by SA options and sorting order are in fact reverted to default or original TB order.

**Comment by Standard8** [comment]
Just to note I've just pushed a fix for this. I'll be putting up a new version of the add-on for review in a bit, so hopefully it'll be released in a couple of days.
