### ISSUE TITLE
Split out Building/Dev/Test information into their own dev doc

### ISSUE THREAD

**Issue by Standard8** [protz/thunderbird-conversations#1394]
I think we should split out the building/dev/test information from the top-level README.md into docs/.

With new tools and options being added, we're going to want slightly more in-depth docs.

Maybe the readme can keep a quick-start, pointing to the other docs for more info.

**Comment by siefkenj** [comment]
PR #1397 does some of this

**Comment by Standard8** [comment]
I've just done some more rework and updated the docs a bit more. Calling this done.
