### ISSUE TITLE
Contact '+' button doesn't work at all

### ISSUE THREAD

**Issue by laspic** [protz/thunderbird-conversations#1395]
* **Thunderbird version:** 68.2.2
* **Thunderbird Conversation version:** 2.15.14
* **Operating System:**
Xubuntu Linux, 18.04.

**What did you do?**
I try to add a contact to my address book directly from the small popup on the name of a participant of a conversation, in clicking on the + button.

**What did you expect to happen?**
At least a reaction (whatever it is) !

**What actually happened?**
If I click on the + button, absolutely nothing happens.

**Comment by Standard8** [comment]
Thanks for filing this. I'd seen this recently, but unfortunately the fix didn't make it onto the release branch. I'm just fixing that now.

**Comment by Standard8** [comment]
I've just put 2.15.15 up for review which fixes this and a few other things. Hopefully it will get approved soon.

**Comment by laspic** [comment]
Everything works now ! Thank you !
