### ISSUE TITLE
Conversation not showing

### ISSUE THREAD

**Issue by jamaisx** [protz/thunderbird-conversations#1396]
Thunderbird version: 68.3.1 (32 bit)
Thunderbird Conversation version: 2.15.14
Operating System: Windows 10

What did you do?

Enabled extension, selected a threaded message, selected "show in conversation"

What did you expect to happen? related messages displayed in the preview section

What actually happened? nothing

Looked at the error console ther is an error

2019-12-18 15:18:30	Conversations.Conversation	ERROR	TypeError: MailServices.accounts.defaultAccount is null
log4moz.js:769
    append resource:///modules/gloda/log4moz.js:769
    log resource:///modules/gloda/log4moz.js:419
    error resource:///modules/gloda/log4moz.js:427
    _Conversation_onQueryCompleted_bug547088 resource://conversations/modules/conversation.js:611

I think that the object has to be checked for null before use it, don't know if it's only for me, but after upgrade from TB60 to latest 68 version, the configuration hast lost the default account 

Workaround: go to account settings, select the desired account then choose "set default" in the account actions list.

**Comment by Standard8** [comment]
Thanks for the report, it looks like I might have to try and implement a workaround for this. Though really it is Thunderbird's problem, as the default account should never be null.

I've filed an issue on your behalf here: https://bugzilla.mozilla.org/show_bug.cgi?id=1604790

If you have more information to add there that might be useful.

**Comment by Standard8** [comment]
I've just put 2.15.15 up for review which fixes this and a few other things. Hopefully it will get approved soon.
