### ISSUE TITLE
Messages added to wrong conversation

### ISSUE THREAD

**Issue by qazip** [protz/thunderbird-conversations#1398]
* **Thunderbird version:** 68.3.0
* **Thunderbird Conversation version:** Latest version at the time of writing this
* **Operating System:** Arch

**What did you do?**
I installed the addon, and many mails are grouped to the wrong conversation.

**What did you expect to happen?**
I expected the mails to be grouped in the right conversation.

**What actually happened?**
Well, the front fell off.

Maybe if I re-do the index or whatever it will be fixed? How do I do that?

Please tell me what additional information you require.. I don't want to post a screenshot of my mails here though.

**EDIT**: The messages that are in the wrong conversations have the following attributes:

- Different from address;
- Different to address;
- Same folder;

**EDIT2**: In fact, it is much worse than I thought. It is completely broken here.

![conversations_1](https://user-images.githubusercontent.com/16175716/71418791-54d43580-2664-11ea-9c25-9dfcd66eaa12.png)

First off, the messages on the left side (mail list) are grouped wrong. Messages B and downwards are not part of the conversation of message A. Now, the behaviour of the right panel (mail preview) is different, depending on weather the thread is collapsed or not:

- If thread is collapsed, clicking on A gives me the wrong messages on the right panel. It is a mess!
- If the thread is NOT collapsed, clicking on A gives me the right messages on the right panel. HOWEVER, the thread on the left side is wrong, that is, some messages are indented in the wrong thread!

I know this is extremely confusing, I don't know if I was clear enough. Please ask me questions and I'll do my best answering them.

**EDIT3**: I removed this add-on and it seems like the grouping of the messages is actually thunderbird's. So, this seems like a thunderbird bug, because faulty behaviour is still there with the addon removed..?

**Comment by Standard8** [comment]
If the grouping of messages is wrong, then that's Thunderbird's issue. The add-on doesn't change what is displayed in the message list.

I don't know if these will help in your case or not, it depends on exactly what's gone wrong:

* You can attempt to repair individual folders in Thunderbird, by right-clicking on them and selecting Properties, then select `Repair Folders`. That will rebuild the folder. Note that you'll likely loose tags and maybe the threading/sort settings.
* You can also try rebuilding the global index database - this is what conversations uses to inform it which messages belong to which conversation - https://support.mozilla.org/kb/rebuilding-global-database

If you need support direct from Thunderbird, please use https://support.mozilla.org/products/thunderbird

**Comment by qazip** [comment]
Hello @Standard8, you are right! Seems like Repair folders fixed the issue, though now messages are not being downloaded for some odd-reason. Anyway, that's another matter.

Sorry for the bother and thank you!

**Comment by qazip** [comment]
@Standard8, this is actually Conversation's fault. So, I uninstalled Conversations and repaired the folder and everything worked as it should. Then I installed conversations again and the threads became messed up again..
