### ISSUE TITLE
 Error after upgrade - Quick Reply 

### ISSUE THREAD

**Issue by marpow** [protz/thunderbird-conversations#1404]
Thunderbird version 68.3.1
Thunderbird Conversations version: 2.15.16
Upgrade: 02.01.2020

Error after upgrade:
 Quick Reply is temporarily disabled due to needing more work for Thunderbird 68. 

How to fix it ?
Regards

**Comment by Standard8** [comment]
That is not an error message. That's an information message that is letting you know we've intentionally disabled Quick Reply at the moment.

There have been large changes in how Thunderbird works in Thunderbird 68. As a result of those changes, and future changes, a large rewrite has been undertaken. The first stage of that rewrite skipped quick reply, as it had already been broken, and the main functionality of the add-on (the message display) could be restored earlier.

The first part of that large rewrite has finished, although there is still more work to do. I'm hoping to start work on re-enabling quick reply soon, but it is likely to take a while to get back to its full functionality. This work is tracked in issue #1361.

**Comment by Standard8** [comment]
If anyone wants to help with the work to fix it, I'm open to contributions, the add-on uses mainly javascript and reactjs. Some discussion as to exactly the right way to reimplement it will be needed.
