### ISSUE TITLE
Suddenly Double-click to open in new tab does not open email

### ISSUE THREAD

**Issue by warethis-dev** [protz/thunderbird-conversations#1406]
* **Thunderbird version:  68.3.1**
* **Thunderbird Conversation version: 3.0.3**
* **Operating System: Windows 10**

**What did you do? Double Click any email**

**What did you expect to happen? Open in new tab as it's set to do in the config**

**What actually happened? Not a thing**

Conversations add-on apparently updated today 1/3/2020 and immediately my double-click to open stopped working. I determined it was this add-on by disabling each add-on in turn. Conversations turned out to be the culprit. I just now discovered it had updated.

**Comment by Standard8** [comment]
Thank you for the report. We've just done a major rework to help support development going forward and we've obviously missed this.

I've just fixed the double-click to open, I'll land it in a moment and get a new version up for review by the add-ons team. Hopefully that'll be approved in the next day or so.

I think there's still an issue with re-expanding messages that were already expanded - I've just filed that as #1407. Hopefully I'll get time to look into that this weekend.

**Comment by Standard8** [comment]
Good news, this was approved an hour ago, so it should be available via Three-bar-menu -> Add-ons -> Add-ons, then click on Extensions, followed by the cog symbol and check for updates.

You may need to restart Thunderbird for it to full take effect.

**Comment by warethis-dev** [comment]
Works perfectly Thank you!
