### ISSUE TITLE
Message icon for popup menu for contact does nothing: ReferenceError: MailServices is not defined

### ISSUE THREAD

**Issue by MLopez-Ibanez** [protz/thunderbird-conversations#1409]
* **Thunderbird version:** ** 	68.2.2 **
* **Thunderbird Conversation version:** 3.0.3
* **Operating System:** Linux

**What did you do?** Click in the message icon shown in the popup that appears after hovering a recipient name in the message pane

**What did you expect to happen?** Open a new compose window to send an email to that contact.

**What actually happened?** Nothing. Log shows:

JavaScript error: chrome://conversations/content/reducer.js, line 459: ReferenceError: MailServices is not defined

**Comment by Standard8** [comment]
Thank you for the report. I've just fixed the issue and uploaded a new version (3.0.5) to the add-ons site for review.

Hopefully it'll be approved soon and then the update will be available.
