### ISSUE TITLE
Deleting, detaching, saving, opening attachments via right click has stopped working

### ISSUE THREAD

**Issue by Jakethethird** [protz/thunderbird-conversations#1414]
* **Thunderbird version:** 68.2.2
* **Thunderbird Conversation version:** 3.0.3
* **Operating System:** Ubuntu 18.04

**What did you do?**
Big attachment, wanted to delete it. Right click on Icon at end of email and choose "Delete Attachment". Nothing happens. Other menu options - Detach, Open and Save - also have stopped working.

Tested on several other emails with different types and sizes of attachments.

If I view using the Classic Reader, I can perform these operations.

It used to work - I did it often.

**Comment by Standard8** [comment]
Thank you for the report, I can see the breakage as well. I think I forgot to revisit this bit in the major rewrite that we did.

I'll try and take a look this weekend.

**Comment by Jakethethird** [comment]
Possibly related, when the attachment is an .ics file, it has always been possible to drag and drop this onto the Today Pane on the right and it puts it into the Lightning calendar. This seems to have stopped working also. 

This is the only way (to my knowledge) to simply move calendar requests (with .ics attachments) into the calendar, but seems to be little known - I found it described in a forum somewhere.

Anyway, thanks for such a great addon.

**Comment by Standard8** [comment]
Hmm yeah, I might have skipped the dnd functionality as it wasn't obvious at the time.

Surely you can add calendar requests using the notification bar that pops up when it detects an invite? If not, that sounds like a bug in Lightning's functionality.

**Comment by Standard8** [comment]
I've now fixed the context menu issue, and I've just submitted a new version to the add-ons site for approval. It might take a few days for it to get approved.

The drag and drop issue I've split out to #1418. Should be fairly simple, but I need to look at other things for a day or two.
