### ISSUE TITLE
Drag and drop of attachments is not implemented after React switch

### ISSUE THREAD

**Issue by Standard8** [protz/thunderbird-conversations#1418]
During the React rewrite I dropped the support for drag and drop for attachments as I wasn't sure how to do it at the time.

I then forgot about putting it back. We should probably be able to add it back fairly easily. The old drag handler code can be found here: https://github.com/protz/thunderbird-conversations/blob/2.14%2B/modules/message.js#L1030

**Comment by Standard8** [comment]
This needs to be implemented somewhere around here: https://github.com/protz/thunderbird-conversations/blob/4afe1cbe1820b67be510b7dadf4b9c01d3b3c14d/addon/content/attachments.jsx#L91 (and the todo removed).

**Comment by Tha14** [comment]
Do we have any update on this? Some of my clients are relying on this function a lot. Thank you.

**Comment by Standard8** [comment]
Sorry, this is not a priority for me at the moment. I'm focussing on some of the other timing and startup issues, as well as moving more of this to a WebExtension. I'm also busy with work this week, so I'm unlikely to get time to do any patches for Conversations at all.

I'm quite happy to accept patches and can guide, I just can't commit to this at the moment.

**Comment by gilles008** [comment]
Hi folks, I can drag files/attachments into a TB message but can't drag a received attachment out of TB as I used to when the Conversations extension is enabled. 

Is this report particularly dealing with the latter?... or is it referring to dragging files into TB, which, as stated above, works at my end.

Could someone clarify please?
Cheers!

**Comment by Tha14** [comment]
Yes, this is about dragging and dropping attachments from TB.

**Comment by gilles008** [comment]
Thanks for the quick reply :). As I mentioned, at this end, dragging "into" works.. it's the dragging "out of" which no longer works.
It's not the end of the world but keeping fingers crossed for a fix to this handy feature.

**Comment by Standard8** [comment]
I think I've now fixed this in https://github.com/protz/thunderbird-conversations/commit/d32d6c66233dd94fb26a20f762e752b02f7269b9. I've basically ported the exact same code across from an older branch, as far as I can tell it is working as well as it used to.

I'm hoping to push out a new version for review soon, though it may take a few days to be approved.
