### ISSUE TITLE
Individual messages of a thread are not focused on in message preview pane

### ISSUE THREAD

**Issue by fridgelord** [protz/thunderbird-conversations#1428]
* **Thunderbird version:** 68.4.1
* **Thunderbird Conversation version:** 3.0.10
* **Operating System:** Windows 10

**What did you do?**
Click on a message of a **collapsed** thread in message preview window.

**What did you expect to happen?**
Before the update individual message could be highlighted (with a slight shade around the message frame) and focused on by clicking on it in the message preview pane and you could use keyboard shortcuts on this particular message. For example CTRL+(SHIFT)+R would reply to this message (this might be related to Issue #1399, it is needed not only to focus on the message preview pane, but also on particular message). F & G would move between messages in the thread. It was possible to tag single message using numbers.

**What actually happened?**
If thread is collapsed, CTRL+(SHIFT)+R has no effect (unless there is only one message in the thread), F & G move between threads and not messages. Tagging with numbers tags all messages in thread.

**Comment by Standard8** [comment]
Thank you for the explanation. I must admit I didn't fully understand some of that code or what it did, which is why it hasn't been re-implemented.

I think it makes sense to have this, so I'll mark it as a bug, and hopefully someone can find time to get to it soon.

**Comment by Standard8** [comment]
@siefkenj I was wondering if you might like to take this one.

I think the old handlers for this were in message.js on the 2.14.x branch: https://github.com/protz/thunderbird-conversations/blob/2.14%2B/modules/message.js (look for `KeyListener`).

We could maybe just implement one part first, e.g. reply/forward and then think about the rest.

**Comment by Standard8** [comment]
I believe this is now fixed by #1432.
