### ISSUE TITLE
Deleting eMail in a tab: eMail deleted, tab displays empty, tab does NOT close

### ISSUE THREAD

**Issue by WalZyl** [protz/thunderbird-conversations#1434]
* **Thunderbird version:** 68.4.1
* **Thunderbird Conversation version:** 3.0.10
* **Operating System:** Windows 10 Pro

**What did you do?**
Load email in a tab. Delete the eMail using "Delete this conversation" button (right-hand side). 

**What did you expect to happen?**
eMail is deleted, tab is closed. Inbox tab or anther tab is displayed / got focus.

**What actually happened?**
eMail text disappears, tab displays empty/blank surface, BUT remains open. 
The eMail is deleted (checked by looking at the original folder).

**Comment by WalZyl** [comment]
I suspect that this issue is in row with #1429 and #1426: asynchrony between actual action by TB and display by Conversations. It's not a big deal for me, nevertheless, somebody could confirm that !? 

I'm convinced that this will disappear once the transition to WebExtensions will be successful.

**Comment by Standard8** [comment]
This was just a simple coding error that had crept in that I've just fixed on master. I'll hopefully push a new version with it out in a day or two.

**Comment by Standard8** [comment]
FYI 3.0.11 is now released, so should be fixed once you've updated to that (possibly only after restart)

**Comment by WalZyl** [comment]
I confirm the fix. Thx.
