### ISSUE TITLE
Can no longer see other conversations for sender

### ISSUE THREAD

**Issue by snowbound** [protz/thunderbird-conversations#1436]
* **Thunderbird version: 	68.4.2**
* **Thunderbird Conversation version:3.0.11**
* **Operating System:Windows10 Pro 1909**

**What did you do?Clicking on sender in message header**

**What did you expect to happen?the popdown menu use to give me the ability to see other prior conversations with the sender**

**What actually happened?That option is no longer showing up**

**Comment by Standard8** [comment]
You shouldn't have to click the sender, just hover over them.

I've just been trying it here and it generally seems to work, although sometimes there can be a little delay.

Are you seeing this on just one contact or all of them?

If you go to the three-bar menu, then Tools -> Developer Tools -> Error Console, do you get any errors appearing on there when you click the button to see the conversations?

**Comment by snowbound** [comment]
It was an extension I was using. I had to blow it away to get the functionality back

**Comment by Standard8** [comment]
Do you know which extension it was?

**Comment by snowbound** [comment]
Sorry I do not

**Comment by Standard8** [comment]
Ok thank, I'll close this out as I don't think there's any more we can do here.
