### ISSUE TITLE
Not seeing replies when clicking on message in inbox

### ISSUE THREAD

**Issue by snowbound** [protz/thunderbird-conversations#1437]
Thunderbird version: 68.4.2
Thunderbird Conversation version:3.0.11
Operating System:Windows10 Pro 1909

**What did you do? Click on message in IMAP inbox of an account**

**What did you expect to happen? I should see all my replies to the message**

**What actually happened?I see none of my replies only subsequent in box messages from the sender.  View > Sort By > Threaded  is enabled**

**Comment by Standard8** [comment]
Is this the result of the other extension as per your other issue?

**Comment by snowbound** [comment]
It probably was. I believe I wound up removing conversations completely and reinstalling it.

**Comment by Standard8** [comment]
Ok, I'll close this out as I'm not sure there's anything else we can do.
