### ISSUE TITLE
Attachements drag and drop issue

### ISSUE THREAD

**Issue by merlin-new** [protz/thunderbird-conversations#1438]
* **Thunderbird version: 68.4.2 (32-Bit)**
* **Thunderbird Conversation version: 3.0.11**
* **Operating System: Win 10 Pro**

**What did you do? Tried to drag a pdf attachement to desktop (download), tried to drag a pdf and drop a pdf attached to an Email to a new Message**

**What did you expect to happen? That pdf can be dragged and dropped to desktop or a 'new message window'**

**What actually happened? showed a symbol 'forbidden (no parking road sign)**

**Comment by Standard8** [comment]
Duplicate of #1418

**Comment by merlin-new** [comment]
Sorry! Hope it can be fixed in teh near future! Thanks
