### ISSUE TITLE
How to make the most recent email on top of conversations?

### ISSUE THREAD

**Issue by GitgPHub** [protz/thunderbird-conversations#1440]
I would like to know if it’s possible (or will eventually be possible) to sort the emails of a conversation in descending order. I mean that the most recent email would be on top.

Thanks for your help and thanks for your plug-in. It improves my appreciation of Thunderbird greatly.

**Comment by kylesorkness** [comment]
The ["I want the most recent message on top" item in the FAQ](https://github.com/protz/thunderbird-conversations/wiki/FAQ#message-display) seems to address this.

**Comment by Standard8** [comment]
The FAQ item is indeed the original reason. I suspect it might be simpler with our current code, but I'm still inclined to wontfix this at the current time. The code base is under heavy re-organisation to support future versions of Thunderbird, therefore I'm keeping it as simple as possible for now, to make that re-org easier.

We might be able to do something after that's happened, but realistically that's at least a year or two away.
