### ISSUE TITLE
Bug?: All tabs have title "Coversation Reader"

### ISSUE THREAD

**Issue by sahil48** [protz/thunderbird-conversations#1444]
* **Thunderbird version: 68.5.0**
* **Thunderbird Conversation version: 3.0.12**
* **Operating System: Windows 10**

**What did you do?** I double clicked to open a message Thunderbird

**What did you expect to happen?** I expect the tab to show the subject line as the name

**What actually happened?** The Tab is Titled as "Conversation Reader". This makes it difficult to select the correct conversation thread because every tab is titled Conversation Reader.

![image](https://user-images.githubusercontent.com/6100774/74871429-73d00a80-5329-11ea-8bee-2f8534efdcb6.png)

**Comment by Standard8** [comment]
Thanks for reporting this, you're totally right, looks like setting the title got lost during some of the rewrites. I'll get that fixed, hopefully a new version will be improved in a day or two.
