### ISSUE TITLE
Remote Content Preferences should be available 

### ISSUE THREAD

**Issue by fyodorovich** [protz/thunderbird-conversations#1453]
* **Thunderbird version:**  	68.5.0
* **Thunderbird Conversation version:** 	3.0.16
* **Operating System:** Mac OS X 10.13.6

**What did you do?** Received an HTML formatted email. I wanted to view the images which were being blocked by TB.

**What did you expect to happen?** I expected to be able to find the preferences button that would allow me control the remote content settings for that message. The options to control the display of the remote content is important. We need to be able to access that functionality. 

**What actually happened?** I wasn't able to find the button until I disabled TB conversations. As soon as I did that, button was displayed.

**Comment by Standard8** [comment]
Do you not see a bar like this?

<img width="716" alt="Screenshot 2020-03-04 at 08 26 42" src="https://user-images.githubusercontent.com/520844/75863564-9ae20e00-5df8-11ea-82d2-681d107b420b.png">

This was on the github email I got for this issue.

**Comment by Standard8** [comment]
Sorry, but without more information I can't help here.

**Comment by fyodorovich** [comment]
No, that bar is not visible. That is exactly the sort of thing I was looking for. 

( Sorry, I thought I had replied 14 days ago when you posted. )
