### ISSUE TITLE
Feature request: Button to 'Edit/Add contact' for email addresses in the header

### ISSUE THREAD

**Issue by akwala** [protz/thunderbird-conversations#1454]
* **Thunderbird version: 68.4.1 (64-bit)**
* **Thunderbird Conversation version: 3.0.12**
* **Operating System: Kubuntu 18.04**

**What did you do?**
Hovered over From/To/etc. address in the email header. This showed a box with buttons to perform actions on the email address, such as Copy, Send email, Recent conversations, etc.

**What did you expect to happen?**
See a button to Edit the Contact corresponding to the email address if it exists in an Address Book, or a button to Add the Contact if the email address is not in an Address Book,

**What actually happened?**
There isn't a button to Edit/Add the Contact corresponding to an email address -- have to use "view using classic reader" in order to Edit/Add a Contact.

**Comment by Standard8** [comment]
If you hover over the contact, then click the little down-arrow:

<img width="174" alt="Screenshot 2020-03-07 at 12 51 37" src="https://user-images.githubusercontent.com/520844/76143809-72654880-6072-11ea-9070-6496198cae58.png">

You then get the option:

<img width="209" alt="Screenshot 2020-03-07 at 12 52 16" src="https://user-images.githubusercontent.com/520844/76143817-801ace00-6072-11ea-9ce1-56b1dfcad6d4.png">

The plus icon there - it is an edit icon if you already have a contact.

I think I might actually change the popup and drop the expand/collapse arrow. I'm not sure it is that useful, and requires an extra click, when really we don't want to have one.

**Comment by Standard8** [comment]
I've just changed the layout of the popup slightly, so we don't have the expander any more. Hopefully that'll be better. Should be released in the next few days.
