### ISSUE TITLE
Attachments are only shown when messages are downloaded for offline use.

### ISSUE THREAD

**Issue by nicolasbry** [protz/thunderbird-conversations#1457]
* **Thunderbird version:** 68.4.2
* **Thunderbird Conversation version:** 3.0.17
* **Operating System:** mac osx 10.13.6

**What did you do?** open the message with pdf attached

**What did you expect to happen?** list of joined is shown

**What actually happened?** only pictures are shown not pdf
![capture 2020-03-28 à 12 14 52](https://user-images.githubusercontent.com/31948836/77821901-12504800-70ee-11ea-8511-f349c99fc585.png)

**Comment by Standard8** [comment]
What makes you think that message has a pdf attached? There's no attachment symbol (the paper clip).

If you go to the three-dots, and select "View in classic reader", does that display show a pdf?

**Comment by mbarper** [comment]
I have the same problem. 

With classic reader shows the pdf attach.

**Comment by labachevskij** [comment]
I have a similar problem (with a twist!): I have three accounts on Thunderbird (all three gmail accounts), with as far as I can see the same account configurations (on the Thunderbird Account settings pages).
In two of the three accounts, attachments are not shown (although the show up as paperclip next to the email in the inbox pane and they are properly shown in classic reader). In the third account the attachments are properly shown also by thunderbird conversations.

Thunderbird version: 68.4.1
Thunderbird-conversations: 3.0.17 (had the issue already in 3.0.12)
OS: Ubuntu 19.10

Anything I can do to help debug this behaviour?

**Comment by matlcnieu** [comment]
Hi,
I just found out that i have the same problem

Thunderbird version: 68.6.0 
Thunderbird-conversations: 3.0.17
OS: Windows 10

I have 5 accounts. My gmail shows SOME OF the .pdf
my personal one "planet hoster", shows SOME OF the .pdf
that's weired

I have to click on "view using the classic reader" to see the attached files

**Comment by Standard8** [comment]
A few ideas:

1. Look at the error console to see if there's any errors raised when you're displaying the message. You can access it from the three-bar menu -> Tools -> Developer Tools.
2. Look at the message sources to see if you can see anything different about how the pdfs are referenced. Maybe the content-type is different or something?
3. (probably mainly in @labachevskij's case) Go into Preferences (or Options) -> Advanced -> General -> Config Editor. Accept the warning if there is one. Search for `mail.` and check there's no obvious/unexpected differences between the settings for accounts and servers.

**Comment by DanieLoche** [comment]
Hello, 
Here is a mail source with an attachment working for me : (only the attachement part, most of the pdf data removed)
`------=_=-_OpenGroupware_org_NGMime-1300-1584626230.293360-10------
Content-Type: application/pdf
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename="=?utf-8?q?Continuite=CC=81_services_Administratifs_du_LAAS=2Epdf?="
Content-Length: 130207
[...] Y2Q0ZDcyN2I0YmE1YTcwZmJlMDkzODRm
ZjYyMmM1PiBdID4+CnN0YXJ0eHJlZgo5NTMzOQolJUVPRgo=

------=_=-_OpenGroupware_org_NGMime-1300-1584626230.293360-10--------`

And a source from an email with a pdf attachment not working for me : 
`--------------276EFB03385F8FA2B19A0070
Content-Type: application/pdf;
 name="Volume 6.pdf"
Content-Transfer-Encoding: base64
Content-Disposition: attachment;
 filename="Volume 6.pdf"
[...]ZDRhYmVmMjNkOTVmMGUxZjhmMzIwPgo8ZWQ4ZTJiODZjNjNkNGFi
ZWYyM2Q5NWYwZTFmOGYzMjA+IF0gPj4Kc3RhcnR4cmVmCjY5ODc5MAolJUVPRgo=
--------------276EFB03385F8FA2B19A0070--`

I also have issues with other attachment file types as simple as images, here is the mail source : 
`--------------7ADAF31C24A0118E2E9C76F1
Content-Type: image/jpeg;
 name="IMG_8495.JPG"
Content-Transfer-Encoding: base64
Content-Disposition: attachment;
 filename="IMG_8495.JPG"
[...]`

I suspect the ";" at the end of the Content-type line being the cause of the issue...

**Comment by labachevskij** [comment]
Hi, thanks for the suggestions:
> 1. Look at the error console to see if there's any errors raised when you're displaying the message. 

No error there seems to be directly related to this issue.

> 2. Look at the message sources to see if you can see anything different about how the pdfs are referenced. Maybe the content-type is different or something?

Does not seem to be the case. Images are properly displayed inline, pdfs and zips are not shown. Does not look like it is sender dependent: same sender to different accounts, attachments displayed in one and not in the other. All incoming email to the two "bad" accounts is not showing attachments, all incoming email to the good one is showing.

All the accounts are gmail-based (although not all @gmail.com)

> 3. (probably mainly in @labachevskij's case) Go into Preferences (or Options) -> Advanced -> General -> Config Editor. Accept the warning if there is one. Search for `mail.` and check there's no obvious/unexpected differences between the settings for accounts and servers.

I checked it, nothing seems to stick our. For prefs.js I went on and displayed all contents of mail.identity and mail.server for the three identities, but there seems to be no difference (except the obvious ones).

I was looking in particular for things related to attachments, but they do not seem to be account related. 

Will keep digging, if anyone has additional suggestions on where to look, they're welcome.

**Comment by DanieLoche** [comment]
Okay, just got a new clue : 
- Everything is completely working okay on my Windows 10 installation (thunderbird 32bits, version 68.6.0).
- It's on my Linux (Ubuntu) station that I have the problem for some attached files (not only pdf). Version is 68.4.1, 64 bits.

**Comment by Standard8** [comment]
Another thought, if you go to the folder these emails are in, right-click and select Properties, is "Include messages in this folder in Global Search results" checked? Also on the Synchronisation tab, is "Select this folder for offline use" checked?

**Comment by mbarper** [comment]
In my case the global search is enabled but the offline use don't. It is needed the offline use to be able to see an attachment?

**Comment by labachevskij** [comment]
> Another thought, if you go to the folder these emails are in, right-click and select Properties, is "Include messages in this folder in Global Search results" checked? Also on the Synchronisation tab, is "Select this folder for offline use" checked?

The "Offline use" did the trick (all my accounts were already in Global search). Thanks a lot!

**Comment by DanieLoche** [comment]
It did the trick for me too ! 
I enabled the "Offline use" option in the "Synchronisation" panel. :) 
It was enable on another folder where I can see the attachment.

I suggest to edit the title / description of the issue in order to fit the fact that not only PDF are concerned (at least).

**Comment by Standard8** [comment]
I've just fixed this in 7ccfecb1e - I took a look and realised that when I did the rewrite, I'd missed porting the piece of code that handles attachments when the message hasn't been downloaded for offline use.

I'm hoping to release this in the next couple of weeks, though the issues we're having in #1481 might delay that a little.
