### ISSUE TITLE
"Jump to this folder" button not working

### ISSUE THREAD

**Issue by mbarper** [protz/thunderbird-conversations#1459]
* **Thunderbird version: 68.4.1 (64-bit)**
* **Thunderbird Conversation version: 3.0.17**
* **Operating System: Ubuntu 19.10**

**What did you do?** Click on a conversation. Detect one of the messages is in another folder. Click on "Jump to this folder" buttom.

**What did you expect to happen?** As usally, clicking on that buttom take me to the message in the original folder containing that message of the conversation

**What actually happened?** Nothing

In the error console it shows this on each click:
![image](https://user-images.githubusercontent.com/3797030/78160460-45733e00-7444-11ea-99a5-957e30a77544.png)

**Comment by Standard8** [comment]
Thank you for the report. I've just fixed this in the source code today. It'll probably be sometime in the next week or two before we get a new version out.

**Comment by mbarper** [comment]
It is working fine now. Thank you very much!
