### ISSUE TITLE
File extraction impossible

### ISSUE THREAD

**Issue by matlcnieu** [protz/thunderbird-conversations#1460]
* **Thunderbird version:** 68.6.0
* **Thunderbird Conversation version:** 3.0.17
* **Operating System:** Windows 10

Hi, 
I'm French, very first time on Github, i've read the Github's "how-to" and i'm doing my best to make this request in the good way.

I love your addon. It's definitly a reason why i'll keep using TB for a while.
But...
i cannot find how to "extract" attached files. It looks like it's impossible. It's important for me cause it helps to save space...
Are you working on this feature please?

Thanks and take care
Mathieu

**Comment by Standard8** [comment]
You should be able to right-click on the attachment and select "Detach Attachment" (or delete if you don't want to save it):

<img width="251" alt="Screenshot 2020-04-02 at 10 23 57" src="https://user-images.githubusercontent.com/520844/78232445-2e782e80-74cc-11ea-8efa-703f9ac857be.png">

**Comment by matlcnieu** [comment]
OMG... i'm so confused.
Sorry for this useless message
I guess it's because there is a button to download the attached file.... my brain was maybe expecting a button to extract it.
thank you for your answer
good luck
