### ISSUE TITLE
Broken 'mark all unread' button on IMAP Accounts

### ISSUE THREAD

**Issue by Dormann** [protz/thunderbird-conversations#1469]
Thunderbird version 68.7.0 (64 bits)
Thunderbird Conversation version 3.0.17

* **Thunderbird version: 68.7.0 (64 bits)**
* **Thunderbird Conversation version: 3.0.17**
* **Operating System: Debian GNU/Linux 10 (Kernel: Linux 4.19.0-6-amd64)**

Since I last updated Thunderbird Conversations, all emails marked as read or unread using the 'mark all unread' button are not permanently marked as such.
While I stay on the current folder, it appears the change has succeeded.
But if I switch folder and then go back to the previous one, the email' status is back to before I marked it.
The same thing happens if I mark an email, place it in another folder and then goes to that folder.

This does not happen if I use the green dot provided by Thunderbird's interface, so I guess it comes from this add-on.

**Comment by Standard8** [comment]
Hi, thank you for the report. This is actually an issue with the APIs Thunderbird provides to extensions that I've just fixed: https://bugzilla.mozilla.org/show_bug.cgi?id=1631184

The fix should make it into the next Thunderbird release in about 3 weeks time. I'll leave this open until for tracking purposes.

This only affects IMAP accounts, local mail accounts and pop3 accounts shouldn't be affected.

As you say, the workaround for now is to use the dot on the thread pane to mark as read/unread.

**Comment by Dormann** [comment]
Haha, guess I was wrong to think it was the add-on's fault. ^^'
Thanks for the quick answer.

**Comment by Standard8** [comment]
Thunderbird 68.8.8 is out now, so updating to that version should fix this.
