### ISSUE TITLE
New email in a thread close all opened messages in it

### ISSUE THREAD

**Issue by Porkepix** [protz/thunderbird-conversations#1470]
* **Thunderbird version: 68.7.0**
* **Thunderbird Conversation version: 3.0.17**
* **Operating System: ArchLinux**

**What did you do?**
Read an email thread when a new email arrive in the same thread.

**What did you expect to happen?**
Just open the new one without doing anything else.

**What actually happened?**
It closed every opened email of the thread I was currently reading to just open the one that arrived in the same thread.

**Comment by Standard8** [comment]
Thanks for reporting this. I think I've just landed the fix for it now.
