### ISSUE TITLE
Uninstlation left my fodlers broken

### ISSUE THREAD

**Issue by pilaGit** [protz/thunderbird-conversations#1476]
I have tried and uninstalled your add-on. It did not return my folders to the original state. Add-on promised "do not worry, we will return everything back if you uninstall". That was a lie.

How do I return my Thunderbird folders to their original order?

**Comment by Standard8** [comment]
Per the [homepage of the add-on](https://addons.thunderbird.net/thunderbird/addon/gmail-conversation-view/): "To remove the unified folder view, hit View > Folders > All."

I don't know why it didn't restore that, it is possible that we've got some regression in there at the moment. We're going to have to rewrite some of that soon anyway.
