### ISSUE TITLE
Unresponsive when activated and many mails in folder

### ISSUE THREAD

**Issue by despecial** [protz/thunderbird-conversations#1479]
* **Thunderbird version:** 60.9.1 (64-Bit) 
* **Thunderbird Conversation version:** 2.14.7
* **Operating System:** MacOS Mojave 10.14.6

Trying to edit a sent message as new in the "sent folder" (containing about 16.000 mails)
Open the context menu immediatly and select "send as new"

Selecting the message took time.
Opening the context menu was okay but impossible to select the desired option.
Thunderbird hang up.

With the deactivated extension it works without any delay.

**Comment by Standard8** [comment]
Please can you clarify the steps to repeat. Exactly which buttons are you clicking on, exactly where are you right-clicking to open up the context menu, e.g. something like this would make it a lot clearer:

1. Select sent folder
2. Select message
3. Right click on ...

**Comment by despecial** [comment]
Sure. 

1.) Select sent folder
2.) Select conversation (open via arrow icon)
3.) Right click latest message
4.) Select ("edit as new" - german translation here)

Funny thing is: today it opens immediately. When I reported the issue I deactivated the extension and re-activated it.

**Comment by Standard8** [comment]
My suspicion is that you potentially clicked on something that was associated with a large conversation - we're still a little slow there, but hopefully the work we're currently doing will help towards that soon.

If it wasn't that, then I can only guess it was something in Thunderbird causing an issue.
