### ISSUE TITLE
Messages not marked "read" since upgrade to 3.1.2

### ISSUE THREAD

**Issue by RanTrycl** [protz/thunderbird-conversations#1484]
* **Thunderbird version:** 68.7.0
* **Thunderbird Conversation version:** 3.1.2
* **Operating System:** linux mint xfce

Since upgrading to 3.1.2, most everything seems to work fine except that read messages are not reporting back to the server that the message is read. Therefore, messages that come in since the 3.1.2 upgrade are eternally "new" and "unread" with no way to change this except at the server level. Running path-to-thunderbird -purgecaches did not change the behaviour.

**Comment by Standard8** [comment]
Please update to Thunderbird 68.8.0, there's a bug in 68.7.0 that caused the new APIs we are using not to work properly for IMAP accounts.
