### ISSUE TITLE
Feature Request: Latest sender displayed in Correspondents column

### ISSUE THREAD

**Issue by soundfx37** [protz/thunderbird-conversations#1485]
Thunder Bird 68.8.0
Thunderbird Conversation version: 3.0.18
Operating System: Windows 10 Home 64-bit Version: 18362.836

**What did you do?**
Turn on conversation mode and set Correspondents as a visible column

**What did you expect to happen?**
see the last person that replied instead of the first person to write the email.

**What actually happened?**
In a long email train only the first person to reply to an email is shown in the correspondents view.  This is very confusing when the conversation moves to another person.  For Example:  I send an email to Joe, Bob, and Susan.  Bob replies first and then never replies again.  The email thread continues between Susan and myself.  Even if Susan and I send 100 emails to each other, the "correspondents" column will only ever show "Bob" (because he replied first), even though he was never really part of the conversation.

It would be super helpful if the correspondents column changed to show the last person to engage in the conversation.  Or if a new column could be added that would show the last sender in a thread.

**Comment by Standard8** [comment]
I just re-read this and realised you were discussing the correspondent's column. That is actually managed by Thunderbird itself, so I've filed a bug with your request: https://bugzilla.mozilla.org/show_bug.cgi?id=1642199

You might want to try the between column, which is what Conversation provides and shows more information.

Closing out as this isn't a Conversations specific issue.

**Comment by soundfx37** [comment]
Hi Mark, Thanks. I've looked at the between column, but if I leave it a reasonable size, it shows the same info as the correspondents column (with myself added to the end).  Sent from my T-Mobile 4G LTE Device
-------- Original message --------From: Mark Banner <notifications@github.com> Date: 5/31/20  4:55 AM  (GMT-08:00) To: protz/thunderbird-conversations <thunderbird-conversations@noreply.github.com> Cc: soundfx37 <jfgass83@gmail.com>, Author <author@noreply.github.com> Subject: Re: [protz/thunderbird-conversations] Feature Request: Latest sender
  displayed in Correspondents column (#1485) 
I just re-read this and realised you were discussing the correspondent's column. That is actually managed by Thunderbird itself, so I've filed a bug with your request: https://bugzilla.mozilla.org/show_bug.cgi?id=1642199
You might want to try the between column, which is what Conversation provides and shows more information.
Closing out as this isn't a Conversations specific issue.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/protz/thunderbird-conversations/issues/1485#issuecomment-636461036",
"url": "https://github.com/protz/thunderbird-conversations/issues/1485#issuecomment-636461036",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
