### ISSUE TITLE
Ctrl+mousewheel doesn't work for text zooming

### ISSUE THREAD

**Issue by nofishonfriday** [protz/thunderbird-conversations#1487]
* **Thunderbird version:** 68.8.0
* **Thunderbird Conversation version:** 	3.1.2
* **Operating System:** Win 8.1x64

**What did you do?**
Ctrl+mousewheel to zoom in/out conversation text

**What did you expect to happen?**
Text zooms in/out

**What actually happened?**
Nothing.

Not totally sure, but I think this did work in previous versions.
Zooming in out via menu View > Zoom > does work as expected, it's just the mousewheel zoom that doesn't..
When I display messages in the classic reader (using "view using classic reader") Ctrl+mousewheel zooming also works, so I'd assume it's a Conversations issue.

Thanks.

**Comment by Standard8** [comment]
Unfortunately this is a Thunderbird issue that hits us, see #1044 for details.

**Comment by nofishonfriday** [comment]
Thanks for the clarification (and sorry for missing #1044).
