### ISSUE TITLE
Does not work with Thunderbird 77b3

### ISSUE THREAD

**Issue by luigifab** [protz/thunderbird-conversations#1488]
I updated from _Thunderbird stable_ to _Thunderbird 77 beta 3 on Linux 64_, and _thunderbird-conversations_ 3.0.18 seems to not work.

Conversation view does not appear.

**Comment by Standard8** [comment]
Yes, you'll need the 3.1.x series which I tried to roll out recently but there were problems. Need to wait a couple of weeks for the next Thunderbird update to happen, then will try again.

xref #1481

**Comment by Standard8** [comment]
3.1.6 is out now, so you should be able to update.

**Comment by luigifab** [comment]
That's true, and it works. thank you :)
