### ISSUE TITLE
White rectangle around conversation in version 3.1.6 on Dark schema

### ISSUE THREAD

**Issue by MartinBalin** [protz/thunderbird-conversations#1491]
Thunderbird 68.8.0 on Ubuntu 18.04 with Dark look and feel and TT DeepDark add on.
When Conversations updated today to 3.1.6 version it started to render white rectangle around email content in conversations. Is likely caused by this commit https://github.com/protz/thunderbird-conversations/commit/1a4d8d185009eacf6a001091839e14d12bfd4256
I built the Conversations from master and reverted changes in options.css and conversation.css to respect dark schema and it is working fine. I understand there was some reason for above mentioned commit. Just want to mention that this white rectangle around is really eyes hurting when you have your system in Dark schema.
![Conversations_update](https://user-images.githubusercontent.com/26064232/84277304-9df54480-ab33-11ea-9f07-842d362464d9.png)

options.css, line 5:
```
/*:root {
  --application-background-color: white;
  --application-foreground-color: black;
}
*/
@media screen and (prefers-color-scheme: dark) {
  :root {
    --application-background-color: rgb(56, 56, 61);
    --application-foreground-color: rgb(249, 249, 250);
  }
} 
```

conversation.css, line 5:

```
/*:root {
  --application-background-color: white;
  --application-foreground-color: black;
}
*/
@media screen and (prefers-color-scheme: dark) {
  :root {
    --application-background-color: rgb(56, 56, 61);
    --application-foreground-color: rgb(249, 249, 250);
  }
}
 ```

the rest of the files was not changed.
Great extension, anyway.

**Comment by Standard8** [comment]
I've just posted a new version for review to the add-ons site that limits the colour setting to just the light mode.

I'm not 100% sure it'll work, if you want to try it out before it gets reviewed, you can find the new version here: https://www.thebanners.uk/conversations-3.1.7.xpi

**Comment by Standard8** [comment]
Oh and I forgot to say, I think the proper fix for this would be to integrate with the dark mode of Thunderbird. I've investigated a little, and there's the option to support the system dark/light mode, or integrate with the applied them. Not quite sure the best way to go, that'll have to be investigated.

**Comment by vvarik** [comment]
> I've just posted a new version for review to the add-ons site that limits the colour setting to just the light mode.
> 
> I'm not 100% sure it'll work, if you want to try it out before it gets reviewed, you can find the new version here: https://www.thebanners.uk/conversations-3.1.7.xpi

Works for me. Thanks a lot!

**Comment by MartinBalin** [comment]
The new version from  https://www.thebanners.uk/conversations-3.1.7.xpi works for me. Looks great. Thank you.
![Conversations_3 1 7](https://user-images.githubusercontent.com/26064232/84474586-613c6100-ac8b-11ea-9def-1c606de9311b.png)

**Comment by Standard8** [comment]
3.1.9 is now out, so closing this out. #1313 is the issue to track for ongoing full support.

**Comment by sprangen** [comment]
Hi, i am now on version 3.1.17 on macOS and still experiencing the same beahviour, i get white rectangles around conversations when using dark mode. 
Seems like this was not fixed for mac (macOS 10.14. and Thundebird 68.10)?  
By the way, thank you for your great work!

**Comment by Standard8** [comment]
@sprangen please can you file a new issue. This was reported on Linux.

In that issue, please can you detail any add-ons you have installed and any settings that you've changed from the default (Help -> Troubleshooting Information may help, not sure). As far as I knew it isn't possible to get the dark mode display of the message itself on Mac with the default settings.

Fundamentally, dark mode isn't complete (xref #1313), and needs work.

**Comment by sprangen** [comment]
@Standard8 Thank you for you message. I will file a new issue.
