### ISSUE TITLE
Emails do not show

### ISSUE THREAD

**Issue by jonas-sk** [protz/thunderbird-conversations#1492]
* **Thunderbird version: 68.9.0**
* **Thunderbird Conversation version: 3.1.6**
* **Operating System: Windows 10**

**What did you do?**
I opened any email, either in the right-hand view or by clicking then on "show this conversation in a new tab".

**What did you expect to happen?**

Show the email.

**What actually happened?**

The whole view is empty. See the screenshot below. I think it happened after updating Thunderbird. Reinstalling the add-on and applying all the requested changes didn't change anything.

![image](https://user-images.githubusercontent.com/7535016/84285099-52e02f00-ab3d-11ea-90d4-36bc573a2bfe.png)

Installed addons: Exquilla for Exchange, Lightning, Provider for Google Calendar

**Comment by Standard8** [comment]
I've put a work around for this into a new version I've just published for review. I've also put a copy of it here, if you want to try it early: https://www.thebanners.uk/conversations-3.1.7.xpi

It would be very useful to know if that fixes your issue - if so, I'll see if we can get a fix into Thunderbird to prevent broken address books causing this in future.

**Comment by jonas-sk** [comment]
Removing ExQuilla worked, thank you! 

This issue seems to have only been introduced in the last Thunderbird update because beforehand everything worked fine, despite not having bothered to remove the Exchange account for months. The log4moz.js error also disappeared (before filing the error report, I had already reinstalled Conversations and didn't do it again after removing ExQuilla)
