### ISSUE TITLE
Can't remove label from message in conversation view

### ISSUE THREAD

**Issue by userlond** [protz/thunderbird-conversations#1494]
* **Thunderbird version: 68.9.0 (32-bit)**
* **Thunderbird Conversation version: 3.1.6**
* **Operating System: Windows 7 Professional Service Pack 1 64-bit**

**What did you do?**
I add two labels to the message, like on screenshot:
![scr_20200612080200](https://user-images.githubusercontent.com/7788670/84454276-4c100400-ac84-11ea-8209-3783cc810446.png)

**What did you expect to happen?**
I expect labels to be deleted when I click on close (x) button of label.

**What actually happened?**
Labels are not deletable this way. I can't delete label from conversation view, but can via Thundebird main menu.

It's possible to delete label from conversation view if there is only one label. But if there'are two labels, it's impossible. This issue wasn't reproducible on TC versions before 3.1.6.

**Comment by Standard8** [comment]
Thank you for the report, I've just fixed this on the latest master, and will release it in the next version, that will hopefully get approved soon.
