### ISSUE TITLE
Two copies of every attachment shown

### ISSUE THREAD

**Issue by Jakethethird** [protz/thunderbird-conversations#1499]
* **Thunderbird version:** 68.8.1
* **Thunderbird Conversation version:**  3.1.9
* **Operating System:** Ubuntu 20.04

**What did you do?** Addon automatically upgraded. It now shows 2 copies of every attachment. If I download attachments, it downloads, then tries to download a second time throwing up the warning that it will overwrite the first copy.

This is the case for new mails and old ones (pre update)

I've re-run the setup assistant, closed and reopened TB, uninstalled and reinstalled the addon, rebooted, etc. No change.

![20200615_screenshot_001](https://user-images.githubusercontent.com/28954472/84634255-13209b00-aee1-11ea-9888-b9b8a2743419.png)

**Comment by Standard8** [comment]
If you go into the add-ons manager, then select Conversation's preferences, do you have "I love attachments" checked?

I think if you uncheck that, then it will work correctly. Do you recall why you have it checked?

**Comment by Jakethethird** [comment]
I do have it selected and, upon deselecting it, there is only 1 now visible, not 2.
It was selected because I do love attachments and I've have had this selected for the last 5 years without this issue.

I have had the Show All Body Parts addon installed for 5 years also. 

The way the "I love attachments" option is described, it suggests there is a risk that I might lose (or not see) attachments, so that leads the user to slect it. Has this TB bug now been fixed so this workaround is no longer needed?

Thanks,
Jake.

**Comment by Standard8** [comment]
> The way the "I love attachments" option is described, it suggests there is a risk that I might lose (or not see) attachments, so that leads the user to slect it. Has this TB bug now been fixed so this workaround is no longer needed?

TBH, I've no idea, I was mainly wondering if we still needed it or not.

I can hopefully look into this later this week, I think it should be fairly simple to fix.

Note to self: start by looking at `getLateAttachments`.

**Comment by Standard8** [comment]
Okay, that was a silly mistake. I've fixed it now and it'll be released in the next version that's currently awaiting approval.
