### ISSUE TITLE
Very high CPU usage

### ISSUE THREAD

**Issue by RuralHunter** [protz/thunderbird-conversations#1504]
* **Thunderbird version:**
68.9.0(32 bits)
* **Thunderbird Conversation version:**
3.1.13
* **Operating System:**
Windows 10 64 bits
**What did you do?**
Just keep thunderbird idle and do nothing.
**What did you expect to happen?**
Thunderbird should use very little of CPU.
**What actually happened?**
With conversations enabled and being idle for 1 or 2 hours, thunderbird almost eats all my CPU and is not responding. After I disable conversations, the problem disappears.

**Comment by RuralHunter** [comment]
This happened since the time of thunderbird converstions release 3.1.0. I'm not sure if it's the new version of thunderbird itself causes the problem or it's the addon.

**Comment by Standard8** [comment]
My guess is that this is 'gloda', the global database, kicking in and re-indexing in the background.

If you go to the three-bar menu, Activity Manager, is there activity happening there, especially relating to indexing?

**Comment by RuralHunter** [comment]
No, there is not any indexing activity. I had more tests and it seems related to some specific messages. If I select that message, thunderbird gets very slow to respond and CPU usage soars. If I select other messages, everything looks ok.

**Comment by Standard8** [comment]
Could it be messages where you have lots of messages in the conversation?

**Comment by RuralHunter** [comment]
Not so many, it's just less than 10.

**Comment by Standard8** [comment]
@RuralHunter could you try getting a profile of the CPU usage? I've written some instructions on how to do this: https://github.com/protz/thunderbird-conversations/wiki/Profiling-Conversation's-Performance

Hopefully that should indicate the areas that are slow in the code.

**Comment by RuralHunter** [comment]
Just done that: https://share.firefox.dev/2zVHghg

**Comment by Standard8** [comment]
Thank you, that's a very interesting trace. We're trying to do things like block quoting in the message, but there's lots of iteration going on - I guess it is a complex message of some kind.

Is there a message that exhibits this that you'd be willing to forward to me for examination?

You could save it as HTML (select html in the dialog), and edit the text out of it if you want, depends on how complex it is.

The main thing for what I need will be the structure of the html.

**Comment by Standard8** [comment]
I have just made one minor improvement (d975a43c80) to make sure that we don't process the head section of an html email, but I suspect in the majority of cases that isn't going to make a significant change, as most emails don't have a head section, or if they do it is very small.

So at most it'll save us a few times round the loop, whereas in your case, we're going through at least a couple of hundred times.

**Comment by RuralHunter** [comment]
yes, it's the problem in html content! I can see the visual of the message keeps changing for ever. This is the message causes the problem:
[badmessage.zip](https://github.com/protz/thunderbird-conversations/files/4812257/badmessage.zip)

**Comment by Standard8** [comment]
Thank you for that, I haven't run with it yet, but it certainly looks like it could cause an issue due to all the recursion.

At a quick glance, I think there's a couple of things we could do:

* Have an allow list of items we iterate into. For example, we currently look at every item e.g. font tags, tables - none of those would seem to be necessary to look for blockquote sections within.
* Treat `<includetail>` as a blockquote. In your case, this would mean everything under the first `------------------ Original ------------------` would be collapsed.

I probably won't get chance to try anything out for a couple of days, but hopefully I'll get some time this week at some stage.

**Comment by Standard8** [comment]
@RuralHunter Thank you again for that message, I wasn't quite right about the cause, but the good news is I've worked out how to fix it.

I've just pushed up a new version for approval, so hopefully that will be out in a few days.

**Comment by RuralHunter** [comment]
ok, thank you very much for the quick responding. I will try the fix once it's released.

**Comment by RuralHunter** [comment]
I updated to 3.1.16. The CPU problem is fixed. But it seems I can not see attachment with some mails.
