### ISSUE TITLE
Reply All button in message view no longer visible

### ISSUE THREAD

**Issue by scootermorris** [protz/thunderbird-conversations#1507]
* 68.9.0 (64-bit)
* 3.1.16
* Fedora Core 32

After the update to 3.1.16 the "Reply All" button in the message view vanished for multiple recipients.   It's there in the classic view, the menu, and with a right click.

**Comment by Standard8** [comment]
Please can you provide a few more details? The reply-all button is working fine for all the cases I've tested.

For example, are any of the emails from your own identities? If you show details, are they all in the to/cc/bcc lines?

**Comment by jeremyheslop** [comment]
- 68.9.0 (64-bit)
- 3.1.16
- MacOS 10.15.4

Same issue. No "Reply All" button in conversation pane. Just Reply. This email has a person in CC. When I go into classic reply all is there.
<img width="1230" alt="Banners_and_Alerts_and_Inbox_-_jeremy_omnitechpro_com" src="https://user-images.githubusercontent.com/56492/86052246-b1a21580-ba24-11ea-989c-f2b53724df27.png">

**Comment by jeremyheslop** [comment]
>     * 68.9.0 (64-bit)
> 
>     * 3.1.16
> 
>     * MacOS 10.15.4
> 
> 
> Same issue. No "Reply All" button in conversation pane. Just Reply. This email has a person in CC. When I go into classic reply all is there.
> <img alt="Banners_and_Alerts_and_Inbox_-_jeremy_omnitechpro_com" width="1230" src="https://user-images.githubusercontent.com/56492/86052246-b1a21580-ba24-11ea-989c-f2b53724df27.png">

Ok so after quitting out of Thunderbird and loading back in it seems to be back to normal. I'm wondering if turning off the plugin and back helped before Quitting Thunderbird and opening back up.

It is also now properly listing all the "Conversations" where before it was not. Hopefully, this helps someone else.

**Comment by phoerious** [comment]
Since the last update, it has disappeared for me as well, making the add-on almost useless for my work email where I regularly have to reply to a bunch of people and mailing lists.

**Comment by jeremyheslop** [comment]
Agreed it is having some issues. I have some threads where it is showing reply all where there are multiple recipients and others where it does not. It is also not showing the conversation view on those items. The ones that do show the conversation view are also showing the reply-all.

**Comment by Standard8** [comment]
@jeremyheslop are you saying that it is still having issues after disable/enable and restarting?

If so, please can you give a better description of what is happening? I'm unable to reproduce at the moment.

Please could you also go into Conversations' preferences (via Add-ons), and turn on debugging at the bottom. Then restart, and subsequently go to Tools -> Developer Tools -> Error Console.

Once you've opened the error console, please clear it, then try selecting messages where you're seeing this broken, and where you're seeing this working. Once done, please right-click on the error console, select all, then right-click again and select copy message.

Please paste that output here and annotate or indicate (if possible) the broken vs good selections.

**Comment by jeremyleib** [comment]
Same issue for me. Neither uninstalling and reinstalling nor disabling and enabling helps for me.

**Comment by jeremyheslop** [comment]
@Standard8 yes. I just disabled, restarted, and enabled the plugin. I turned on debugging.

Console gives no errors on the threads that work. However when clicking on a thread where the reply-all does not show gives this error:

<img width="891" alt="Error_Console" src="https://user-images.githubusercontent.com/56492/86281540-b513d900-bbab-11ea-81df-7fdb8eec67be.png">

This is the error when clicking on a message where it is now showing an attachment:

<img width="890" alt="Error_Console" src="https://user-images.githubusercontent.com/56492/86281696-f0aea300-bbab-11ea-824e-beab87639cf5.png">

Looks to me like it is having issues with messages that are not indexed? I'm looking around and haven't found a good way to know if a message is indexed or not. In the activity manager it looks to be stuck on indexing Sent Mail. So this could be a problem. I'll turn off indexing and back on to see if that clears anything out.

**Comment by Standard8** [comment]
Thank you for the information, that's very useful. I see the error now - unfortunately a simple typo.

For the fallback, although it says it is bad, it is probably just mainly because of performance, and that we can't get the ideal data. We'll typically fallback in various folders (e.g. deleted where indexing doesn't normally happen) and also if you select a message very soon after it has arrived.

In any case, I'll get a new release heading out for this now we know what it is. There's another couple of issues it'd be nice to get out anyway.

**Comment by Standard8** [comment]
3.1.17 has been released now, so hopefully this should be working better.
