### ISSUE TITLE
tag button in the 'toolbar' of the conversation header

### ISSUE THREAD

**Issue by neandr** [protz/thunderbird-conversations#260]
unfortunately there is no button for 'tag' on the conversation header line, also with the [more  v] button there is no one.
Could it be added somehow?

Günter

**Comment by Standard8** [comment]
There hasn't been much interest in this, so I'm going to say that this probably wouldn't be that useful - there's other options like the number keys and the tag toolbar.

If there's a specific use case, then we might be able to accommodate that, but for now, I think we'll say no, and keep things simpler.
