### ISSUE TITLE
Implement navigation commands for conversations in a tab

### ISSUE THREAD

**Issue by ifireball** [protz/thunderbird-conversations#333]
When using the conversation view, one cannot use the "F", "B" of "N" keys to move out of the conversation even when there are now unread messages inside that conversation, this is cumbersome when one has many messages that do not belong in threads.

EDIT (jonathan):
This feature request is about being able to navigate in "standalone" mode , i.e. with a conversation in a tab. We could probably reuse the code from the standalone message window that instanciates a fake JS navigator, but this is likely super painful and difficult, so not going to happen any time soon.

**Comment by protz** [comment]
significant work required, both on the Conversations and the Thunderbird side, extra investigations needed to figure out how to do that

**Comment by Standard8** [comment]
As far as I can tell f, b and n are working fine in the latest master (might not work fully in the 2.15.x versions, I've not tested).
