### ISSUE TITLE
Allow toggle between default view and conversation view

### ISSUE THREAD

**Issue by progandy** [protz/thunderbird-conversations#395]
I'd like to have a hoktey and a button on each message in conversation view that allows me to toggle between the default message display and the conversation view. This will be very helpful while there are still actions and information in the default view which is not displayed in the conversation view. (eg return receipt requests, toolbar buttons, etc)

**Comment by alexrah** [comment]
hi,
I'd like to have directions on how to implement the "return receipt" button in conversation view.
Thanks!

**Comment by protz** [comment]
Hi there,

See https://github.com/protz/thunderbird-conversations/issues/129 for 
some thoughts; basically, you would need to re-implement the logic from 
http://mxr.mozilla.org/comm-central/source/mail/base/content/mailWindowOverlay.js#3070 
that detects whether the message wants a return receipt or not.

There are two codepaths: for messages that are streamed 
(MessageFromDbHdr), you just need to read the various headers after you 
get the MimeMsg. For messages that come from Gloda, you can implement a 
Gloda plugin at indexation-time (there are examples of that in the 
source) that flags each gloda message with a property that says whether 
the sender wants a return receipt.

Then, you need to re-implement the logic for sending the status delivery 
notification. You need to imitate:
- 
http://mxr.mozilla.org/comm-central/source/mailnews/extensions/mdn/src/nsMsgMdnGenerator.cpp#1052 
(to make sure that when the user views the message with the classic 
reader, they're not prompted to send it again)
- then you need to use modules/stdlib/send.js to send the delivery 
status notification (just re-implement the regular text that Thunderbird 
uses)

Feel free to ask for more guidance on 
https://github.com/protz/thunderbird-conversations/issues/129!

Cheers,

Jonathan

The steps would be as follows:
- in modules/message.js, modify MessageFromDbHdr

~ jonathan
