### ISSUE TITLE
Show the newest messages on the top

### ISSUE THREAD

**Issue by hrabur** [protz/thunderbird-conversations#424]
Hi,

Conversations is a great AddOn. The only feature I lack is the possibility to put the newest messages on top. I keep my inbox view pane sorted by date, where the newest is on the top. The opposite to this order the threads are displayed with the oldest on the top. The same applies to the message pane, where the oldest (the root) of the conversation is shown on the top.

When there are pretty big conversations this order may appear very inconvenient, because most of the time I'm aware of my conversations and I'm interested of the latest reply, so it sounds normal to expect to see the latest messages on the top either in the message thread tree see in the inbox pane and the conversation presentation in message pane.

Hope this helps,
Hrabur

**Comment by jpfleury** [comment]
For th record, here are duplicates (closed) of this bug: #447 #704 #871

**Comment by alexstaj** [comment]
has this changed?
