### ISSUE TITLE
Enigmail feature on quick reply

### ISSUE THREAD

**Issue by shirosaki** [protz/thunderbird-conversations#426]
If using quick reply, it is better that decrypt, encrypt and sign feature of Enigmail is usable.

I wrote a patch to add some Enigmail features to quick reply.
- decrypt quoted original message in draft
- check default account settings of sign, encrypt and PGP/MIME #410
- check per recipient rules
- confirm before send

In addition I refined code in tryEnigmail().
- detect pgp armor block properly using indent
- add convertFromUnicode to fix decrypting error of non-ascii message

Could you confirm this?
https://gist.github.com/1208000

It works fine in my testing.
But this patch is big, so there might be some defects.
It has duplicate code for the difficulty in reusing Enigmail code.

**Comment by bartpolot** [comment]
Hi, is there any chance this gets to be implemented? What is missing for this to work, Enigmail some API?

**Comment by Manko10** [comment]
Is someone still working on this? I'd love to use Enigmail through Quick Reply. But since I want to sign my mails by default I always have to use the classic reply window.
