### ISSUE TITLE
using horizontal line with compose

### ISSUE THREAD

**Issue by neandr** [protz/thunderbird-conversations#430]
With  a normal compose I added a horizontal line (html item:<hr>). No problem, it was shown as such -- during composing.

But saving and showing it in conversation view, starting with the <hr> position the rest of the document is shown as "quotation".

Seems it's a "conversation add-on" specific interpretation. Showing the message with TB in a new window and also showing it with GMail everything is as expected.

Do I miss something?

Guenter

**Comment by SimJoSt** [comment]
I just stumbled over the issue again. It's interesting to me, that the standard Thunderbird viewer doesn't have the same behavior as it is likely that it should show the Hotmail quotes correctly as well^^
Maybe now, as everything at Microsoft has been ported to the Office365 infrastructure and outlook.com, it can be changed.

**Comment by protz** [comment]
Hmm. Hotmail is gone? But outlook.com still uses the same crappy quoting using a horizontal line, right? Instead of using blockquote like the rest of the world.

**Comment by protz** [comment]
So I'm not sure what the right behavior would be...
