### ISSUE TITLE
HTML code appears in quick reply

### ISSUE THREAD

**Issue by hovs13** [protz/thunderbird-conversations#536]
HTML header coding appears when composing a quick reply message. see sample below.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
<meta http-equiv=Content-Type content="text/html; charset=windows-1252">
<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 12">
<meta name=Originator content="Microsoft Word 12">
<link rel=File-List href="Hovan%20Stepanian_files/filelist.xml">

<link rel=themeData href="Hovan%20Stepanian_files/themedata.thmx">
<link rel=colorSchemeMapping
href="Hovan%20Stepanian_files/colorschememapping.xml">

<style>

</style>

</head>

**Comment by Glaxiq** [comment]
Martin Keseg

**Comment by Glaxiq** [comment]
‏‪shysayh9@gmail.com‬‏

**Comment by Glaxiq** [comment]
> الرجاء قراءة العدد [رقم 352](https://github.com/thunderbird-conversations/thunderbird-conversations/issues/352)
