### ISSUE TITLE
Keyboard focus weirdness doesn't allow use of keyboard shortcuts

### ISSUE THREAD

**Issue by joedrew** [protz/thunderbird-conversations#550]
If I click in the Conversation view (Conversations 2.2.4), after I press 'n' to go to the next unread message (which works!) I can't then press 'n' again to go to the next-next unread message. However, if I click on the conversation again, it works.

Everything works fine if my keyboard focus is in the message list.

**Comment by zzzeek** [comment]
Trying to figure out how to get at least "apple-W" in OSX back?  This would only apply to a newly opened conversation window and would close the window when pressed.  I see there's a lot of stuff going on with keyBindings and propagation.   I would think that certain keys are safe to propagate if they are going to the window itself, in the case where we've opened a new window.   This would need I guess a "closeExternalWindow" command in message.js -> keybindings -> OSX

**Comment by protz** [comment]
Correct. Again, this is because there's no outer xul:window, meaning that
there are no standard keyboard shortcuts in that window.

**Comment by zzzeek** [comment]
OK is this #914 again?

**Comment by protz** [comment]
It could be fixed with a workaround, that is, you could add a listener in
stub.xhtml in the case that this is a quickCompose window that runs
windows.close whenever event.keyCode == 'w' && isMeta(event)...

**Comment by Standard8** [comment]
AFAIK this is all working in the latest versions. It seems to be working fine with the latest master on TB 68, and possibly with a few earlier versions.
