### ISSUE TITLE
reply box never uses fixed width fonts for plain text messages

### ISSUE THREAD

**Issue by ghost** [protz/thunderbird-conversations#553]
Hi,

I've been trying to make this work ever since I installed the extension to no avail. I tried on both v9.0.1 and v10.0 beta 4.

Basically, when I use the reply box in the threads view (conversations) for plain text messages, then my reply and the quoted text never appears in fixed width fonts. If I reply in a new window then it shows fine, as usual, with my configured fixed width font.

See screenshots here:

view in conversations: http://db.tt/LDObPloe
reply in conversations: http://db.tt/C2lin8Iv
reply in a new window: http://db.tt/UZfSQnIc

You can notice the message is clearly plain-text whereas the reply inside conversations is not. Clicking "reply in a new window" shows everything plain-text as normal.

I'm using Win 7 x64 and:
- Conversations 2.2.4 with tweak chrome fonts = off, tweak body fonts = off,
- Thunderbird 9.0.1 and 10.0b4 with the email account set to compose message in plain text (compose in html = off), message encoding (both in/out) is Western ISO-8859-1. allow messages to use other fonts = off

I'd really like and many times need to compose messages in plain-text directly in conversations so I hope this can be fixed soon. Please let me know if I can provide any other info.

Cheers

**Comment by jendrikw** [comment]
@protz It looks like this doesn't work anymore because there is now an iframe. Please gives us an update to the solution.
