### ISSUE TITLE
Conversation Plugin Is Adding Unrelated Emails To Thread

### ISSUE THREAD

**Issue by screenmachine** [protz/thunderbird-conversations#617]
Hello, I'm running Thunderbird 13.01, Thunderbird Conversations 2.3.2 on a Windows 7 Home Premium (64 bit) system.

Recently I noticed that emails from a conversation with a subject of "Red Widgets" are getting lumped into conversations with the subject line of "Blue Thingies" but not vice versa. Basically emails from two separate people are getting combined into a single conversation thread. Even if those emails are in the trash, a different folder, etc.

If I disable the conversations plugin everything reverts to normal, I've already uninstalled the plugin, reinstalled, even did the same with Thunderbird.

I am open to any and all thoughts!

**Comment by kaimast** [comment]
I just ran into this bug on a non-gmail account. Repair did fix it as well.
