### ISSUE TITLE
GMail-Conversation-View doesn't respect contact settings

### ISSUE THREAD

**Issue by KindDragon** [protz/thunderbird-conversations#652]
GMail-Conversation-View doesn't respect checkbox "Always display name instead of name from message header" from contact settings. GMail-Conversation-View  always display name from contact instead even if checkbox is off

**Comment by DarwinAwardWinner** [comment]
Was this ever fixed in the release version? I'm seeing this problem now in TC 2.14.7, and it can only be fixed by deleting the contact entirely as in #462.
