### ISSUE TITLE
signed/encrypted symbol for SMIME encrypted mails (some code in there to salvage!)

### ISSUE THREAD

**Issue by leoss** [protz/thunderbird-conversations#717]
Encryption of messages can be done in two ways in Thunderbird. GPG/PGP ist one method, SMIME is the second. I am using SMIME encryption.
I'm missing any symbol which indicates whether the signature of email is valid or the mail was encrypted. For Enigmail this information seems to be available and is implemented.

I started developing a plugin for gmail-conversation-view similar to enigmail plugin with the aim to indicate validity of  signed emails and so on. But I don't know how to access information of encryption status and signature status. In original thunderbird these status data is available in http://mxr.mozilla.org/comm-central/source/mailnews/extensions/smime/content/msgHdrViewSMIMEOverlay.js in the variables gEncryptionStatus and  gSignatureStatus.
Is there any way to access this information from a plugin of your extension?

**Comment by meteficha** [comment]
I know these "+1" posts are annoying, but this issue hasn't seen any news in a while.  So, +1, this would be great :).

**Comment by Standard8** [comment]
We now have tags to indicate signed status. I think that's enough, but feel free to re-open and add a bit more explanation if what we have isn't enough.
