### ISSUE TITLE
Reply to mailing list

### ISSUE THREAD

**Issue by hroncok** [protz/thunderbird-conversations#781]
In Thunderbird without this extension I can see a button Reply to mailing list (or conference, I'm not sure, as my Thunderbird is localized).

So when there is a mail from foo@bar.org in a mailing list list@list.org, I can:
- Reply (to foo@bar.org)
- Reply to the conference (to list@list.org)
- Reply to all (both)

Note that it doesn't matter if the Reply-To header is set to the sender or the list.

This functionality is hidden by this extension by only providing Reply (using address in Reply-To header) and Reply to all.

Could you please also offer reply to conference or reply to sender options?

Thanks

**Comment by gurvinderdadyala** [comment]
@protz is there any update on this feature. I am using Thunderbird version 31.4.0 and whenever i get email from mailing list I do not find option for reply to list, though this option is visible when you view message in classic reader.

**Comment by xi** [comment]
I am using the current master (357cc7c) with thunderbird 45. The most relevant reply option is directly available, all other (if applicable) from the dropdown menu and in the footer. So I guess this issue has been fixed.

**Comment by protz** [comment]
Thanks @xi. Closing.
