### ISSUE TITLE
Attachments of PGP/MIME message are not shown in conversation view

### ISSUE THREAD

**Issue by shirosaki** [protz/thunderbird-conversations#783]
With Thunderbird 24.2.0 and latest add-on, attachments of a PGP/MIME encrypted message are not shown in conversation view. But if I open a message in the classic reader, attachments are shown correctly.
With Thunderbird 17.0.8 and Thundervird Conversation 2.6.3 I can see attachments correctly.

It seems that PGP/MIME attachments information is not available in Thunderbird 24.2.0.

https://github.com/protz/GMail-Conversation-View/blob/d41cbd2bfffa61d8f07785af96046cc6e4eccd3c/modules/message.js#L1170

At above code (in function buildAttachmentViewIfNeeded()), I checked attachments length with TB 24.2.0 and got 0 even if the encrypted message had an attachment.
With TB 17.0.8, I got 1 as expected.

```
Log.debug('allAttachments: ' + aMimeMsg.allAttachments.length);
Log.debug('allUserAttachments: ' + aMimeMsg.allUserAttachments.length);
```

Any ideas? Thanks.

**Comment by jmigual** [comment]
Hey hi, it seems to me that this is happening again. If an email has inline image attachments they show up properly but if it has additional files attached at the bottom only the text content is displayed and neither the images or the attached file is shown.

**Comment by firefoxlover** [comment]
The issue seems to be solved, at least an already decrypted message is shown.

It doesnt show the "this message cannot be decrypted as the secret key is missing" dialog.
