### ISSUE TITLE
Enhance Enigmail interaction with more UI (especially quick reply)

### ISSUE THREAD

**Issue by klorydryk** [protz/thunderbird-conversations#791]
Hi,
When a conversation is encrypted with enigmail, if I use Conversation "quick response" plugin at some point, the email is sent without any encryption, with all conversation history.

It is very important to maintain the conversation protection. Add buttons to encrypt/sign ?

**Edit**: sub-issues in #711 #747 #640

**Comment by bartpolot** [comment]
In the current version the behaviour I see is that 'quick reply' *always* sends the message unencrypted (no matter what the enigmail settings, per-recipient rules or conversation history) but does *not* include previous messages unencrypted, just the PGP ciphertext quoted.

**Comment by protz** [comment]
Yes, this is a bug in the current version. Any help in fixing this would
be highly appreciated! :)

~ jonathan

**Comment by bartpolot** [comment]
I wish I had the time... (don't we all?)

**Comment by RalfJung** [comment]
Also see #1015, there's some trouble with Conversations fetching the default setting from Enigmail and applying it to quick replies.

**Comment by Standard8** [comment]
Looks like this was fixed by #1029 but didn't get closed when that was merged. If there's more missing, please feel free to file new issues.
