### ISSUE TITLE
Inline reply with r or Shift+R keyboard shortcut

### ISSUE THREAD

**Issue by orschiro** [protz/thunderbird-conversations#803]
I noticed that here is only `Ctrl+Shift+R` to reply to a message by keyboard shortcut.

However, this opens a new compose window for the reply.

Is it possible to map `r` or `Shift+R` for inline replies?

So that the cursor automatically jumps to the reply field below the message.

Thanks for your advice!

**Comment by Standard8** [comment]
Duplicate of #739
