### ISSUE TITLE
FossaMail compatibility?

### ISSUE THREAD

**Issue by Gittyperson** [protz/thunderbird-conversations#842]
Thanks a lot for your excellent extension. Version 2.7 works fine in this new Thunderbird-based client but 2.8 (with its many improvements) is reported incompatible and won't install. Would it be possible to add FossaMail compatibility for the newer versions, too?

**Comment by MartinX3** [comment]
FossaMail is now based on LTS Thunderbird v38.
There are some compatibility issues with conversations v2.10.2 and enigmail v1.9.6.1

Mails are sometimes not decrypted, instead, they are showing the encrypted stuff.
And the tags which are showing you if the mail is encrypted/signed are missing.
If i disable conversations, everything is working.
