### ISSUE TITLE
Support for spell check correction in inline reply

### ISSUE THREAD

**Issue by orschiro** [protz/thunderbird-conversations#850]
Hi there,

Is it technically possible to have support for context menu spell check correction in the inline reply mode?

Currently I do not see these in the context menu when right clicking on a misspelled word.

See the following screenshot:

![spell-check-conversations](https://cloud.githubusercontent.com/assets/170947/4045055/fded4f32-2d25-11e4-8eda-5a08ed5eae8e.png)

Thanks for listening!

**Comment by protz** [comment]
The fix has made it to both Aurora and Nightly.

**Comment by ghiamar** [comment]
Hi @protz sorry to bother but I have Thunderbird V31.7.0 and Conversation plugin V2.8.1 but I still can't get the spell checker to work. Should I do something more than have Thunderbird stable updated?

Thanks for your help!

**Comment by protz** [comment]
This will be fixed once you get upgraded to Thunderbird 38.

**Comment by ghiamar** [comment]
Great! Thanks a lot!
