### ISSUE TITLE
[Enigmail] Multiple password prompts when opening conversations (Windows-only)

### ISSUE THREAD

**Issue by notger** [protz/thunderbird-conversations#875]
When opening an encrypted conversation thread, I get prompted multiple times for my PGP password, one for each message in the thread.

TB Conversations calls gpg.exe for decryption multiple times, where it should only call once and subsequently use that key to decrypt all the messages in the thread.

This only happens in Windows. Linux setup does not have these problems.

System setup:
- Windows 7
- Thunderbird 24.6.0 and 31.2
  -> Thunderbird Conversation 2.7
  -> EnigMail 1.7.2 (set to use gpg.exe)

**Comment by zeitkunst** [comment]
I have the same issue and would be happy to provide more info or test any solutions. It's becoming an issue that may cause me to move away from tb conversations on Windows, but again, I'm happy to help out if I can.

**Comment by Standard8** [comment]
I've not heard of this recently, but if it is still an issue on the latest versions, please feel free to reopen or file a new one.
