### ISSUE TITLE
Conversation wont find mail unless opened (Exquilla exchange account)

### ISSUE THREAD

**Issue by NikMel** [protz/thunderbird-conversations#878]
Hi, and thanks for a great extension.

On an Exchange account (using the Exquilla 31.0.1136) Conversation won't find a reply or a mail moved to a new folder, unless clicked on. This leaves many of my mail conversations incomplete (especially wrt my replies).

Steps to reproduce:
1a. In a conversation, make a reply, or
1b. Move a mail in a conversation to a new folder (or archive, trash)

Expected result:
- The conversation should include the mail from 1a and 1b with a button indicating its location

Observed result:
- The mail is not shown

Workaround:
1. Open the folder (e.g. the "Sent" folder for case 1a)
2. Click the mail (i.e. explicitly showing it, effectively removing the twinkle/star-thingy TB puts in front of it)
3. Now, viewing the original conversation includes the mail from 1a and 1b

Versions:
OS: Ubuntu 14.10
TB: 31.2.0
GMail-Conversations-View: 2.8.1 (last updated Aug 8 2014)
Exquilla for MS Exchange: 31.0.1136 (last updated 2014-10-27)

Update:
I should add that with two other accounts (one IMAP and one GMail) all works as expected.

All the best,
Niklas

**Comment by Standard8** [comment]
TBH this more sounds like a bug with how Exquilla is setting things up. Unfortunately much has changed between now and then.

I'm going to close this out, but feel free to re-open if this is still an issue. Seeing if there's any errors on the error console might help as well.
