### ISSUE TITLE
enigmail can't decrypt inline PGP messages in conversations view

### ISSUE THREAD

**Issue by pravi** [protz/thunderbird-conversations#901]
it works when manually select view in classic reader option

**Comment by m-kuhn** [comment]
I can confirm this.
Although sometimes decrypting works but I cannot tell the reason for this.

**Comment by pianoslum** [comment]
IIRC inline PGP is a bit problematic with Conversations; however @shirosaki is the man for this kind of question, I think

**Comment by dmitrydonskih** [comment]
+1, I confirm this.
MT 38.6.0, EnigMail 1.9, 
gpg (GnuPG) 2.0.29 (Gpg4win 2.2.6)
I can reproduce it and send details on request.

**Comment by shirosaki** [comment]
Current released version 2.10.2 doesn't work with Enigmail 1.9.
Please try latest development version.
https://jonathan.protzenko.fr/thunderbird-conversations/

**Comment by MartinX3** [comment]
Same here:
FossaMail based on LTS Thunderbird v38.
There are some compatibility issues with conversations v2.10.2 and enigmail v1.9.6.1

Mails are sometimes not decrypted, instead, they are showing the encrypted stuff.
And the tags which are showing you if the mail is encrypted/signed are missing.
If i disable conversations, everything is working.

I already tried to deactivate the checkboxes in the wizard.
I think the problem is the conversation "view".

**Comment by norristh** [comment]
I have the same problem with Conversations 2.11.4, Enigmail 1.9.6.1, and Thunderbird 45.8.0.  I believe all PGP/MIME emails display fine, but at least some inline PGP texts show still encrypted in conversation view.  To read them, I need to Open in classic viewer, Reply/Forward, disable the Conversations add-on, or go to View and uncheck "Conversation View."  I can provide more info or samples as requested.

Thanks for a great add-on!

**Comment by shirosaki** [comment]
@norristh  I cannot reproduce the issue with inline PGP.
I need samples to fix it.

**Comment by norristh** [comment]
It actually started working for me a while ago, presumably after updating Conversations, Enigmail, or Thunderbird.

**Comment by Standard8** [comment]
A lot of changes have been made over the last couple of years with respect to Thunderbird, Conversations and Engimail. If this is still an issue with the latest versions of each, please file a new issue and we can take a look - be prepared to give examples though.
