### ISSUE TITLE
Conversation quick reply does not work for Exquilla exchange account

### ISSUE THREAD

**Issue by atbest** [protz/thunderbird-conversations#910]
I have one Exquilla exchange account and a gmail account. When I use the quick reply box, "From" account does show the exchange account, but it actually uses my gmail account to send the email. If I click the Reply in a new window, email will be sent with the exchange account without problems.

I am using 64-bit Windows 7 with thunderbird 31.4.0, Exquilla 31.0.1136 and thunderbird conversation 2.8.1.

**Comment by protz** [comment]
Yeah, this is problematic. I should probably get an Exquilla account just to test it, because many features seem to be broken with Conversations.

**Comment by atbest** [comment]
Can we disable Conversations for Exquilla account temporarily?

**Comment by protz** [comment]
Yes, I believe that would be easy to do. Do you know how to detect in the
code if a message is from exquilla?

**Comment by atbest** [comment]
I don't know the code, but I have good news to report. After upgrading Thunderbird to 31.6.0 and ExQuilla to 38.0.1156 version, Conversation quick reply works normally now for my exchange account. So you may not need to work on this for the time being.

**Comment by Standard8** [comment]
According to the last message here, this may now be working, hence closing out. If it is still an issue, please feel free to re-open.
