### ISSUE TITLE
Wrong "special" characters in Between/Sender field

### ISSUE THREAD

**Issue by XDomanX** [protz/thunderbird-conversations#924]
I have an issue with displaying characters in Between/Sender. See the example images. The top marks are with wrong characters from these fields and the bottom marks are with the correct characters that displays in message area.

![wrong characters in sender - example 1](https://cloud.githubusercontent.com/assets/11420315/6592338/3c4bd93c-c7cd-11e4-97fe-eedd103863cc.jpg)
![wrong characters in sender - example 2](https://cloud.githubusercontent.com/assets/11420315/6592337/3c4b8752-c7cd-11e4-85b8-3d94176fb8f5.jpg)
![wrong characters in sender - example 3](https://cloud.githubusercontent.com/assets/11420315/6592339/3c5313fa-c7cd-11e4-9f5a-2e003820e8de.jpg)

**Comment by protz** [comment]
Can you please forward this message to me as an attachment? (My email address is on my github profile page.)

Also, what is your locale (if you know it)?

**Comment by protz** [comment]
Tools > Forward As > Attachment

**Comment by Standard8** [comment]
AFAICT this is fixed in the current 2.13.3 version of conversations. @XDomanX would you be able to retry this please?

**Comment by Standard8** [comment]
I believe this is fixed, no response from reporter, so closing out. Please reopen with details if it is still happening on the latest.
