### ISSUE TITLE
Key customization panel confused

### ISSUE THREAD

**Issue by protz** [protz/thunderbird-conversations#927]
STR:
- open addon manager
- open keycustomization panel
- close addon manager
- reopen addon manager
- try to open keycustomization panel

(From #851 )

**Comment by pianoslum** [comment]
It's just that we set a flag when opening the key-customization panel but don't set it back when closing the window.
Do we need that logic anyway? Could there be a second window to edit the keys?

Otherwise we should add a listener when the pref-window is closed an reset the flag! I could do it ;-)

**Comment by protz** [comment]
I think the flag is there to prevent the dialog from being open from 
multiple windows at the same time, because then there's a lot of state 
in it and state would get confused if two windows edit the preferences 
at the same time.

So, yeah, clearing the flag upon window closing seems like the right fix.

**Comment by pianoslum** [comment]
Hey, I couldn't find the right listener yet...
Do you have an idea? I could add this to my fixes; but it's very minor, so it doesn't matter if it's not in the new release...

**Comment by protz** [comment]
http://mxr.mozilla.org/comm-central/source/mail/base/content/tabmail.xml#707

Apparently you can add a tabMonitor on tabmail that will receive a notification when a tab is closed, meaning that you can watch when the addon manager is closed, possibly check whether Conversation's options were being displayed, and act accordingly (disable keycustomizations).

The same should probably be done for when a window is closed, I suppose.

Here's an example on how to register a tab monitor: http://mxr.mozilla.org/comm-central/source/calendar/lightning/content/messenger-overlay-sidebar.js#146

Let me know if that helps! I'm merging your other pull request in the meanwhile.

**Comment by protz** [comment]
(I've submitted a first attempt to addons.mozilla.org -- since it usually gets rejected on the first try, I'd rather get a head start. But if you submit a pull request for -master I'll take care of cherry-picking your fixes for the 2.9+ branch.)

**Comment by pianoslum** [comment]
I wanted to add a listener to `let tabmail = window.document.getElementById('tabmail');` in bootstrap.js. But there's neither a window nor a document during startup(), is there?

Maybe I have very little time this weekend; if that's too long, that fix will be included in 2.9.1 :-)

BTW: Why is an AddOn usually rejected?

**Comment by protz** [comment]
Right, you should register that listener in the monkeyPatchWindow routine,
because that one gets called once a window is loaded and ready (when
bootstrap.js executes, there's no window yet, that's why we register window
opened handlers).

The addon is usually rejected because there's warnings / you have to argue
with addons.mozilla.org reviewers / my addon is big and bundles jquery +
plugins / makes it hard to review.

**Comment by protz** [comment]
Well the addon got accepted, so that's good news! You're credited in the
"version information" section :).

~ jonathan

**Comment by pianoslum** [comment]
Cool ;-)

**Comment by Standard8** [comment]
We've removed key customisations from the latest versions as they broke and then didn't appear to be used much.
