### ISSUE TITLE
get rid of the "between" column

### ISSUE THREAD

**Issue by protz** [protz/thunderbird-conversations#932]
the new "correspondents" column in Thunderbird is just much better

**Comment by protz** [comment]
also, do that *after* the branching to 2.9

**Comment by GICodeWarrior** [comment]
Hi, I upgraded Thunderbird recently and noticed the new Correspondents column.

The new column doesn't show the same information the Between column did.  For example, I receive a lot of messages via distribution lists, and the new column only shows the sender.  The Between column would show me the recipients as well so I could know what lists it was sent to.

Do you know if there is any way to get the old behavior back in the current version of Thunderbird & Conversations?
