### ISSUE TITLE
Select/copy filename of attachment

### ISSUE THREAD

**Issue by MLopez-Ibanez** [protz/thunderbird-conversations#950]
When viewing a message within a conversation, attachments appear as:

icon filename
       size | preview | open | save

I would like to select and copy the filename but it is currently not possible (neither the size).

**Comment by MLopez-Ibanez** [comment]
The workaround is to click save, then the filename will be offered for saving and (at least in Linux), it can be easily copied.

**Comment by MLopez-Ibanez** [comment]
I'm not sure if it is new (I don't update often enough), but the filenames are now also displayed on the header and they are selectable. Not a fix to the original issue, but better than clicking in "save".

**Comment by Standard8** [comment]
Just to note I've just fixed this and it should be in a release soon. I changed the draggable area to just the background square for the attachment, so the text can now be selected. Note that unfortunately drag and drop is broken at the moment (#1418).

I've also expanded the are you can click on to preview the attachment to the background square as well.
