### ISSUE TITLE
New API for interfacing Enigmail

### ISSUE THREAD

**Issue by pbrunschwig** [protz/thunderbird-conversations#978]
We did a big refactoring of the Enigmail core. The consequences are that the JS-modules to include have changed and the various methods have moved to different modules.

Please  check the Enigmail source for details: https://sourceforge.net/p/enigmail/source/ci/master/tree/ or contact me if you need further infos.

**Comment by protz** [comment]
Hey Patrick,

Thanks for letting me know, this is highly appreciated. I currently have very little bandwidth available for the addon, so this is slightly worrying — I don't know where I'll find the time to fix this.

Do you have an ETA / target version number?

@shirosaki what's your opinion? Is it a big change?

Cheers,

Jonathan

**Comment by pbrunschwig** [comment]
The ETA for the next Enigmail release (v1.9) is November earliest.

**Comment by shirosaki** [comment]
I installed enigmail nightly builld and test it. 
https://www.enigmail.net/download/nightly.php
In some cases message body of PGP/MIME messages in a thread looks empty. It needs investigation.
