### ISSUE TITLE
Conversation buttons icons not centered

### ISSUE THREAD

**Issue by wagnerand** [protz/thunderbird-conversations#987]
I'm wondering why no one has reported this yet, but on my MacBook Pro running 10.10.4 and Thunderbird 38.1.0 with TbConversations 2.9.1 the conversation buttons are off, see screenshot.
<img width="208" alt="screen shot 2015-07-16 at 11 50 27" src="https://cloud.githubusercontent.com/assets/873258/8720137/246516f6-2bb1-11e5-8b7d-a69abc8f1f58.png">

**Comment by protz** [comment]
Huh. I no longer use a Mac so I didn't notice. Thanks for the report. Any way  you could submit a patch that doesn't break other platforms?

**Comment by wagnerand** [comment]
Can you give me a hint where to start?

**Comment by protz** [comment]
I would setup
https://developer.mozilla.org/en-US/docs/Tools/Remote_Debugging/Thunderbird
and use the Firefox developer tools to inspect the conversation view to
figure out which CSS rule is wrong exactly.

~ jonathan

**Comment by wagnerand** [comment]
I know how to debug Thunderbird in general. What I'd need is a starting point where to look in the DOM. I don't know how to find your message pane.

**Comment by protz** [comment]
Well the inspect tool from the firefox dev tools gives you a way to 
click on the DOM element you want, doesn't it?

**Comment by wagnerand** [comment]
Wow, I didn't know that worked for chrome-debugging...impressive.

**Comment by wagnerand** [comment]
So, the rule causing this is https://github.com/protz/GMail-Conversation-View/blob/master/skin/conversation.css#L111. If you remove disable the `width: 30px;` rule, the width is 36px.
What's the supposed width of that button? In order words, should we fix the aligned with `width: 30px;` or should we fix the width itself?
